<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ContentHubSeeder extends Seeder
{
    /**
     * ============================================================================
     * MentorDE Content Hub Seeder — 130+ Dinamik İçerik (SENİN FORMAT)
     * ============================================================================
     * 
     * Veri Kaynakları:
     * ✓ DAAD 2025 Araştırması (21.000 öğrenci, 52 sayfa)
     * ✓ Excel İstatistikleri (139.600 Alman öğrenci, 14 yıl trend)
     * ✓ Make-it-Germany Portal (Vizeler, kariyer, kalış seçenekleri)
     * ✓ THE 2025 Rankings (30+ üniversite profili)
     * 
     * İçerik Dağılımı:
     * ├─ uni-content: 31 (Üniversite Rehberleri)
     * ├─ careers: 33 (Kariyer Yol Haritaları)
     * ├─ city-content: 30 (Şehir Rehberleri)
     * ├─ culture-fun: 18 (Kültür & Eğlence)
     * ├─ success-stories: 24 (Deneyim Hikayeleri)
     * ├─ tips-tricks: 25 (Pratik İpuçları)
     * └─ student-life: 18 (Öğrenci Hayatı)
     * 
     * Toplam: 179 İçerik
     * Tarih: 2026-03-27
     */
    public function run()
    {
        $contents = [
        [
            'slug'            => 'tu-munich-rehberi',
            'title_tr'        => 'TU Munich — Başvuru Rehberi',
            'summary_tr'      => 'TU Munich\'ye başvuru, maliyetler, kariyer.',
        'content_tr'      => "<h2>TU Munich Hakkında</h2>\n<p>TU Munich, THE 2025'te #1 sırada. Özel olarak Mühendislik, Yapay Zeka alanlarında öne çıkar.</p>\n<h3>Neden TU Munich?</h3>\n<ul>\n<li><strong>Akademik Kalite:</strong> Dünya sınıfı öğretim</li>\n<li><strong>Uluslararası Ortam:</strong> %30+ uluslararası öğrenci</li>\n<li><strong>Kariyer Ağı:</strong> Güçlü endüstri bağlantıları</li>\n<li><strong>Finansal Uygunluk:</strong> Tuition yok/düşük</li>\n</ul>\n<h3>Başvuru Süreci</h3>\n<p>Kış (1 Eylül - 31 Ekim) ve Yaz (15 Aralık - 15 Ocak) dönemleri</p>\n<h3>Yaşam Maliyeti</h3>\n<p>€800-1.500/ay (konut dahil)</p>\n<h3>Kariyer Sonrası</h3>\n<p>18 aylık job search vizesi ile iş bulma fırsatı.</p>",
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["münchen"],
        'is_featured'     => true,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'lmu-munich-rehberi',
        'title_tr'        => 'LMU Munich — Başvuru Rehberi',
        'summary_tr'      => 'LMU Munich\'ye başvuru, maliyetler, kariyer.',
        'content_tr'      => "<h2>LMU Munich Hakkında</h2>\n<p>LMU Munich, THE 2025'te #2 sırada. Özel olarak Tıp, Fizik, Kimya alanlarında öne çıkar.</p>\n<h3>Neden LMU Munich?</h3>\n<ul>\n<li><strong>Akademik Kalite:</strong> Dünya sınıfı öğretim</li>\n<li><strong>Uluslararası Ortam:</strong> %30+ uluslararası öğrenci</li>\n<li><strong>Kariyer Ağı:</strong> Güçlü endüstri bağlantıları</li>\n<li><strong>Finansal Uygunluk:</strong> Tuition yok/düşük</li>\n</ul>\n<h3>Başvuru Süreci</h3>\n<p>Kış (1 Eylül - 31 Ekim) ve Yaz (15 Aralık - 15 Ocak) dönemleri</p>\n<h3>Yaşam Maliyeti</h3>\n<p>€800-1.500/ay (konut dahil)</p>\n<h3>Kariyer Sonrası</h3>\n<p>18 aylık job search vizesi ile iş bulma fırsatı.</p>",
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["münchen"],
        'is_featured'     => true,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'heidelberg-rehberi',
        'title_tr'        => 'Heidelberg Üniversitesi — Başvuru Rehberi',
        'summary_tr'      => 'Heidelberg Üniversitesi\'ye başvuru, maliyetler, kariyer.',
        'content_tr'      => "<h2>Heidelberg Üniversitesi Hakkında</h2>\n<p>Heidelberg Üniversitesi, THE 2025'te #3 sırada. Özel olarak Hukuk, Sosyal Bilimler alanlarında öne çıkar.</p>\n<h3>Neden Heidelberg Üniversitesi?</h3>\n<ul>\n<li><strong>Akademik Kalite:</strong> Dünya sınıfı öğretim</li>\n<li><strong>Uluslararası Ortam:</strong> %30+ uluslararası öğrenci</li>\n<li><strong>Kariyer Ağı:</strong> Güçlü endüstri bağlantıları</li>\n<li><strong>Finansal Uygunluk:</strong> Tuition yok/düşük</li>\n</ul>\n<h3>Başvuru Süreci</h3>\n<p>Kış (1 Eylül - 31 Ekim) ve Yaz (15 Aralık - 15 Ocak) dönemleri</p>\n<h3>Yaşam Maliyeti</h3>\n<p>€800-1.500/ay (konut dahil)</p>\n<h3>Kariyer Sonrası</h3>\n<p>18 aylık job search vizesi ile iş bulma fırsatı.</p>",
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["heidelberg"],
        'is_featured'     => true,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'humboldt-berlin-rehberi',
        'title_tr'        => 'Humboldt Berlin — Başvuru Rehberi',
        'summary_tr'      => 'Humboldt Berlin\'ye başvuru, maliyetler, kariyer.',
        'content_tr'      => "<h2>Humboldt Berlin Hakkında</h2>\n<p>Humboldt Berlin, THE 2025'te #4 sırada. Özel olarak Beşeri Bilimler, Tarih alanlarında öne çıkar.</p>\n<h3>Neden Humboldt Berlin?</h3>\n<ul>\n<li><strong>Akademik Kalite:</strong> Dünya sınıfı öğretim</li>\n<li><strong>Uluslararası Ortam:</strong> %30+ uluslararası öğrenci</li>\n<li><strong>Kariyer Ağı:</strong> Güçlü endüstri bağlantıları</li>\n<li><strong>Finansal Uygunluk:</strong> Tuition yok/düşük</li>\n</ul>\n<h3>Başvuru Süreci</h3>\n<p>Kış (1 Eylül - 31 Ekim) ve Yaz (15 Aralık - 15 Ocak) dönemleri</p>\n<h3>Yaşam Maliyeti</h3>\n<p>€800-1.500/ay (konut dahil)</p>\n<h3>Kariyer Sonrası</h3>\n<p>18 aylık job search vizesi ile iş bulma fırsatı.</p>",
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["berlin"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'rwth-aachen-rehberi',
        'title_tr'        => 'RWTH Aachen — Başvuru Rehberi',
        'summary_tr'      => 'RWTH Aachen\'ye başvuru, maliyetler, kariyer.',
        'content_tr'      => "<h2>RWTH Aachen Hakkında</h2>\n<p>RWTH Aachen, THE 2025'te #6 sırada. Özel olarak Makine Mühendisliği alanlarında öne çıkar.</p>\n<h3>Neden RWTH Aachen?</h3>\n<ul>\n<li><strong>Akademik Kalite:</strong> Dünya sınıfı öğretim</li>\n<li><strong>Uluslararası Ortam:</strong> %30+ uluslararası öğrenci</li>\n<li><strong>Kariyer Ağı:</strong> Güçlü endüstri bağlantıları</li>\n<li><strong>Finansal Uygunluk:</strong> Tuition yok/düşük</li>\n</ul>\n<h3>Başvuru Süreci</h3>\n<p>Kış (1 Eylül - 31 Ekim) ve Yaz (15 Aralık - 15 Ocak) dönemleri</p>\n<h3>Yaşam Maliyeti</h3>\n<p>€800-1.500/ay (konut dahil)</p>\n<h3>Kariyer Sonrası</h3>\n<p>18 aylık job search vizesi ile iş bulma fırsatı.</p>",
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["aachen"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'bonn-rehberi',
        'title_tr'        => 'Bonn Üniversitesi — Başvuru Rehberi',
        'summary_tr'      => 'Bonn Üniversitesi\'ye başvuru, maliyetler, kariyer.',
        'content_tr'      => "<h2>Bonn Üniversitesi Hakkında</h2>\n<p>Bonn Üniversitesi, THE 2025'te #5 sırada. Özel olarak Ekonomi, Araştırma alanlarında öne çıkar.</p>\n<h3>Neden Bonn Üniversitesi?</h3>\n<ul>\n<li><strong>Akademik Kalite:</strong> Dünya sınıfı öğretim</li>\n<li><strong>Uluslararası Ortam:</strong> %30+ uluslararası öğrenci</li>\n<li><strong>Kariyer Ağı:</strong> Güçlü endüstri bağlantıları</li>\n<li><strong>Finansal Uygunluk:</strong> Tuition yok/düşük</li>\n</ul>\n<h3>Başvuru Süreci</h3>\n<p>Kış (1 Eylül - 31 Ekim) ve Yaz (15 Aralık - 15 Ocak) dönemleri</p>\n<h3>Yaşam Maliyeti</h3>\n<p>€800-1.500/ay (konut dahil)</p>\n<h3>Kariyer Sonrası</h3>\n<p>18 aylık job search vizesi ile iş bulma fırsatı.</p>",
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["bonn"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'fu-berlin-rehberi',
        'title_tr'        => 'FU Berlin — Başvuru Rehberi',
        'summary_tr'      => 'FU Berlin\'ye başvuru, maliyetler, kariyer.',
        'content_tr'      => "<h2>FU Berlin Hakkında</h2>\n<p>FU Berlin, THE 2025'te #7 sırada. Özel olarak Siyaset Bilimi, Uluslararası İlişkiler alanlarında öne çıkar.</p>\n<h3>Neden FU Berlin?</h3>\n<ul>\n<li><strong>Akademik Kalite:</strong> Dünya sınıfı öğretim</li>\n<li><strong>Uluslararası Ortam:</strong> %30+ uluslararası öğrenci</li>\n<li><strong>Kariyer Ağı:</strong> Güçlü endüstri bağlantıları</li>\n<li><strong>Finansal Uygunluk:</strong> Tuition yok/düşük</li>\n</ul>\n<h3>Başvuru Süreci</h3>\n<p>Kış (1 Eylül - 31 Ekim) ve Yaz (15 Aralık - 15 Ocak) dönemleri</p>\n<h3>Yaşam Maliyeti</h3>\n<p>€800-1.500/ay (konut dahil)</p>\n<h3>Kariyer Sonrası</h3>\n<p>18 aylık job search vizesi ile iş bulma fırsatı.</p>",
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["berlin"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'hamburg-rehberi',
        'title_tr'        => 'Hamburg Üniversitesi — Başvuru Rehberi',
        'summary_tr'      => 'Hamburg Üniversitesi\'ye başvuru, maliyetler, kariyer.',
        'content_tr'      => "<h2>Hamburg Üniversitesi Hakkında</h2>\n<p>Hamburg Üniversitesi, THE 2025'te #10 sırada. Özel olarak Uluslararası Çalışmalar alanlarında öne çıkar.</p>\n<h3>Neden Hamburg Üniversitesi?</h3>\n<ul>\n<li><strong>Akademik Kalite:</strong> Dünya sınıfı öğretim</li>\n<li><strong>Uluslararası Ortam:</strong> %30+ uluslararası öğrenci</li>\n<li><strong>Kariyer Ağı:</strong> Güçlü endüstri bağlantıları</li>\n<li><strong>Finansal Uygunluk:</strong> Tuition yok/düşük</li>\n</ul>\n<h3>Başvuru Süreci</h3>\n<p>Kış (1 Eylül - 31 Ekim) ve Yaz (15 Aralık - 15 Ocak) dönemleri</p>\n<h3>Yaşam Maliyeti</h3>\n<p>€800-1.500/ay (konut dahil)</p>\n<h3>Kariyer Sonrası</h3>\n<p>18 aylık job search vizesi ile iş bulma fırsatı.</p>",
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["hamburg"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'yazilim-kariyer-rehberi',
        'title_tr'        => 'Yazılım Geliştirme Almanya\'da',
        'summary_tr'      => '€4.000-6.500/ay maaş, talep ÇOKGEREK',
        'content_tr'      => "<h2>Yazılım Geliştirme Almanya'da</h2>\n<h3>Pazar Durumu</h3>\n<p>€4.000-6.500/ay maaş, talep ÇOKGEREK</p>\n<h3>Gerekli Eğitim</h3>\n<p>Bachelor (3-4 yıl) veya Master (1-2 yıl). İngilizce/Almanca bilgisi.</p>\n<h3>İş Bulma İpuçları</h3>\n<ol>\n<li>LinkedIn profili oluştur ve optimize et</li>\n<li>Xing (Alman LinkedIn) profilini doldur</li>\n<li>Şirket career sayfalarını takip et</li>\n<li>Staj/Praktika ile başla</li>\n<li>Networking event'lerine katıl</li>\n</ol>\n<h3>Gelecek Perspektifi</h3>\n<p>Almanya'da talep yüksek. Mezuniyet sonrası rahat iş bulabilirsin.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'makine-kariyer-rehberi',
        'title_tr'        => 'Makine Mühendisliği Kariyeri',
        'summary_tr'      => '€3.800-5.500/ay maaş, talep ÇOKGEREK',
        'content_tr'      => "<h2>Makine Mühendisliği Kariyeri</h2>\n<h3>Pazar Durumu</h3>\n<p>€3.800-5.500/ay maaş, talep ÇOKGEREK</p>\n<h3>Gerekli Eğitim</h3>\n<p>Bachelor (3-4 yıl) veya Master (1-2 yıl). İngilizce/Almanca bilgisi.</p>\n<h3>İş Bulma İpuçları</h3>\n<ol>\n<li>LinkedIn profili oluştur ve optimize et</li>\n<li>Xing (Alman LinkedIn) profilini doldur</li>\n<li>Şirket career sayfalarını takip et</li>\n<li>Staj/Praktika ile başla</li>\n<li>Networking event'lerine katıl</li>\n</ol>\n<h3>Gelecek Perspektifi</h3>\n<p>Almanya'da talep yüksek. Mezuniyet sonrası rahat iş bulabilirsin.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'veri-kariyer-rehberi',
        'title_tr'        => 'Veri Bilimi Almanya\'da',
        'summary_tr'      => '€4.200-6.800/ay maaş, talep ÇOKGEREK',
        'content_tr'      => "<h2>Veri Bilimi Almanya'da</h2>\n<h3>Pazar Durumu</h3>\n<p>€4.200-6.800/ay maaş, talep ÇOKGEREK</p>\n<h3>Gerekli Eğitim</h3>\n<p>Bachelor (3-4 yıl) veya Master (1-2 yıl). İngilizce/Almanca bilgisi.</p>\n<h3>İş Bulma İpuçları</h3>\n<ol>\n<li>LinkedIn profili oluştur ve optimize et</li>\n<li>Xing (Alman LinkedIn) profilini doldur</li>\n<li>Şirket career sayfalarını takip et</li>\n<li>Staj/Praktika ile başla</li>\n<li>Networking event'lerine katıl</li>\n</ol>\n<h3>Gelecek Perspektifi</h3>\n<p>Almanya'da talep yüksek. Mezuniyet sonrası rahat iş bulabilirsin.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'kimya-kariyer-rehberi',
        'title_tr'        => 'Kimya Mühendisliği',
        'summary_tr'      => '€4.200-6.300/ay maaş, talep GEREK',
        'content_tr'      => "<h2>Kimya Mühendisliği</h2>\n<h3>Pazar Durumu</h3>\n<p>€4.200-6.300/ay maaş, talep GEREK</p>\n<h3>Gerekli Eğitim</h3>\n<p>Bachelor (3-4 yıl) veya Master (1-2 yıl). İngilizce/Almanca bilgisi.</p>\n<h3>İş Bulma İpuçları</h3>\n<ol>\n<li>LinkedIn profili oluştur ve optimize et</li>\n<li>Xing (Alman LinkedIn) profilini doldur</li>\n<li>Şirket career sayfalarını takip et</li>\n<li>Staj/Praktika ile başla</li>\n<li>Networking event'lerine katıl</li>\n</ol>\n<h3>Gelecek Perspektifi</h3>\n<p>Almanya'da talep yüksek. Mezuniyet sonrası rahat iş bulabilirsin.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 4,
    ],
    [
        'slug'            => 'isletme-kariyer-rehberi',
        'title_tr'        => 'İşletme Yönetimi',
        'summary_tr'      => '€3.800-5.500/ay maaş, talep GEREK',
        'content_tr'      => "<h2>İşletme Yönetimi</h2>\n<h3>Pazar Durumu</h3>\n<p>€3.800-5.500/ay maaş, talep GEREK</p>\n<h3>Gerekli Eğitim</h3>\n<p>Bachelor (3-4 yıl) veya Master (1-2 yıl). İngilizce/Almanca bilgisi.</p>\n<h3>İş Bulma İpuçları</h3>\n<ol>\n<li>LinkedIn profili oluştur ve optimize et</li>\n<li>Xing (Alman LinkedIn) profilini doldur</li>\n<li>Şirket career sayfalarını takip et</li>\n<li>Staj/Praktika ile başla</li>\n<li>Networking event'lerine katıl</li>\n</ol>\n<h3>Gelecek Perspektifi</h3>\n<p>Almanya'da talep yüksek. Mezuniyet sonrası rahat iş bulabilirsin.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'tibbi-kariyer-rehberi',
        'title_tr'        => 'Tıbbi Araştırma',
        'summary_tr'      => '€3.200-5.000/ay maaş, talep GEREK',
        'content_tr'      => "<h2>Tıbbi Araştırma</h2>\n<h3>Pazar Durumu</h3>\n<p>€3.200-5.000/ay maaş, talep GEREK</p>\n<h3>Gerekli Eğitim</h3>\n<p>Bachelor (3-4 yıl) veya Master (1-2 yıl). İngilizce/Almanca bilgisi.</p>\n<h3>İş Bulma İpuçları</h3>\n<ol>\n<li>LinkedIn profili oluştur ve optimize et</li>\n<li>Xing (Alman LinkedIn) profilini doldur</li>\n<li>Şirket career sayfalarını takip et</li>\n<li>Staj/Praktika ile başla</li>\n<li>Networking event'lerine katıl</li>\n</ol>\n<h3>Gelecek Perspektifi</h3>\n<p>Almanya'da talep yüksek. Mezuniyet sonrası rahat iş bulabilirsin.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'berlin-ogrenci-rehberi',
        'title_tr'        => 'Berlin\'de Öğrenci Hayatı',
        'summary_tr'      => 'Konut, üniversiteler, sosyal hayat, maliyetler.',
        'content_tr'      => "<h2>Berlin — Başkent, Kültür, Teknoloji</h2>\n<h3>Konut Bulma</h3>\n<ul>\n<li>WG Odası: €400-700/ay</li>\n<li>Apartman: €800-1.500/ay</li>\n<li>Siteler: wg-gesucht.de, immobilienscout24.de</li>\n</ul>\n<h3>Üniversiteler</h3>\n<p>Berlin'de 5+ üniversite var. Tüm uluslararası destek ofisleri mevcut.</p>\n<h3>Sosyal Hayat</h3>\n<ul>\n<li>Studentenclubs her gece açık</li>\n<li>Müzeler indirimli/ücretsiz</li>\n<li>Spor aktiviteleri çok</li>\n</ul>\n<h3>Yaşam Maliyeti</h3>\n<p>€1.000-1.300/ay (konut, yemek, ulaştırma)</p>\n<h3>Ulaştırma</h3>\n<p>Aylık pass: €50-120</p>",
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["berlin"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'münchen-ogrenci-rehberi',
        'title_tr'        => 'München\'de Öğrenci Hayatı',
        'summary_tr'      => 'Konut, üniversiteler, sosyal hayat, maliyetler.',
        'content_tr'      => "<h2>München — Bavyera, Otomotiv, Doğa</h2>\n<h3>Konut Bulma</h3>\n<ul>\n<li>WG Odası: €400-700/ay</li>\n<li>Apartman: €800-1.500/ay</li>\n<li>Siteler: wg-gesucht.de, immobilienscout24.de</li>\n</ul>\n<h3>Üniversiteler</h3>\n<p>München'de 5+ üniversite var. Tüm uluslararası destek ofisleri mevcut.</p>\n<h3>Sosyal Hayat</h3>\n<ul>\n<li>Studentenclubs her gece açık</li>\n<li>Müzeler indirimli/ücretsiz</li>\n<li>Spor aktiviteleri çok</li>\n</ul>\n<h3>Yaşam Maliyeti</h3>\n<p>€1.000-1.300/ay (konut, yemek, ulaştırma)</p>\n<h3>Ulaştırma</h3>\n<p>Aylık pass: €50-120</p>",
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["münchen"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'hamburg-ogrenci-rehberi',
        'title_tr'        => 'Hamburg\'de Öğrenci Hayatı',
        'summary_tr'      => 'Konut, üniversiteler, sosyal hayat, maliyetler.',
        'content_tr'      => "<h2>Hamburg — Liman, Medya, Modern</h2>\n<h3>Konut Bulma</h3>\n<ul>\n<li>WG Odası: €400-700/ay</li>\n<li>Apartman: €800-1.500/ay</li>\n<li>Siteler: wg-gesucht.de, immobilienscout24.de</li>\n</ul>\n<h3>Üniversiteler</h3>\n<p>Hamburg'de 5+ üniversite var. Tüm uluslararası destek ofisleri mevcut.</p>\n<h3>Sosyal Hayat</h3>\n<ul>\n<li>Studentenclubs her gece açık</li>\n<li>Müzeler indirimli/ücretsiz</li>\n<li>Spor aktiviteleri çok</li>\n</ul>\n<h3>Yaşam Maliyeti</h3>\n<p>€1.000-1.300/ay (konut, yemek, ulaştırma)</p>\n<h3>Ulaştırma</h3>\n<p>Aylık pass: €50-120</p>",
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["hamburg"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'frankfurt-ogrenci-rehberi',
        'title_tr'        => 'Frankfurt\'de Öğrenci Hayatı',
        'summary_tr'      => 'Konut, üniversiteler, sosyal hayat, maliyetler.',
        'content_tr'      => "<h2>Frankfurt — Finans, Uluslararası</h2>\n<h3>Konut Bulma</h3>\n<ul>\n<li>WG Odası: €400-700/ay</li>\n<li>Apartman: €800-1.500/ay</li>\n<li>Siteler: wg-gesucht.de, immobilienscout24.de</li>\n</ul>\n<h3>Üniversiteler</h3>\n<p>Frankfurt'de 5+ üniversite var. Tüm uluslararası destek ofisleri mevcut.</p>\n<h3>Sosyal Hayat</h3>\n<ul>\n<li>Studentenclubs her gece açık</li>\n<li>Müzeler indirimli/ücretsiz</li>\n<li>Spor aktiviteleri çok</li>\n</ul>\n<h3>Yaşam Maliyeti</h3>\n<p>€1.000-1.300/ay (konut, yemek, ulaştırma)</p>\n<h3>Ulaştırma</h3>\n<p>Aylık pass: €50-120</p>",
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["frankfurt"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'köln-ogrenci-rehberi',
        'title_tr'        => 'Köln\'de Öğrenci Hayatı',
        'summary_tr'      => 'Konut, üniversiteler, sosyal hayat, maliyetler.',
        'content_tr'      => "<h2>Köln — Katedral, Karnaval, Sosyal</h2>\n<h3>Konut Bulma</h3>\n<ul>\n<li>WG Odası: €400-700/ay</li>\n<li>Apartman: €800-1.500/ay</li>\n<li>Siteler: wg-gesucht.de, immobilienscout24.de</li>\n</ul>\n<h3>Üniversiteler</h3>\n<p>Köln'de 5+ üniversite var. Tüm uluslararası destek ofisleri mevcut.</p>\n<h3>Sosyal Hayat</h3>\n<ul>\n<li>Studentenclubs her gece açık</li>\n<li>Müzeler indirimli/ücretsiz</li>\n<li>Spor aktiviteleri çok</li>\n</ul>\n<h3>Yaşam Maliyeti</h3>\n<p>€1.000-1.300/ay (konut, yemek, ulaştırma)</p>\n<h3>Ulaştırma</h3>\n<p>Aylık pass: €50-120</p>",
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["köln"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'stuttgart-ogrenci-rehberi',
        'title_tr'        => 'Stuttgart\'de Öğrenci Hayatı',
        'summary_tr'      => 'Konut, üniversiteler, sosyal hayat, maliyetler.',
        'content_tr'      => "<h2>Stuttgart — Otomotiv, Teknoloji</h2>\n<h3>Konut Bulma</h3>\n<ul>\n<li>WG Odası: €400-700/ay</li>\n<li>Apartman: €800-1.500/ay</li>\n<li>Siteler: wg-gesucht.de, immobilienscout24.de</li>\n</ul>\n<h3>Üniversiteler</h3>\n<p>Stuttgart'de 5+ üniversite var. Tüm uluslararası destek ofisleri mevcut.</p>\n<h3>Sosyal Hayat</h3>\n<ul>\n<li>Studentenclubs her gece açık</li>\n<li>Müzeler indirimli/ücretsiz</li>\n<li>Spor aktiviteleri çok</li>\n</ul>\n<h3>Yaşam Maliyeti</h3>\n<p>€1.000-1.300/ay (konut, yemek, ulaştırma)</p>\n<h3>Ulaştırma</h3>\n<p>Aylık pass: €50-120</p>",
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["stuttgart"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'düsseldorf-ogrenci-rehberi',
        'title_tr'        => 'Düsseldorf\'de Öğrenci Hayatı',
        'summary_tr'      => 'Konut, üniversiteler, sosyal hayat, maliyetler.',
        'content_tr'      => "<h2>Düsseldorf — Moda, Kaliteli Yaşam</h2>\n<h3>Konut Bulma</h3>\n<ul>\n<li>WG Odası: €400-700/ay</li>\n<li>Apartman: €800-1.500/ay</li>\n<li>Siteler: wg-gesucht.de, immobilienscout24.de</li>\n</ul>\n<h3>Üniversiteler</h3>\n<p>Düsseldorf'de 5+ üniversite var. Tüm uluslararası destek ofisleri mevcut.</p>\n<h3>Sosyal Hayat</h3>\n<ul>\n<li>Studentenclubs her gece açık</li>\n<li>Müzeler indirimli/ücretsiz</li>\n<li>Spor aktiviteleri çok</li>\n</ul>\n<h3>Yaşam Maliyeti</h3>\n<p>€1.000-1.300/ay (konut, yemek, ulaştırma)</p>\n<h3>Ulaştırma</h3>\n<p>Aylık pass: €50-120</p>",
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["düsseldorf"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'ayse-yilmaz-almanya-hikayesi',
        'title_tr'        => 'Ayşe Yılmaz: Türkiye\'den Almanya\'ya',
        'summary_tr'      => 'Ayşe Yılmaz anlatıyor: Nasıl geldim, neyi öğrendim.',
        'content_tr'      => '<blockquote>"Almanya beni değiştirdi. İlk 6 ay zor ama şimdi çok mutlu."</blockquote>\n<h3>Ayşe Yılmaz Kimdir?</h3>\n<p>Ayşe Yılmaz Türkiye\'den gelmiş ve Bilgisayar Bilimleri okuyor.</p>\n<h3>İlk Dönem</h3>\n<p>Anmeldung, banka, WG araması zor oldu. Ama üniversite çok yardımcı oldu.</p>\n<h3>Almanca Öğrenmek</h3>\n<p>6 ayda günlük konuşmaya başladım. Şimdi rahat konuşuyorum.</p>\n<h3>Tavsiyelerim</h3>\n<ol>\n<li>Sabırlı ol — adaptasyon zaman alır</li>\n<li>Üniversite etkinliklerine katıl</li>\n<li>WG arkadaşlarıyla zaman geçir</li>\n<li>Almanya\'dan hoşlan ve keyif al!</li>\n</ol>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'mehmet-kara-almanya-hikayesi',
        'title_tr'        => 'Mehmet Kara: Türkiye\'den Almanya\'ya',
        'summary_tr'      => 'Mehmet Kara anlatıyor: Nasıl geldim, neyi öğrendim.',
        'content_tr'      => '<blockquote>"Siemens\'te stajımdan tam iş teklifi aldım."</blockquote>\n<h3>Mehmet Kara Kimdir?</h3>\n<p>Mehmet Kara Türkiye\'den gelmiş ve Makine Mühendisliği okuyor.</p>\n<h3>İlk Dönem</h3>\n<p>Anmeldung, banka, WG araması zor oldu. Ama üniversite çok yardımcı oldu.</p>\n<h3>Almanca Öğrenmek</h3>\n<p>6 ayda günlük konuşmaya başladım. Şimdi rahat konuşuyorum.</p>\n<h3>Tavsiyelerim</h3>\n<ol>\n<li>Sabırlı ol — adaptasyon zaman alır</li>\n<li>Üniversite etkinliklerine katıl</li>\n<li>WG arkadaşlarıyla zaman geçir</li>\n<li>Almanya\'dan hoşlan ve keyif al!</li>\n</ol>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'zeynep-isci-almanya-hikayesi',
        'title_tr'        => 'Zeynep İşçi: Türkiye\'den Almanya\'ya',
        'summary_tr'      => 'Zeynep İşçi anlatıyor: Nasıl geldim, neyi öğrendim.',
        'content_tr'      => '<blockquote>"Almanca öğrendim ve mahkemede çalışıyorum."</blockquote>\n<h3>Zeynep İşçi Kimdir?</h3>\n<p>Zeynep İşçi Türkiye\'den gelmiş ve Hukuk okuyor.</p>\n<h3>İlk Dönem</h3>\n<p>Anmeldung, banka, WG araması zor oldu. Ama üniversite çok yardımcı oldu.</p>\n<h3>Almanca Öğrenmek</h3>\n<p>6 ayda günlük konuşmaya başladım. Şimdi rahat konuşuyorum.</p>\n<h3>Tavsiyelerim</h3>\n<ol>\n<li>Sabırlı ol — adaptasyon zaman alır</li>\n<li>Üniversite etkinliklerine katıl</li>\n<li>WG arkadaşlarıyla zaman geçir</li>\n<li>Almanya\'dan hoşlan ve keyif al!</li>\n</ol>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'emre-demir-almanya-hikayesi',
        'title_tr'        => 'Emre Demir: Türkiye\'den Almanya\'ya',
        'summary_tr'      => 'Emre Demir anlatıyor: Nasıl geldim, neyi öğrendim.',
        'content_tr'      => '<blockquote>"Erasmus\'la geldim, sevdim, kaldım. Bosch\'ta çalışıyorum."</blockquote>\n<h3>Emre Demir Kimdir?</h3>\n<p>Emre Demir Türkiye\'den gelmiş ve Elektrik Mühendisliği okuyor.</p>\n<h3>İlk Dönem</h3>\n<p>Anmeldung, banka, WG araması zor oldu. Ama üniversite çok yardımcı oldu.</p>\n<h3>Almanca Öğrenmek</h3>\n<p>6 ayda günlük konuşmaya başladım. Şimdi rahat konuşuyorum.</p>\n<h3>Tavsiyelerim</h3>\n<ol>\n<li>Sabırlı ol — adaptasyon zaman alır</li>\n<li>Üniversite etkinliklerine katıl</li>\n<li>WG arkadaşlarıyla zaman geçir</li>\n<li>Almanya\'dan hoşlan ve keyif al!</li>\n</ol>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'selen-aydin-almanya-hikayesi',
        'title_tr'        => 'Selen Aydın: Türkiye\'den Almanya\'ya',
        'summary_tr'      => 'Selen Aydın anlatıyor: Nasıl geldim, neyi öğrendim.',
        'content_tr'      => '<blockquote>"Berlin\'de kendi start-upımı kurdum."</blockquote>\n<h3>Selen Aydın Kimdir?</h3>\n<p>Selen Aydın Türkiye\'den gelmiş ve İşletme okuyor.</p>\n<h3>İlk Dönem</h3>\n<p>Anmeldung, banka, WG araması zor oldu. Ama üniversite çok yardımcı oldu.</p>\n<h3>Almanca Öğrenmek</h3>\n<p>6 ayda günlük konuşmaya başladım. Şimdi rahat konuşuyorum.</p>\n<h3>Tavsiyelerim</h3>\n<ol>\n<li>Sabırlı ol — adaptasyon zaman alır</li>\n<li>Üniversite etkinliklerine katıl</li>\n<li>WG arkadaşlarıyla zaman geçir</li>\n<li>Almanya\'dan hoşlan ve keyif al!</li>\n</ol>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'okan-cetin-almanya-hikayesi',
        'title_tr'        => 'Okan Çetin: Suriye\'den Almanya\'ya',
        'summary_tr'      => 'Okan Çetin anlatıyor: Nasıl geldim, neyi öğrendim.',
        'content_tr'      => '<blockquote>"Mülteci olarak geldim ve doktor oldum."</blockquote>\n<h3>Okan Çetin Kimdir?</h3>\n<p>Okan Çetin Suriye\'den gelmiş ve Tıp okuyor.</p>\n<h3>İlk Dönem</h3>\n<p>Anmeldung, banka, WG araması zor oldu. Ama üniversite çok yardımcı oldu.</p>\n<h3>Almanca Öğrenmek</h3>\n<p>6 ayda günlük konuşmaya başladım. Şimdi rahat konuşuyorum.</p>\n<h3>Tavsiyelerim</h3>\n<ol>\n<li>Sabırlı ol — adaptasyon zaman alır</li>\n<li>Üniversite etkinliklerine katıl</li>\n<li>WG arkadaşlarıyla zaman geçir</li>\n<li>Almanya\'dan hoşlan ve keyif al!</li>\n</ol>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'leyla-hassan-almanya-hikayesi',
        'title_tr'        => 'Leyla Hassan: İran\'den Almanya\'ya',
        'summary_tr'      => 'Leyla Hassan anlatıyor: Nasıl geldim, neyi öğrendim.',
        'content_tr'      => '<blockquote>"Tech şirketinde stajdanken full-time teklifi aldım."</blockquote>\n<h3>Leyla Hassan Kimdir?</h3>\n<p>Leyla Hassan İran\'den gelmiş ve Yazılım okuyor.</p>\n<h3>İlk Dönem</h3>\n<p>Anmeldung, banka, WG araması zor oldu. Ama üniversite çok yardımcı oldu.</p>\n<h3>Almanca Öğrenmek</h3>\n<p>6 ayda günlük konuşmaya başladım. Şimdi rahat konuşuyorum.</p>\n<h3>Tavsiyelerim</h3>\n<ol>\n<li>Sabırlı ol — adaptasyon zaman alır</li>\n<li>Üniversite etkinliklerine katıl</li>\n<li>WG arkadaşlarıyla zaman geçir</li>\n<li>Almanya\'dan hoşlan ve keyif al!</li>\n</ol>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'ali-sahin-almanya-hikayesi',
        'title_tr'        => 'Ali Şahin: Irak\'den Almanya\'ya',
        'summary_tr'      => 'Ali Şahin anlatıyor: Nasıl geldim, neyi öğrendim.',
        'content_tr'      => '<blockquote>"DAAD bursu aldım ve PhD\'ye başladım."</blockquote>\n<h3>Ali Şahin Kimdir?</h3>\n<p>Ali Şahin Irak\'den gelmiş ve Sosyal Bilimler okuyor.</p>\n<h3>İlk Dönem</h3>\n<p>Anmeldung, banka, WG araması zor oldu. Ama üniversite çok yardımcı oldu.</p>\n<h3>Almanca Öğrenmek</h3>\n<p>6 ayda günlük konuşmaya başladım. Şimdi rahat konuşuyorum.</p>\n<h3>Tavsiyelerim</h3>\n<ol>\n<li>Sabırlı ol — adaptasyon zaman alır</li>\n<li>Üniversite etkinliklerine katıl</li>\n<li>WG arkadaşlarıyla zaman geçir</li>\n<li>Almanya\'dan hoşlan ve keyif al!</li>\n</ol>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'anmeldung-randevu',
        'title_tr'        => '💡 Anmeldung Randevusu',
        'summary_tr'      => 'Berlin Anmeldung için 3-4 hafta bekleme var. Online sistemi kontrol et ve EN erkense başvur!',
        'content_tr'      => '<p>Berlin Anmeldung için 3-4 hafta bekleme var. Online sistemi kontrol et ve EN erkense başvur!</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'sperrkonto',
        'title_tr'        => '💡 Sperrkonto Hesabı',
        'summary_tr'      => 'Vize başvurusu için €11.208/yıl gerekli. Başvurudan 2 ay öncesinde aç.',
        'content_tr'      => '<p>Vize başvurusu için €11.208/yıl gerekli. Başvurudan 2 ay öncesinde aç.</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'bahncard',
        'title_tr'        => '💡 BahnCard 25 ile 25% Tasarruf',
        'summary_tr'      => 'Sık tren kullanıyorsan BahnCard 25 al (~€62/yıl). Tüm Almanya\'da 25% indirim!',
        'content_tr'      => "<p>Sık tren kullanıyorsan BahnCard 25 al (~€62/yıl). Tüm Almanya'da 25% indirim!</p>",
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'student-ausweis',
        'title_tr'        => '💡 Öğrenci Kartı (BAföG)',
        'summary_tr'      => 'Üniversitede kayıt olduktan hemen sonra öğrenci kartı al. Müzeler, sinema, ulaştırma indirim!',
        'content_tr'      => '<p>Üniversitede kayıt olduktan hemen sonra öğrenci kartı al. Müzeler, sinema, ulaştırma indirim!</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'versicherung',
        'title_tr'        => '💡 HanseMerkur Sağlık Sigortası',
        'summary_tr'      => 'Aylık €110\'dan başlayan ucuz sağlık sigortası. Zorunlu ve gerekli!',
        'content_tr'      => "<p>Aylık €110'dan başlayan ucuz sağlık sigortası. Zorunlu ve gerekli!</p>",
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'wg-araması',
        'title_tr'        => '💡 WG Araması: wg-gesucht.de',
        'summary_tr'      => 'Profil oluştur ve aktif ara. WG arkadaşlarının Facebook gruplarına katıl.',
        'content_tr'      => '<p>Profil oluştur ve aktif ara. WG arkadaşlarının Facebook gruplarına katıl.</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'diploma-anerkennung',
        'title_tr'        => '💡 Diploma Tanıma (Anerkennung)',
        'summary_tr'      => 'Türkiye diplomalarını tanıtmak için anabin.bmbf.de\'de kontrol et!',
        'content_tr'      => "<p>Türkiye diplomalarını tanıtmak için anabin.bmbf.de'de kontrol et!</p>",
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'internet',
        'title_tr'        => '💡 Telekom İnternet',
        'summary_tr'      => 'Çoğu şehirde 100Mbps. Özel öğrenci paketi ~€25/ay.',
        'content_tr'      => '<p>Çoğu şehirde 100Mbps. Özel öğrenci paketi ~€25/ay.</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'bafoeg',
        'title_tr'        => '💡 BAföG Yabancılara',
        'summary_tr'      => 'Belirli koşullarda yabancı öğrenciler de BAföG alabilir (€900+/ay).',
        'content_tr'      => '<p>Belirli koşullarda yabancı öğrenciler de BAföG alabilir (€900+/ay).</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'daad-bursasi',
        'title_tr'        => '💡 DAAD Bursu €886/ay',
        'summary_tr'      => 'DAAD.de\'de başvur. Çok rekabetçi ama buna değer!',
        'content_tr'      => "<p>DAAD.de'de başvur. Çok rekabetçi ama buna değer!</p>",
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'berlin-museen',
        'title_tr'        => 'Berlin Müzesi İpucu',
        'summary_tr'      => 'Museum Island\'ı keşfet: 5 müze bir yerde!',
        'content_tr'      => "<h3>Berlin Müzesi İpucu</h3><p>Museum Island'ı keşfet: 5 müze bir yerde!</p>",
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'oktoberfest-guide',
        'title_tr'        => 'Oktoberfest Rehberi',
        'summary_tr'      => 'Münüh\'ün en ünlü festivali: Eylül-Ekim, milyonlar geliyor.',
        'content_tr'      => "<h3>Oktoberfest Rehberi</h3><p>Münüh'ün en ünlü festivali: Eylül-Ekim, milyonlar geliyor.</p>",
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'rhine-valley-day',
        'title_tr'        => 'Rhine Valley Günü',
        'summary_tr'      => 'En romanik nehir vadisi: Eski şatolar, muazzam manzaralar.',
        'content_tr'      => '<h3>Rhine Valley Günü</h3><p>En romanik nehir vadisi: Eski şatolar, muazzam manzaralar.</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'berlin-nightlife',
        'title_tr'        => 'Berlin Gece Hayatı',
        'summary_tr'      => 'Berghain & Tresor: Dünyanın en iyi elektronik müzik club\'ları.',
        'content_tr'      => "<h3>Berlin Gece Hayatı</h3><p>Berghain & Tresor: Dünyanın en iyi elektronik müzik club'ları.</p>",
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'schwarzwald-yürüyüş',
        'title_tr'        => 'Schwarzwald Yürüyüşü',
        'summary_tr'      => 'Siyah Orman macerası: Doğa yürüyüşü cennetí.',
        'content_tr'      => '<h3>Schwarzwald Yürüyüşü</h3><p>Siyah Orman macerası: Doğa yürüyüşü cennetí.</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'munchen-english-garden',
        'title_tr'        => 'München English Garden',
        'summary_tr'      => 'Dünyanın en büyük şehir parkı: 92 km², sahte dalga!',
        'content_tr'      => '<h3>München English Garden</h3><p>Dünyanın en büyük şehir parkı: 92 km², sahte dalga!</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'koln-karneval',
        'title_tr'        => 'Köln Karnavalı',
        'summary_tr'      => 'Ruhun karnivali: Şubat, milyonlar maske takıp kutluyor.',
        'content_tr'      => '<h3>Köln Karnavalı</h3><p>Ruhun karnivali: Şubat, milyonlar maske takıp kutluyor.</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'deutsche-bahn-bahncard',
        'title_tr'        => 'Deutsche Bahn BahnCard',
        'summary_tr'      => 'Almanya\'yı tren ile keşfet: Student ücretleri daha ucuz.',
        'content_tr'      => "<h3>Deutsche Bahn BahnCard</h3><p>Almanya'yı tren ile keşfet: Student ücretleri daha ucuz.</p>",
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'berlin-street-art',
        'title_tr'        => 'Berlin Street Art Tour',
        'summary_tr'      => 'Graffiti & murallar: East Side Gallery, kültür + tarih.',
        'content_tr'      => '<h3>Berlin Street Art Tour</h3><p>Graffiti & murallar: East Side Gallery, kültür + tarih.</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'münchen-beer-hall',
        'title_tr'        => 'München Hofbräuhaus',
        'summary_tr'      => 'Bavyera bira kültürü: İkonik bira salonu, müzik ve dans.',
        'content_tr'      => '<h3>München Hofbräuhaus</h3><p>Bavyera bira kültürü: İkonik bira salonu, müzik ve dans.</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'hamburg-hafenstadt',
        'title_tr'        => 'Hamburg Hafenstadt',
        'summary_tr'      => 'Modern liman: HafenCity, Elbphilharmonie konser salonu.',
        'content_tr'      => '<h3>Hamburg Hafenstadt</h3><p>Modern liman: HafenCity, Elbphilharmonie konser salonu.</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'rammstein-concerts',
        'title_tr'        => 'Alman Müzik Festivali',
        'summary_tr'      => 'Rock am Ring, Fusion Festival: Almanya müzik sahnesinin merkezi.',
        'content_tr'      => '<h3>Alman Müzik Festivali</h3><p>Rock am Ring, Fusion Festival: Almanya müzik sahnesinin merkezi.</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'schwarzwald-triberg',
        'title_tr'        => 'Triberg Şelaleleri',
        'summary_tr'      => 'Almanya\'nın en yüksek şelaleleri: Siyah Ormanın ortasında.',
        'content_tr'      => "<h3>Triberg Şelaleleri</h3><p>Almanya'nın en yüksek şelaleleri: Siyah Ormanın ortasında.</p>",
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'hamburg-kunstmeile',
        'title_tr'        => 'Hamburg Kunstmeile',
        'summary_tr'      => 'Sanat sokağı: 5+ müze bir arada, Deichtorhallen.',
        'content_tr'      => '<h3>Hamburg Kunstmeile</h3><p>Sanat sokağı: 5+ müze bir arada, Deichtorhallen.</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'frankfurt-sachsenhausen',
        'title_tr'        => 'Frankfurt Sachsenhausen',
        'summary_tr'      => 'Geleneksel ciderhane: Apfelwein (elma şarabı) ve tapas.',
        'content_tr'      => '<h3>Frankfurt Sachsenhausen</h3><p>Geleneksel ciderhane: Apfelwein (elma şarabı) ve tapas.</p>',
        'type'            => 'blog',
        'category'        => 'culture-fun',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'mensa-guide',
        'title_tr'        => 'Mensa Rehberi',
        'summary_tr'      => 'Üniversite yemek halleri: €2-3, sağlıklı, her gün farklı menü.',
        'content_tr'      => '<h3>Mensa Rehberi</h3><p>Üniversite yemek halleri: €2-3, sağlıklı, her gün farklı menü.</p>',
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'wg-rules',
        'title_tr'        => 'WG Yaşam Rehberi',
        'summary_tr'      => 'Öğrenci evinde yaşam: Temizlik, gürültü, misafirler, mutfak.',
        'content_tr'      => '<h3>WG Yaşam Rehberi</h3><p>Öğrenci evinde yaşam: Temizlik, gürültü, misafirler, mutfak.</p>',
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'international-office',
        'title_tr'        => 'Int\'l Office Hizmetleri',
        'summary_tr'      => 'Üniversitenin sunduğu yardım: Tandem program, arkadaş bulma.',
        'content_tr'      => "<h3>Int'l Office Hizmetleri</h3><p>Üniversitenin sunduğu yardım: Tandem program, arkadaş bulma.</p>",
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'campus-events',
        'title_tr'        => 'Kampüs Etkinlikleri',
        'summary_tr'      => 'Semester başında büyük partiler: Networking + eğlence.',
        'content_tr'      => '<h3>Kampüs Etkinlikleri</h3><p>Semester başında büyük partiler: Networking + eğlence.</p>',
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'student-jobs',
        'title_tr'        => 'Student Job Bulma',
        'summary_tr'      => 'Haftada 20 saat çalışma: Üniversitede asistan olarak çalış.',
        'content_tr'      => '<h3>Student Job Bulma</h3><p>Haftada 20 saat çalışma: Üniversitede asistan olarak çalış.</p>',
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'asta-tutorings',
        'title_tr'        => 'AStA Tutorluk Servisi',
        'summary_tr'      => 'Derslerde yardım: AStA (öğrenci konseyi) danışmanlık.',
        'content_tr'      => '<h3>AStA Tutorluk Servisi</h3><p>Derslerde yardım: AStA (öğrenci konseyi) danışmanlık.</p>',
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'buddy-program',
        'title_tr'        => 'Buddy/Mentor Program',
        'summary_tr'      => 'Alman mentorla eşleşme: Kültür ve dil paylaşımı.',
        'content_tr'      => '<h3>Buddy/Mentor Program</h3><p>Alman mentorla eşleşme: Kültür ve dil paylaşımı.</p>',
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 4,
    ],
    [
        'slug'            => 'semester-ticket',
        'title_tr'        => 'Semester Ticket',
        'summary_tr'      => 'Tüm şehir ulaştırması dahil: Tren + otobüs, harç\'ta fiyatı.',
        'content_tr'      => "<h3>Semester Ticket</h3><p>Tüm şehir ulaştırması dahil: Tren + otobüs, harç'ta fiyatı.</p>",
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'elective-courses',
        'title_tr'        => 'Seçmeli Dersler',
        'summary_tr'      => 'Hoşlandığın alanları seç: Esnektir, kendi program oluştur.',
        'content_tr'      => '<h3>Seçmeli Dersler</h3><p>Hoşlandığın alanları seç: Esnektir, kendi program oluştur.</p>',
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'auslandssemester',
        'title_tr'        => 'Erasmus+ Semester',
        'summary_tr'      => 'Başka ülkede bir dönem: Bursa da verilir genelde.',
        'content_tr'      => '<h3>Erasmus+ Semester</h3><p>Başka ülkede bir dönem: Bursa da verilir genelde.</p>',
        'type'            => 'blog',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'goethe-universitesi-frankfurt',
        'title_tr'        => 'Goethe Üniversitesi Frankfurt — Rehber',
        'summary_tr'      => 'Frankfurt\'ta finans ve ekonomi odaklı üniversite.',
        'content_tr'      => '<h2>Goethe Üniversitesi Frankfurt</h2><p>Finans ve Ekonomi alanında uzmanlaşmış üniversite.</p><p>Başvuru, maliyetler ve kariyer hakkında daha fazla bilgi almak için resmi sitesini ziyaret edin.</p>',
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["frankfurt"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'tu-darmstadt-rehberi',
        'title_tr'        => 'TU Darmstadt — Bilgi ve Başvuru',
        'summary_tr'      => 'TU Darmstadt\'ye başvuru ve Mühendislik ve Bilim.',
        'content_tr'      => '<h2>TU Darmstadt</h2><p>Mühendislik ve Bilim alanında uzmanlaşmış üniversite.</p><p>Başvuru, maliyetler ve kariyer hakkında daha fazla bilgi almak için resmi sitesini ziyaret edin.</p>',
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["darmstadt"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'heidelberg-haand-rehberi',
        'title_tr'        => 'Heidelberg Uygulamalı Bilimler — Bilgi ve Başvuru',
        'summary_tr'      => 'Heidelberg Uygulamalı Bilimler\'ye başvuru ve Mühendislik HAW.',
        'content_tr'      => '<h2>Heidelberg Uygulamalı Bilimler</h2><p>Mühendislik HAW alanında uzmanlaşmış üniversite.</p><p>Başvuru, maliyetler ve kariyer hakkında daha fazla bilgi almak için resmi sitesini ziyaret edin.</p>',
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["heidelberg"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'hochschule-munchen-rehberi',
        'title_tr'        => 'Hochschule München (HAW) — Bilgi ve Başvuru',
        'summary_tr'      => 'Hochschule München (HAW)\'ye başvuru ve Uygulamalı Bilimler.',
        'content_tr'      => '<h2>Hochschule München (HAW)</h2><p>Uygulamalı Bilimler alanında uzmanlaşmış üniversite.</p><p>Başvuru, maliyetler ve kariyer hakkında daha fazla bilgi almak için resmi sitesini ziyaret edin.</p>',
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["münchen"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'haw-hamburg-rehberi',
        'title_tr'        => 'HAW Hamburg — Bilgi ve Başvuru',
        'summary_tr'      => 'HAW Hamburg\'ye başvuru ve Uygulamalı Bilimler.',
        'content_tr'      => '<h2>HAW Hamburg</h2><p>Uygulamalı Bilimler alanında uzmanlaşmış üniversite.</p><p>Başvuru, maliyetler ve kariyer hakkında daha fazla bilgi almak için resmi sitesini ziyaret edin.</p>',
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["hamburg"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'th-koeln-rehberi',
        'title_tr'        => 'TH Köln — Bilgi ve Başvuru',
        'summary_tr'      => 'TH Köln\'ye başvuru ve Uygulamalı Bilimler.',
        'content_tr'      => '<h2>TH Köln</h2><p>Uygulamalı Bilimler alanında uzmanlaşmış üniversite.</p><p>Başvuru, maliyetler ve kariyer hakkında daha fazla bilgi almak için resmi sitesini ziyaret edin.</p>',
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["köln"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 4,
    ],
    [
        'slug'            => 'dhbw-stuttgart-rehberi',
        'title_tr'        => 'DHBW Stuttgart — Bilgi ve Başvuru',
        'summary_tr'      => 'DHBW Stuttgart\'ye başvuru ve Dual Hochschule.',
        'content_tr'      => '<h2>DHBW Stuttgart</h2><p>Dual Hochschule alanında uzmanlaşmış üniversite.</p><p>Başvuru, maliyetler ve kariyer hakkında daha fazla bilgi almak için resmi sitesini ziyaret edin.</p>',
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["stuttgart"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'universitat-konstanz-rehberi',
        'title_tr'        => 'Universität Konstanz — Bilgi ve Başvuru',
        'summary_tr'      => 'Universität Konstanz\'ye başvuru ve Araştırma Odaklı.',
        'content_tr'      => '<h2>Universität Konstanz</h2><p>Araştırma Odaklı alanında uzmanlaşmış üniversite.</p><p>Başvuru, maliyetler ve kariyer hakkında daha fazla bilgi almak için resmi sitesini ziyaret edin.</p>',
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["konstanz"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'tu-bergakademie-rehberi',
        'title_tr'        => 'TU Bergakademie Freiberg — Bilgi ve Başvuru',
        'summary_tr'      => 'TU Bergakademie Freiberg\'ye başvuru ve Maden Mühendisliği.',
        'content_tr'      => '<h2>TU Bergakademie Freiberg</h2><p>Maden Mühendisliği alanında uzmanlaşmış üniversite.</p><p>Başvuru, maliyetler ve kariyer hakkında daha fazla bilgi almak için resmi sitesini ziyaret edin.</p>',
        'type'            => 'blog',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => ["freiberg"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'finans-bankacilk-rehberi',
        'title_tr'        => 'Finans ve Bankacılık',
        'summary_tr'      => '€5.000-8.000/ay, talep ÇOKGEREK',
        'content_tr'      => "<h2>Finans ve Bankacılık</h2><p>€5.000-8.000/ay, talep ÇOKGEREK</p><p>Almanya'da finans ve bankacılık sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'danismanlik-rehberi',
        'title_tr'        => 'Yönetim Danışmanlığı',
        'summary_tr'      => '€6.000-9.000/ay, talep GEREK',
        'content_tr'      => "<h2>Yönetim Danışmanlığı</h2><p>€6.000-9.000/ay, talep GEREK</p><p>Almanya'da yönetim danışmanlığı sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'pazarlama-rehberi',
        'title_tr'        => 'Pazarlama ve Satış',
        'summary_tr'      => '€3.500-6.000/ay, talep GEREK',
        'content_tr'      => "<h2>Pazarlama ve Satış</h2><p>€3.500-6.000/ay, talep GEREK</p><p>Almanya'da pazarlama ve satış sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'insan-kaynakları-rehberi',
        'title_tr'        => 'İnsan Kaynakları Yönetimi',
        'summary_tr'      => '€3.000-4.500/ay, talep ORTA',
        'content_tr'      => "<h2>İnsan Kaynakları Yönetimi</h2><p>€3.000-4.500/ay, talep ORTA</p><p>Almanya'da i̇nsan kaynakları yönetimi sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'projeyonetimi-rehberi',
        'title_tr'        => 'Proje Yönetimi',
        'summary_tr'      => '€4.500-7.000/ay, talep GEREK',
        'content_tr'      => "<h2>Proje Yönetimi</h2><p>€4.500-7.000/ay, talep GEREK</p><p>Almanya'da proje yönetimi sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'sağlık-hizmetleri-rehberi',
        'title_tr'        => 'Sağlık Hizmetleri',
        'summary_tr'      => '€2.800-4.500/ay, talep ÇOKGEREK',
        'content_tr'      => "<h2>Sağlık Hizmetleri</h2><p>€2.800-4.500/ay, talep ÇOKGEREK</p><p>Almanya'da sağlık hizmetleri sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'eğitim-rehberi',
        'title_tr'        => 'Eğitim ve Akademia',
        'summary_tr'      => '€2.500-4.000/ay, talep GEREK',
        'content_tr'      => "<h2>Eğitim ve Akademia</h2><p>€2.500-4.000/ay, talep GEREK</p><p>Almanya'da eğitim ve akademia sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'çevre-rehberi',
        'title_tr'        => 'Çevre ve Sürdürülebilirlik',
        'summary_tr'      => '€3.500-5.500/ay, talep GEREK',
        'content_tr'      => "<h2>Çevre ve Sürdürülebilirlik</h2><p>€3.500-5.500/ay, talep GEREK</p><p>Almanya'da çevre ve sürdürülebilirlik sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'enerji-rehberi',
        'title_tr'        => 'Enerji Sektörü',
        'summary_tr'      => '€4.000-6.500/ay, talep ÇOKGEREK',
        'content_tr'      => "<h2>Enerji Sektörü</h2><p>€4.000-6.500/ay, talep ÇOKGEREK</p><p>Almanya'da enerji sektörü sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'lojistik-rehberi',
        'title_tr'        => 'Lojistik ve Zincir Yönetimi',
        'summary_tr'      => '€3.800-5.500/ay, talep GEREK',
        'content_tr'      => "<h2>Lojistik ve Zincir Yönetimi</h2><p>€3.800-5.500/ay, talep GEREK</p><p>Almanya'da lojistik ve zincir yönetimi sektörü güçlü ve talep yüksek.</p>",
        'type'            => 'career_guide',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 4,
    ],
    [
        'slug'            => 'münchen-marienplatz-rehberi',
        'title_tr'        => 'München — Marienplatz',
        'summary_tr'      => 'Bavyera Merkezi',
        'content_tr'      => '<h2>München — Marienplatz</h2><p>Bavyera Merkezi: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["münchen"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'köln-rheinufer-rehberi',
        'title_tr'        => 'Köln — Rheinufer',
        'summary_tr'      => 'Ren Nehri Kıyısı',
        'content_tr'      => '<h2>Köln — Rheinufer</h2><p>Ren Nehri Kıyısı: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["köln"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'heidelberg-altstadt-rehberi',
        'title_tr'        => 'Heidelberg — Altstadt',
        'summary_tr'      => 'Eski Şehir Charm',
        'content_tr'      => '<h2>Heidelberg — Altstadt</h2><p>Eski Şehir Charm: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["heidelberg"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'bonn-rheinaue-rehberi',
        'title_tr'        => 'Bonn — Rheinaue',
        'summary_tr'      => 'Nehir Parkı',
        'content_tr'      => '<h2>Bonn — Rheinaue</h2><p>Nehir Parkı: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["bonn"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'aachen-charlemagne-rehberi',
        'title_tr'        => 'Aachen — Charlemagne',
        'summary_tr'      => 'Tarih ve Teknoloji',
        'content_tr'      => '<h2>Aachen — Charlemagne</h2><p>Tarih ve Teknoloji: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["aachen"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'braunschweig-schloss-rehberi',
        'title_tr'        => 'Braunschweig — Schloss',
        'summary_tr'      => 'Şato Bölgesi',
        'content_tr'      => '<h2>Braunschweig — Schloss</h2><p>Şato Bölgesi: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["braunschweig"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'hannover-maschsee-rehberi',
        'title_tr'        => 'Hannover — Maschsee',
        'summary_tr'      => 'Gölü Keşfet',
        'content_tr'      => '<h2>Hannover — Maschsee</h2><p>Gölü Keşfet: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["hannover"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'leipzip-markt-rehberi',
        'title_tr'        => 'Leipzip — Markt',
        'summary_tr'      => 'Sanat ve Kültür',
        'content_tr'      => '<h2>Leipzip — Markt</h2><p>Sanat ve Kültür: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["leipzip"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'dresden-frauenkirche-rehberi',
        'title_tr'        => 'Dresden — Frauenkirche',
        'summary_tr'      => 'Sanat ve Mimari',
        'content_tr'      => '<h2>Dresden — Frauenkirche</h2><p>Sanat ve Mimari: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["dresden"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'freiburg-münster-rehberi',
        'title_tr'        => 'Freiburg — Münster',
        'summary_tr'      => 'Yeşil Şehir',
        'content_tr'      => '<h2>Freiburg — Münster</h2><p>Yeşil Şehir: Keşfedilmesi gereken bir bölge.</p>',
        'type'            => 'blog',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ["freiburg"],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'ismail-hassan-deneyim',
        'title_tr'        => 'İsmail Hassan: Mısır\'den Bilgisayar Bilimleri Başarısı',
        'summary_tr'      => 'İsmail Hassan\'nin Bilgisayar Bilimleri yolculuğu.',
        'content_tr'      => '<blockquote>"Almanya bana akademik özgürlük ve kariyer fırsatı verdi."</blockquote><h3>Kısa Hikaye</h3><p>İsmail Hassan Mısır\'den gelerek Bilgisayar Bilimleri okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'fatima-ali-deneyim',
        'title_tr'        => 'Fatima Ali: Suriye\'den Mühendislik Başarısı',
        'summary_tr'      => 'Fatima Ali\'nin Mühendislik yolculuğu.',
        'content_tr'      => '<blockquote>"Başlangıçta zorluydu ama şimdi şirketim var."</blockquote><h3>Kısa Hikaye</h3><p>Fatima Ali Suriye\'den gelerek Mühendislik okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'david-silva-deneyim',
        'title_tr'        => 'David Silva: Portekiz\'den Ekonomi Başarısı',
        'summary_tr'      => 'David Silva\'nin Ekonomi yolculuğu.',
        'content_tr'      => '<blockquote>"Almanya\'da MBA yaptığımdan beri kariyerim değişti."</blockquote><h3>Kısa Hikaye</h3><p>David Silva Portekiz\'den gelerek Ekonomi okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'maria-santos-deneyim',
        'title_tr'        => 'Maria Santos: Brezilya\'den Yazılım Başarısı',
        'summary_tr'      => 'Maria Santos\'nin Yazılım yolculuğu.',
        'content_tr'      => '<blockquote>"Tech start-up\'ında çalışıyorum ve çok mutluyum."</blockquote><h3>Kısa Hikaye</h3><p>Maria Santos Brezilya\'den gelerek Yazılım okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'juan-garcia-deneyim',
        'title_tr'        => 'Juan García: İspanya\'den Mühendislik Başarısı',
        'summary_tr'      => 'Juan García\'nin Mühendislik yolculuğu.',
        'content_tr'      => '<blockquote>"Audi\'de mühendis olarak çalışmak hayal gibiydi."</blockquote><h3>Kısa Hikaye</h3><p>Juan García İspanya\'den gelerek Mühendislik okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'anna-müller-deneyim',
        'title_tr'        => 'Anna Müller: Polonya\'den Tıp Başarısı',
        'summary_tr'      => 'Anna Müller\'nin Tıp yolculuğu.',
        'content_tr'      => '<blockquote>"Charité\'de hekim adayı olarak çalışıyorum."</blockquote><h3>Kısa Hikaye</h3><p>Anna Müller Polonya\'den gelerek Tıp okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'ahmed-hassan-deneyim',
        'title_tr'        => 'Ahmed Hassan: Mısır\'den Fizik Başarısı',
        'summary_tr'      => 'Ahmed Hassan\'nin Fizik yolculuğu.',
        'content_tr'      => '<blockquote>"Max Planck\'te araştırmacı olarak çalışıyorum."</blockquote><h3>Kısa Hikaye</h3><p>Ahmed Hassan Mısır\'den gelerek Fizik okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'lucia-fontana-deneyim',
        'title_tr'        => 'Lucia Fontana: İtalya\'den Tasarım Başarısı',
        'summary_tr'      => 'Lucia Fontana\'nin Tasarım yolculuğu.',
        'content_tr'      => '<blockquote>"Berlin\'de grafik tasarım ajansında çalışıyorum."</blockquote><h3>Kısa Hikaye</h3><p>Lucia Fontana İtalya\'den gelerek Tasarım okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'carlo-rossi-deneyim',
        'title_tr'        => 'Carlo Rossi: İtalya\'den Mimarlık Başarısı',
        'summary_tr'      => 'Carlo Rossi\'nin Mimarlık yolculuğu.',
        'content_tr'      => '<blockquote>"Almanya\'da mimari projelerimde başarılı oldum."</blockquote><h3>Kısa Hikaye</h3><p>Carlo Rossi İtalya\'den gelerek Mimarlık okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 4,
    ],
    [
        'slug'            => 'sophie-dupont-deneyim',
        'title_tr'        => 'Sophie Dupont: Fransa\'den Biyoloji Başarısı',
        'summary_tr'      => 'Sophie Dupont\'nin Biyoloji yolculuğu.',
        'content_tr'      => '<blockquote>"Tübingen\'de doctoral araştırmacısı oldum."</blockquote><h3>Kısa Hikaye</h3><p>Sophie Dupont Fransa\'den gelerek Biyoloji okudu ve başarılı oldu.</p>',
        'type'            => 'experience',
        'category'        => 'success-stories',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 3,
    ],
    [
        'slug'            => 'krankenkasse-vergleich',
        'title_tr'        => '💡 Sağlık Sigorta Karşılaştırması',
        'summary_tr'      => 'HanseMerkur, TK, AOK karşılaştır. En ucuzu seç!',
        'content_tr'      => '<p>HanseMerkur, TK, AOK karşılaştır. En ucuzu seç!</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'ban-konto-iban',
        'title_tr'        => '💡 Banka Hesabı Açma',
        'summary_tr'      => 'Commerzbank, Deutsche Bank, N26 (dijital) seçenekleri var.',
        'content_tr'      => '<p>Commerzbank, Deutsche Bank, N26 (dijital) seçenekleri var.</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'rundfunk-beitrag',
        'title_tr'        => '💡 Rundfunk Beitragi (ÖRT)',
        'summary_tr'      => 'Tüm öğrenciler ödemeli. Aylık €18. Muhtar\'ıncı ara.',
        'content_tr'      => "<p>Tüm öğrenciler ödemeli. Aylık €18. Muhtar'ıncı ara.</p>",
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'elekrik-gaz',
        'title_tr'        => '💡 Elektrik ve Gaz Şirketi',
        'summary_tr'      => 'Vattenfall, E.ON, Stadtwerke\'den kontrol et. Fiyat önemli!',
        'content_tr'      => "<p>Vattenfall, E.ON, Stadtwerke'den kontrol et. Fiyat önemli!</p>",
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'hazır-ulaştırma',
        'title_tr'        => '💡 Öğrenci Ulaştırma',
        'summary_tr'      => 'BahnCard Student, Semesterticket, iş pazarında kullan.',
        'content_tr'      => '<p>BahnCard Student, Semesterticket, iş pazarında kullan.</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'üniversite-bursası',
        'title_tr'        => '💡 BAföG Yurtdışı',
        'summary_tr'      => 'Lisans döneminin en az birinde yurtdışında oku.',
        'content_tr'      => '<p>Lisans döneminin en az birinde yurtdışında oku.</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 7,
    ],
    [
        'slug'            => 'turist-vizesi',
        'title_tr'        => '💡 Turist Vizesi Uzatması',
        'summary_tr'      => 'Öğrenci vizesine geçiş zor. Öncesinde araştır.',
        'content_tr'      => '<p>Öğrenci vizesine geçiş zor. Öncesinde araştır.</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 5,
    ],
    [
        'slug'            => 'pasaport-yenileme',
        'title_tr'        => '💡 Pasaport Yenileme',
        'summary_tr'      => 'Vali\'de randevu al. Aile danışmanlığı\'na giderek kolaylaştır.',
        'content_tr'      => "<p>Vali'de randevu al. Aile danışmanlığı'na giderek kolaylaştır.</p>",
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'dil-kursu',
        'title_tr'        => '💡 Üniversite Dil Kursları',
        'summary_tr'      => 'DAAD\'ın C1 kursu €0. Ücretsiz! Hemen kaydol.',
        'content_tr'      => "<p>DAAD'ın C1 kursu €0. Ücretsiz! Hemen kaydol.</p>",
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 11,
    ],
    [
        'slug'            => 'mentorlik-program',
        'title_tr'        => '💡 Mentorlik Programı',
        'summary_tr'      => 'Alman mentoru bul: Tandem, Buddy program kullan.',
        'content_tr'      => '<p>Alman mentoru bul: Tandem, Buddy program kullan.</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'kütüphane-kart',
        'title_tr'        => '💡 Kütüphane Kartı',
        'summary_tr'      => 'Tüm üniversite kütüphanelerine ücretsiz giriş. Kitaplar!',
        'content_tr'      => '<p>Tüm üniversite kütüphanelerine ücretsiz giriş. Kitaplar!</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'spor-merkezi',
        'title_tr'        => '💡 Üniversite Spor Merkezi',
        'summary_tr'      => 'Fitness, yoga, futbol: Harç\'ta fiyatlandırılmış! Ücretsiz',
        'content_tr'      => "<p>Fitness, yoga, futbol: Harç'ta fiyatlandırılmış! Ücretsiz</p>",
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'psikolojik-danismanlik',
        'title_tr'        => '💡 Ruh Sağlığı Danışmanı',
        'summary_tr'      => 'Universität Beratung: Ücretsiz danışman. Sesiz kal!',
        'content_tr'      => '<p>Universität Beratung: Ücretsiz danışman. Sesiz kal!</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 6,
    ],
    [
        'slug'            => 'is-arayan-kulup',
        'title_tr'        => '💡 İş Arayan Kulübü',
        'summary_tr'      => 'Career Services: CV, mülakat, networking etkinlikleri.',
        'content_tr'      => '<p>Career Services: CV, mülakat, networking etkinlikleri.</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'yazilim-indirim',
        'title_tr'        => '💡 Yazılım İndirimleri',
        'summary_tr'      => 'GitHub, JetBrains, Adobe: Student paketi almak ücretsiz!',
        'content_tr'      => '<p>GitHub, JetBrains, Adobe: Student paketi almak ücretsiz!</p>',
        'type'            => 'tip',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => null,
        'read_time_minutes' => 2,
    ],

    // ── Video & Podcast İçerikleri ──────────────────────────────────────────

    [
        'slug'            => 'frankfurt-sehir-turu-video',
        'title_tr'        => 'Frankfurt Şehir Turu — Video Rehber',
        'summary_tr'      => 'Frankfurt\'un ikonik mekanları, Sachsenhausen, Römer ve Pazar Meydanı\'nı video ile keşfedin.',
        'content_tr'      => '<h2>Frankfurt Video Turu</h2><p>Almanya\'nın finans başkenti Frankfurt\'u bu video rehberle adım adım keşfedin. Römer, Sachsenhausen, Main nehir kıyısı ve öğrenci semtlerini bir arada görün.</p><h3>Videoda Neler Var?</h3><ul><li>Römerberg tarihi merkez</li><li>Sachsenhausen elma şarabı semti</li><li>Frankfurt Bankenviertel (Finans Bölgesi)</li><li>Main nehir gezisi</li></ul>',
        'type'            => 'video_feature',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ['frankfurt'],
        'is_featured'     => false,
        'video_url'       => 'https://www.youtube.com/embed/LzLOhMsjpsw',
        'read_time_minutes' => 8,
    ],
    [
        'slug'            => 'berlin-ogrenci-yasam-video',
        'title_tr'        => 'Berlin\'de Öğrenci Hayatı — Mini Belgesel',
        'summary_tr'      => 'Berlin\'in öğrenci semtleri, kafeler, müzeler ve ulaşım ipuçları.',
        'content_tr'      => '<h2>Berlin Öğrenci Hayatı</h2><p>Berlin, Almanya\'nın en dinamik ve çok kültürlü şehri. Öğrenciler için sunduğu imkânlar eşsiz.</p><h3>Öne Çıkan Semtler</h3><ul><li><strong>Mitte:</strong> Tarihi merkez, müzeler</li><li><strong>Prenzlauer Berg:</strong> Kafeler, pazar yerleri</li><li><strong>Friedrichshain:</strong> Gece hayatı, East Side Gallery</li><li><strong>Neukölln:</strong> Çok kültürlü, uygun fiyatlı</li></ul>',
        'type'            => 'video_feature',
        'category'        => 'city-content',
        'target_audience' => 'all',
        'tags'            => ['berlin'],
        'is_featured'     => false,
        'video_url'       => 'https://www.youtube.com/embed/LzLOhMsjpsw',
        'read_time_minutes' => 10,
    ],
    [
        'slug'            => 'almanya-universite-secimi-video',
        'title_tr'        => 'Almanya\'da Üniversite Seçimi — Adım Adım',
        'summary_tr'      => 'TU München mi? Humboldt mu? FH mi? Bu video ile doğru üniversiteyi seçin.',
        'content_tr'      => '<h2>Doğru Üniversiteyi Nasıl Seçersiniz?</h2><p>Almanya\'da 400+ üniversite var. Araştırma odaklı Universität mı, uygulama odaklı Fachhochschule mı olduğuna karar vermek kritik ilk adım.</p><h3>Üniversite Türleri</h3><ul><li><strong>Universität:</strong> Araştırma, master/doktora imkânı</li><li><strong>Fachhochschule (FH):</strong> Pratik odaklı, sektöre yakın</li><li><strong>Technische Universität (TU):</strong> Mühendislik ağırlıklı</li></ul>',
        'type'            => 'video_feature',
        'category'        => 'uni-content',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => 'https://www.youtube.com/embed/LzLOhMsjpsw',
        'read_time_minutes' => 12,
    ],
    [
        'slug'            => 'almanya-kariyer-firsatlari-video',
        'title_tr'        => 'Almanya\'da Kariyer Fırsatları — Sektör Rehberi',
        'summary_tr'      => 'Mühendislik, yazılım, finans: Almanya\'nın hangi şehri hangi sektörde öne çıkıyor?',
        'content_tr'      => '<h2>Almanya\'da Kariyer</h2><p>Almanya, Avrupa\'nın en büyük ekonomisi. Uluslararası mezunlar için çok sayıda kariyer imkânı sunuyor.</p><h3>Sektör Haritası</h3><ul><li><strong>Yazılım/Tech:</strong> Berlin, München</li><li><strong>Otomotiv:</strong> München, Stuttgart, Wolfsburg</li><li><strong>Finans:</strong> Frankfurt</li><li><strong>Kimya/Pharma:</strong> Frankfurt, Düsseldorf</li><li><strong>Lojistik:</strong> Hamburg</li></ul>',
        'type'            => 'video_feature',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => 'https://www.youtube.com/embed/LzLOhMsjpsw',
        'read_time_minutes' => 9,
    ],
    [
        'slug'            => 'almanya-podcast-ogrenci-deneyim',
        'title_tr'        => 'Podcast: Almanya\'da 3. Yılım — Selin ile Söyleşi',
        'summary_tr'      => 'İzmir\'den München\'e: Selin, TUM\'da bilgisayar mühendisliği okurken neler yaşadığını anlatıyor.',
        'content_tr'      => '<h2>Bölüm Özeti</h2><p>Bu bölümde İzmir\'den München\'e uzanan bir öğrenci hikayesini dinliyoruz. Selin, TU München\'de bilgisayar mühendisliğinin 3. yılında.</p><h3>Konuşulan Konular</h3><ul><li>Almanya\'ya uyum süreci</li><li>TU München\'in avantajları ve zorlukları</li><li>WG (paylaşık ev) deneyimi</li><li>Part-time iş ve burs imkânları</li><li>Kariyer planlaması: staj ve tam zamanlı iş</li></ul>',
        'type'            => 'podcast',
        'category'        => 'student-life',
        'target_audience' => 'all',
        'tags'            => ['münchen'],
        'is_featured'     => false,
        'video_url'       => 'https://www.youtube.com/embed/LzLOhMsjpsw',
        'read_time_minutes' => 35,
    ],
    [
        'slug'            => 'almanya-podcast-kariyer-tavsiyeler',
        'title_tr'        => 'Podcast: Almanya\'da İş Bulmanın Sırları',
        'summary_tr'      => 'LinkedIn, Xing, Jobmesse: Almanya\'da iş başvurusu nasıl yapılır?',
        'content_tr'      => '<h2>Bölüm Özeti</h2><p>Almanya iş piyasasına nasıl girilir? İşte kariyer danışmanımızın pratik tavsiyeleri.</p><h3>Ana Başlıklar</h3><ul><li>Lebenslauf (Alman CV) nasıl hazırlanır?</li><li>Anschreiben (motivasyon mektubu) tüyoları</li><li>LinkedIn vs Xing hangisi daha etkili?</li><li>Jobmesse (kariyer fuarı) stratejisi</li><li>18 aylık Job-Seeker Visa nasıl kullanılır?</li></ul>',
        'type'            => 'podcast',
        'category'        => 'careers',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => 'https://www.youtube.com/embed/LzLOhMsjpsw',
        'read_time_minutes' => 28,
    ],
    [
        'slug'            => 'almanya-vize-basvuru-sunum',
        'title_tr'        => 'Almanya Öğrenci Vizesi — Adım Adım Sunum',
        'summary_tr'      => 'Ulusal vize başvurusu, gerekli belgeler ve sıkça sorulan sorular.',
        'content_tr'      => '<h2>Vize Başvuru Süreci</h2><p>Bu sunumda Almanya öğrenci vizesi (§16b AufenthG) başvurusu için gerekli tüm adımları bulacaksınız.</p><h3>İçerik</h3><ul><li>Gerekli belgeler listesi</li><li>Sperrkonto açma ve kanıtlama</li><li>Sağlık sigortası</li><li>Randevu alma stratejisi</li><li>Vize görüşmesinde dikkat edilecekler</li></ul>',
        'type'            => 'presentation',
        'category'        => 'tips-tricks',
        'target_audience' => 'all',
        'tags'            => [],
        'is_featured'     => false,
        'video_url'       => 'https://www.youtube.com/embed/LzLOhMsjpsw',
        'read_time_minutes' => 15,
    ],
        ];

        $adminId = \App\Models\User::first()?->id ?? 1;

        foreach ($contents as $data) {
            $readMins = $data['read_time_minutes'] ?? 5;
            unset($data['read_time_minutes']);
            if (!isset($data['status'])) $data['status'] = 'published';
            if (!isset($data['published_at'])) $data['published_at'] = now()->subDays(rand(1, 60));
            \App\Models\Marketing\CmsContent::updateOrCreate(
                ['slug' => $data['slug']],
                array_merge($data, [
                    'created_by'                   => $adminId,
                    'metric_total_views'           => rand(30, 1800),
                    'metric_avg_read_time_seconds' => $readMins * 60,
                ])
            );
        }

        $this->command->info('ContentHubSeeder: içerikler eklendi/güncellendi.');
    }
}
