<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Marketing\CmsContent;
use Illuminate\Support\Carbon;

/**
 * Ek içerikler: success-stories (tüm tipler), uni-content, city-content eksikleri,
 * careers/student-life/tips-tricks doldurma.
 */
class ContentHubExtraSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();
        $adminId = \App\Models\User::first()?->id ?? 1;

        $items = [

            /* ── SUCCESS STORIES ── */
            [
                'slug'        => 'almanya-mezun-hikayesi-mert',
                'title_tr'    => 'TUM Mezunu Mert: "Almanya Beni Dönüştürdü"',
                'summary_tr'  => 'İstanbul\'dan München\'e, öğrencilikten BMW mühendisliğine: 5 yılın özeti.',
                'content_tr'  => '<h2>Başlangıç: Korku ve Heyecan</h2><p>2019\'da Türkiye\'den Almanya\'ya geldiğimde elimde bir karyola ve bir valiz vardı. TU München\'de Makine Mühendisliği okuyacaktım. İlk hafta kafam tamamen karışıktı — ne Almanca bürokratik işlemler ne de paylaşık ev arkadaşlarım. Ama bir şey vardı: azim.</p><h2>Akademik Zorluklar</h2><p>İlk sömestr neredeyse battım. Thermodynamik dersinden C- aldım. Ama danışman hocam bana şunu söyledi: "Almanya\'da mükemmellik geceden gelmez." O cümle hayatımı değiştirdi.</p><h2>Dönüm Noktası: BMW Stajı</h2><p>3. yılda BMW Motorsport\'ta staj yaptım. 6 ayda teorik bilgimi gerçek mühendisliğe dönüştürdüm. Stajın son haftasında tam zamanlı teklif aldım.</p><h2>Bugün</h2><p>Şu an BMW R&D\'de çalışıyorum, elektrikli araç sistemleri üzerine. Almanya bana sadece bir kariyer değil, bir yaşam biçimi verdi.</p>',
                'type'        => 'experience',
                'category'    => 'success-stories',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['munich', 'tum', 'başarı', 'mühendislik'],
                'is_featured' => true,
                'featured_order' => 4,
                'read_time'   => 7,
                'published_at'=> $now->copy()->subDays(2),
            ],
            [
                'slug'        => 'berlin-hukuk-mezunu-selin',
                'title_tr'    => '"Humboldt\'ta Hukuk": Selin\'in Başarı Hikayesi',
                'summary_tr'  => 'Türk hukuk fakültesi mezununun Almanya\'da master yapma ve avukatlık stajı alma hikayesi.',
                'content_tr'  => '<h2>Hukuk = Almancaya Teslim Olmak</h2><p>Hukuk, belki de Almanya\'da en zorlu alanlardan biri. Çünkü her şey dil üzerine kurulu — hukuki terminoloji, mahkeme dili, akademik yazı. C1 Almancam olmasına rağmen ilk sömestr dökümanları okurken bazen saatler geçirebiliyordum.</p><h2>Humboldt Üniversitesi</h2><p>Berlin Humboldt\'ta LLM (Hukuk Yüksek Lisans) programına kabul aldım. Program %60 uluslararası öğrencilerden oluşuyor — bu da adaptasyonu kolaylaştırdı.</p><h2>Sonuç</h2><p>Şu an Berlin\'de bir hukuk firmasında avukatlık stajı yapıyorum. Almanya\'da yabancı hukuk mezunlarının lokal baroya kaydolması mümkün — hedefim 2 yıl içinde tam lisans almak.</p>',
                'type'        => 'blog',
                'category'    => 'success-stories',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['berlin', 'hukuk', 'başarı', 'master'],
                'read_time'   => 6,
                'published_at'=> $now->copy()->subDays(4),
            ],
            [
                'slug'        => 'hamburg-mimarlik-basari',
                'title_tr'    => 'HafenCity\'de Mimarlık: Zeynep\'in Yolculuğu',
                'summary_tr'  => 'İzmir\'den Hamburg\'a, mimarlık öğrencisinden uluslararası ofis çalışanına.',
                'content_tr'  => '<p>Hamburg HafenCity Üniversitesi\'nde Mimarlık okudum. Portfolio hazırlama, stüdyo geceleri ve son olarak Zaha Hadid Architects\'e başvuru — bu hikaye hem başarının hem de direnişin hikayesi.</p><h3>Portfolio\'nun Önemi</h3><p>Almanya\'daki mimarlık programları portfolio bazlı kabul yapıyor. 3 ay boyunca 40 sayfalık portfolyomu hazırladım. Red aldığımda yıkıldım. Ama tekrar revize ederek 2. başvuruda kabul aldım.</p><h3>Mezuniyet Sonrası</h3><p>Şu an Hamburg merkezli bir sürdürülebilir mimarlık ofisinde çalışıyorum. Projelerimiz Avrupa genelinde yayılıyor.</p>',
                'type'        => 'experience',
                'category'    => 'success-stories',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['hamburg', 'mimarlık', 'başarı'],
                'read_time'   => 5,
                'published_at'=> $now->copy()->subDays(6),
            ],
            [
                'slug'        => 'basari-podcast-can-siemens',
                'title_tr'    => 'Podcast: Can\'ın Siemens Kariyeri — Sıfırdan Yöneticiliğe',
                'summary_tr'  => 'Erlangen\'de Siemens\'te 8 yılda junior mühendisten ürün yöneticisine yükselen Can ile konuştuk.',
                'content_tr'  => '<p><strong>Bu bölümde:</strong></p><ul><li>Türkiye\'den Almanya\'ya geçişin zorlukları</li><li>Siemens\'te kariyer basamakları</li><li>Almancayı iş dilinde nasıl geliştirdi?</li><li>Yeni gelenlere öneriler</li></ul>',
                'type'        => 'podcast',
                'category'    => 'success-stories',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['siemens', 'kariyer', 'başarı', 'podcast'],
                'video_url'   => 'https://open.spotify.com/embed/episode/placeholder2',
                'read_time'   => 40,
                'published_at'=> $now->copy()->subDays(9),
            ],
            [
                'slug'        => 'basari-video-tıp-munih',
                'title_tr'    => 'Video: LMU München\'de Tıp — 6 Yılın Özeti',
                'summary_tr'  => 'LMU München Tıp Fakültesi\'nde 6 yıl okuyan Ayşe\'nin vlog serisi.',
                'content_tr'  => '<p>Bu videoda LMU München Tıp Fakültesi mezunu Dr. Ayşe Kara ile röportaj yapıyoruz. Almanya\'da tıp okumak isteyenler için değerli bilgiler içeriyor.</p><p><strong>Konular:</strong></p><ul><li>Numerus Clausus (NC) — not ortalaması gereksinimleri</li><li>Klinik rotasyonlar (Famulaturen)</li><li>Almanca tıp terminolojisi</li><li>Uzmanlık eğitimi (Facharztausbildung)</li></ul>',
                'type'        => 'video_feature',
                'category'    => 'success-stories',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['munich', 'tıp', 'başarı', 'lmu'],
                'video_url'   => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'read_time'   => 25,
                'published_at'=> $now->copy()->subDays(11),
            ],
            [
                'slug'        => 'basari-sunum-kariyer-yolu',
                'title_tr'    => 'Sunum: Almanya\'da Kariyer Yolculuğu — 5 Başarı Vakası',
                'summary_tr'  => 'Farklı sektörlerde başarılı olan 5 Türk mezununun kariyer rotalarını gösteren sunum.',
                'content_tr'  => '<p>Bu sunumda mühendislik, finans, hukuk, mimarlık ve tıp alanlarında Almanya\'da başarılı olan 5 mezunun kariyer haritasını görsel olarak inceliyoruz.</p>',
                'type'        => 'presentation',
                'category'    => 'success-stories',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['kariyer', 'başarı', 'sunum'],
                'video_url'   => 'https://docs.google.com/presentation/d/e/2PACX-placeholder2/embed',
                'read_time'   => 10,
                'published_at'=> $now->copy()->subDays(14),
            ],
            [
                'slug'        => 'basari-ipucu-motivasyon',
                'title_tr'    => '5 Mezundan Aynı Tavsiye: "Bunu Yapmasaydım Olmazdım"',
                'summary_tr'  => 'Almanya\'da başarılı olan mezunların ortak paydasında ne var?',
                'content_tr'  => '<p>Onlarca başarı hikayesini inceledik. Tekrar eden 5 ortak unsur bulduk:</p><ol><li><strong>Almancaya erken başlamak</strong> — gelmeden en az 1 yıl önce</li><li><strong>Staja ciddi bakmak</strong> — iş kapısı oradan açılıyor</li><li><strong>Ağ kurmak</strong> — hemşeriler kadar Alman kollegler de önemli</li><li><strong>Sabır</strong> — ilk yıl zor, ikinci yıl daha kolay, üçüncü yıl normal</li><li><strong>Geri dönmek için gitmemek</strong> — karar verip gitmek</li></ol>',
                'type'        => 'tip',
                'category'    => 'success-stories',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['başarı', 'tavsiye', 'motivasyon'],
                'read_time'   => 3,
                'published_at'=> $now->copy()->subDays(1),
            ],
            [
                'slug'        => 'basari-kariyer-rehberi-genel',
                'title_tr'    => 'Almanya\'da Başarıya Giden Yol: 10 Mezundan Kariyer Rehberi',
                'summary_tr'  => 'Almanya\'daki Türk mezunların kariyer yolculuklarından derlenen kapsamlı rehber.',
                'content_tr'  => '<h2>10 Mezun, 10 Farklı Yol</h2><p>Almanya\'da başarılı olmak için tek bir formül yok. Ama belirli kalıplar tekrar ediyor.</p><h3>Ortak Özellikler</h3><ul><li>C1+ Almanca düzeyi</li><li>En az 1 Almanya\'daki staj deneyimi</li><li>Lokal ağ (Netzwerk)</li><li>Uzun vadeli planlama</li></ul><h3>Sektörel Farklılıklar</h3><p>Teknoloji ve mühendislik — en hızlı yol. Hukuk ve tıp — en uzun ama en stabil yol. Finans — NetworkX bağlantısı şart.</p>',
                'type'        => 'career_guide',
                'category'    => 'success-stories',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['kariyer', 'başarı', 'rehber'],
                'read_time'   => 9,
                'published_at'=> $now->copy()->subDays(15),
            ],

            /* ── UNI-CONTENT ── */
            [
                'slug'        => 'almanya-universite-secimi-rehber',
                'title_tr'    => 'Almanya\'da Hangi Üniversite? TU vs FH vs Privat',
                'summary_tr'  => 'Devlet üniversitesi mi, uygulamalı bilimler mi, özel üniversite mi? Karar vermenize yardımcı rehber.',
                'content_tr'  => '<h2>Almanya\'da Üniversite Sistemi</h2><p>Almanya\'da 3 ana üniversite türü var:</p><h3>1. Universität (Araştırma Üniversiteleri)</h3><p>TU München, Humboldt Berlin, Heidelberg gibi kurumlar. Teorik odaklı, akademik kariyer için ideal.</p><h3>2. Fachhochschule / HAW (Uygulamalı Bilimler)</h3><p>Pratik odaklı, iş dünyasına hızlı giriş. Staj zorunlu.</p><h3>3. Private Hochschule (Özel Üniversite)</h3><p>EBS, WHU gibi kurumlar. Ücretli ama kariyer servisleri güçlü.</p><h3>Nasıl Karar Verilir?</h3><p>Akademik kariyer hedefliyorsanız → Universität. Hızlı iş bağlantısı istiyorsanız → FH. Yönetim/MBA ağırlıklı → Private.</p>',
                'type'        => 'blog',
                'category'    => 'uni-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['üniversite', 'seçim', 'rehber'],
                'read_time'   => 8,
                'published_at'=> $now->copy()->subDays(5),
            ],
            [
                'slug'        => 'uni-assist-rehberi',
                'title_tr'    => 'uni-assist Başvurusu: Adım Adım Tam Rehber',
                'summary_tr'  => 'Türkiye mezunlarının Almanya üniversitelerine başvuruda kullandığı uni-assist portali nasıl kullanılır?',
                'content_tr'  => '<h2>uni-assist Nedir?</h2><p>uni-assist, Alman üniversitelerinin yabancı öğrenci başvurularını merkezi olarak değerlendirmek için kullandığı bir platform. ~75 EUR ücret var.</p><h3>Adımlar</h3><ol><li>uni-assist.de\'de hesap aç</li><li>Başvurmak istediğin üniversiteleri seç</li><li>Belgeleri yükle: transkript, diploma, Almanca sertifikası, motivasyon mektubu</li><li>APS sertifikasını (Türkiye mezunları için) ekle</li><li>Ödeme yap</li><li>Sonuç: 4-8 hafta</li></ol><h3>Dikkat Edilecekler</h3><ul><li>Her üniversite için ek özel başvuru gerekebilir</li><li>Son başvuru tarihleri: kış dönemi 15 Temmuz, yaz dönemi 15 Ocak</li></ul>',
                'type'        => 'blog',
                'category'    => 'uni-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['uni-assist', 'başvuru', 'üniversite'],
                'read_time'   => 7,
                'published_at'=> $now->copy()->subDays(8),
            ],
            [
                'slug'        => 'universite-basvuru-sunum',
                'title_tr'    => 'Sunum: Almanya Üniversite Başvuru Süreci — Takvim ve Belgeler',
                'summary_tr'  => 'Başvuru takvimi, gerekli belgeler ve uni-assist, hochschulstart süreçlerini adım adım gösteren sunum.',
                'content_tr'  => '<p>Bu sunumda Almanya üniversitelerine başvuru sürecinin tüm adımları görsel olarak anlatılmaktadır.</p><p><strong>İçerik:</strong></p><ul><li>Başvuru takvimi (12 aylık)</li><li>Gerekli belgeler listesi</li><li>uni-assist vs direkt başvuru</li><li>Motivasyon mektubu yazımı</li><li>Kabul sonrası adımlar</li></ul>',
                'type'        => 'presentation',
                'category'    => 'uni-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['başvuru', 'üniversite', 'sunum'],
                'video_url'   => 'https://docs.google.com/presentation/d/e/2PACX-placeholder-uni/embed',
                'read_time'   => 15,
                'published_at'=> $now->copy()->subDays(12),
            ],
            [
                'slug'        => 'tu-munih-tum-deneyimi',
                'title_tr'    => '"TUM\'da İlk Yıl": Şaşkınlık, Adaptasyon ve Büyüme',
                'summary_tr'  => 'Dünyanın en iyi mühendislik fakültelerinden TU München\'de ilk yılın gerçek hikayesi.',
                'content_tr'  => 'TUM\'a kabul aldığımda tüm arkadaşlarım kutladı. Ama ilk sınava girdiğimde neden bu kadar zor olduğunu anladım.\n\nAlmanya\'da sınav sistemi Türkiye\'den farklı: çoktan seçmeli yok, her şey açık uçlu. Düşünce sürecini yazıyorsunuz. Bu alışkın olmadığım bir şeydi.\n\nİlk sömestr sonunda GPA\'im hayal ettiğimden düşüktü. Ama 2. sömestrede sistemi öğrendim: Altklausuren (eski sınavlar) çöz, Tutorien\'e katıl, öğrenci gruplarıyla çalış.\n\nTUM\'un en güçlü yanı: araştırma projeleri. Ben 2. yılda bir Lehrstuhl\'da (araştırma grubu) student assistant olarak çalıştım. Bu deneyim hem para hem CV hem de network sağladı.',
                'type'        => 'experience',
                'category'    => 'uni-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['tum', 'munich', 'deneyim', 'üniversite'],
                'read_time'   => 6,
                'published_at'=> $now->copy()->subDays(16),
            ],
            [
                'slug'        => 'almanya-burslar-daad',
                'title_tr'    => 'DAAD ve Diğer Burslar: Almanya\'da Para Kazanarak Okumak',
                'summary_tr'  => 'Almanya\'da üniversite eğitimini destekleyecek burs programları: DAAD, Deutschlandstipendium, özel vakıflar.',
                'content_tr'  => '<h2>Almanya\'da Burs İmkânları</h2><h3>DAAD (Alman Akademik Değişim Servisi)</h3><p>En büyük burs programı. Yıllık 100,000+ öğrenciyi destekliyor. Başvuru: daad.de</p><h3>Deutschlandstipendium</h3><p>Üniversite bazlı burs, aylık €300. Akademik başarı + sosyal bağlılık kriteri. Çoğu üniversite kendi başvuru portalına sahip.</p><h3>Vakıf Bursları</h3><ul><li>Friedrich-Ebert-Stiftung (sosyal demokrat)</li><li>Konrad-Adenauer-Stiftung (Hristiyan demokrat)</li><li>Heinrich-Böll-Stiftung (yeşil)</li><li>Hanns-Seidel-Stiftung (CSU bağlantılı)</li></ul>',
                'type'        => 'career_guide',
                'category'    => 'uni-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['burs', 'daad', 'üniversite', 'para'],
                'read_time'   => 8,
                'published_at'=> $now->copy()->subDays(20),
            ],
            [
                'slug'        => 'universitede-almanca-ipucu',
                'title_tr'    => 'Üniversitede Almanca: Akademik Dil İpuçları',
                'summary_tr'  => 'Günlük Almanca ile akademik Almanca farklı. Derslerde başarılı olmak için bilmeniz gerekenler.',
                'content_tr'  => '<p>B2 Almancayla Almanya\'ya gelen öğrenciler şok yaşıyor: <em>günlük Almanca</em> ile <em>akademik Almanca</em> neredeyse iki ayrı dil.</p><h3>Fark Ne?</h3><ul><li>Konjunktiv (dilek kipi) — akademik yazıda zorunlu</li><li>Passivkonstruktionen — pasif cümleler çok kullanılır</li><li>Fachvokabular — her alanın kendi teknik sözlüğü var</li></ul><h3>Ne Yapmalı?</h3><ul><li>Ders notlarını Almanca tut</li><li>Seminerlerde konuş — sessiz kalmak dili geliştirmiyor</li><li>Sprechstunde\'a git — hoca ile birebir pratik</li></ul>',
                'type'        => 'tip',
                'category'    => 'uni-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['almanca', 'akademik', 'üniversite'],
                'read_time'   => 4,
                'published_at'=> $now->copy()->subDays(7),
            ],

            /* ── CITY-CONTENT ── */
            [
                'slug'        => 'frankfurt-sehir-rehberi-ogrenci',
                'title_tr'    => 'Frankfurt\'ta Öğrenci Olmak: Finans Şehrinde Yaşam',
                'summary_tr'  => 'Goethe Üniversitesi ve Frankfurt kampüs çevresinde öğrenci hayatı — pahalı mı, yoksa yönetilebilir mi?',
                'content_tr'  => '<h2>Frankfurt = Sadece Banka Değil</h2><p>Frankfurt denince akla hep iş dünyası gelir. Ama şehrin bir de öğrenci yüzü var. Goethe Üniversitesi\'nin 46,000 öğrencisiyle şehir aslında oldukça canlı bir kampüs ortamına sahip.</p><h3>Kira Durumu</h3><p>Frankfurt, Almanya\'nın en pahalı şehirlerinden biri. WG odası €700-1,100 arasında. Öğrenci yurdu €350-500 arası — ama bekleme listesi uzun.</p><h3>Ulaşım</h3><p>RMV ulaşım kartı Semesterticket ile dahil. Frankfurt Hbf\'dan her yöne gidebilirsiniz.</p><h3>Artılar</h3><ul><li>İş bağlantıları — en büyük finans kurumları kapı komşunuz</li><li>Uluslararası atmosfer</li><li>Havalimanı — her şehre direkt uçuş</li></ul>',
                'type'        => 'experience',
                'category'    => 'city-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['frankfurt', 'şehir', 'deneyim'],
                'read_time'   => 6,
                'published_at'=> $now->copy()->subDays(3),
            ],
            [
                'slug'        => 'cologne-koeln-ogrenci-ipucu',
                'title_tr'    => 'Köln\'de Ucuz Yaşamanın 7 Sırrı',
                'summary_tr'  => 'Kölnlü öğrencilerin para biriktirdiği yollar: Mensa\'dan ikinci el eşyaya.',
                'content_tr'  => '<p>Köln, Almanya\'nın en büyük üniversite şehirlerinden biri. 100,000\'den fazla öğrenciyle şehir oldukça öğrenci dostu.</p><ol><li><strong>KVB Semesterticket:</strong> Tüm toplu taşıma dahil, dönemde ~€220</li><li><strong>Mensa Theologicum:</strong> En ucuz Mensa — günde €2.50\'ye yemek</li><li><strong>Ebay Kleinanzeigen:</strong> İkinci el mobilya — sıfır fiyatın %20\'sine</li><li><strong>Deutz pazarı:</strong> Cumartesi sabahı taze sebze meyve ucuz</li><li><strong>Kölner Dom çevresi:</strong> Turistik → pahalı. Ehrenfeld, Mülheim → ucuz ve şık</li><li><strong>Filmforum NRW:</strong> Öğrenci bileti €5.50</li><li><strong>KHM\'de sanat etkinlikleri:</strong> Çoğu ücretsiz</li></ol>',
                'type'        => 'tip',
                'category'    => 'city-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['cologne', 'bütçe', 'ipucu'],
                'read_time'   => 4,
                'published_at'=> $now->copy()->subDays(6),
            ],
            [
                'slug'        => 'sehir-secimi-sunum',
                'title_tr'    => 'Sunum: Almanya\'da Şehir Seçimi — 10 Şehir Karşılaştırması',
                'summary_tr'  => 'Kira, iş imkânı, ulaşım, öğrenci yaşamı: 10 Alman şehrini görsel olarak karşılaştıran sunum.',
                'content_tr'  => '<p>Bu sunumda Almanya\'nın en popüler 10 öğrenci şehri kira maliyeti, iş imkânları, ulaşım kalitesi ve kültürel yaşam açısından karşılaştırılıyor.</p>',
                'type'        => 'presentation',
                'category'    => 'city-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['şehir', 'karşılaştırma', 'sunum'],
                'video_url'   => 'https://docs.google.com/presentation/d/e/2PACX-placeholder-city/embed',
                'read_time'   => 12,
                'published_at'=> $now->copy()->subDays(10),
            ],
            [
                'slug'        => 'stuttgart-otomotiv-sehri',
                'title_tr'    => 'Stuttgart\'ta Öğrenci & Mühendis: Mercedes ve Porsche Şehri',
                'summary_tr'  => 'Stuttgart\'ın otomotiv endüstrisi ve üniversite yaşamı. Staj fırsatları ve kampüs kültürü.',
                'content_tr'  => '<h2>Stuttgart = Otomotiv Kalbi</h2><p>Stuttgart, Almanya\'nın en güçlü sanayi ekosistemlerinden birine ev sahipliği yapar. Mercedes-Benz, Porsche, Bosch, ZF Friedrichshafen — hepsi burada.</p><h3>Üniversiteler</h3><ul><li><strong>Universität Stuttgart:</strong> Teknik-ağırlıklı, mühendislik araştırmada güçlü</li><li><strong>HFT Stuttgart:</strong> Teknik FH, mimarlık ve inşaat</li><li><strong>DHBW Stuttgart:</strong> Duales Studium — çalışarak okuma modeli</li></ul><h3>Staj İpuçları</h3><p>Porsche ve Mercedes HR departmanları Stuttgart kampüslerinde aktif recruiting yapıyor. Kariyer fuarlarını kaçırmayın.</p>',
                'type'        => 'career_guide',
                'category'    => 'city-content',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['stuttgart', 'otomotiv', 'kariyer'],
                'read_time'   => 7,
                'published_at'=> $now->copy()->subDays(18),
            ],

            /* ── CAREERS ── */
            [
                'slug'        => 'almanya-is-basvurusu-cv',
                'title_tr'    => 'Almanya\'da CV Nasıl Yazılır? Alman Formatı',
                'summary_tr'  => 'Türk CV\'si ile Alman CV\'si arasındaki farklar. Bewerbung paketini doğru hazırlamak.',
                'content_tr'  => '<h2>Alman CV Formatı = Lebenslauf</h2><p>Alman CV\'si (Lebenslauf) Türk CV\'sinden oldukça farklı. İşte temel farklar:</p><h3>Yapı</h3><ul><li><strong>Fotoğraf zorunlu</strong> — Profesyonel vesikalık sol üstte</li><li><strong>Kişisel bilgiler</strong> — Doğum tarihi, uyruk, medeni durum dahil edilebilir</li><li><strong>Ters kronolojik sıra</strong> — En son deneyim önce</li><li><strong>Tablo formatı</strong> — Sol: tarih | Sağ: açıklama</li></ul><h3>Motivationsschreiben</h3><p>CV\'ye ek olarak motivasyon mektubu şart. Türkiye\'deki cover letter\'dan daha detaylı — neden bu şirkette, neden bu pozisyon, ne katkı sunacaksınız.</p><h3>Zeugnis</h3><p>Almanya\'da çalışma belgesi (Arbeitszeugnis) çok önemli. Mevcut çalışanlar için referans mektubu işlevi görür.</p>',
                'type'        => 'blog',
                'category'    => 'careers',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['cv', 'başvuru', 'kariyer'],
                'read_time'   => 8,
                'published_at'=> $now->copy()->subDays(4),
            ],
            [
                'slug'        => 'almanya-is-piyasasi-video',
                'title_tr'    => 'Video: Almanya İş Piyasası 2024 — Fırsatlar ve Zorluuklar',
                'summary_tr'  => 'Almanya\'da iş arayanlar için güncel iş piyasası analizi: hangi sektörler büyüyor, hangilerinde tıkanma var?',
                'content_tr'  => '<p>Bu videoda Almanya iş piyasasının 2024 görünümünü analiz ediyoruz.</p><p><strong>İçerik:</strong></p><ul><li>Fachkräftemangel (uzman açığı) — hangi alanlar etkileniyor?</li><li>Yapay zeka etkisi — hangi meslekler dönüşüyor?</li><li>Türk kökenli mühendisler için fırsatlar</li><li>Bürokratik engeller: tanınma (Anerkennung) süreci</li></ul>',
                'type'        => 'video_feature',
                'category'    => 'careers',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['iş-piyasası', 'kariyer', 'almanya'],
                'video_url'   => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'read_time'   => 18,
                'published_at'=> $now->copy()->subDays(7),
            ],
            [
                'slug'        => 'almanya-kariyer-podcast',
                'title_tr'    => 'Podcast: Almanya\'da Kariyer Geçişleri — 3 Farklı Sektör',
                'summary_tr'  => 'Yazılım, sağlık ve mühendislik alanlarında kariyer geçişi yapan 3 uzmanla söyleşi.',
                'content_tr'  => '<p>Bu bölümde kariyer değişikliği yapan 3 uzmanla konuşuyoruz: Yazılımcılıktan product manager\'lığa, hemşirelikten hastane yönetimine, makine mühendisliğinden veri bilimciliğine.</p>',
                'type'        => 'podcast',
                'category'    => 'careers',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['kariyer', 'podcast', 'geçiş'],
                'video_url'   => 'https://open.spotify.com/embed/episode/placeholder3',
                'read_time'   => 50,
                'published_at'=> $now->copy()->subDays(13),
            ],

            /* ── STUDENT-LIFE ── */
            [
                'slug'        => 'ogrenci-psikoloji-almanya',
                'title_tr'    => 'Almanya\'da Öğrenci Psikolojisi: Yalnızlık ve Başa Çıkma',
                'summary_tr'  => 'Pek çok öğrencinin konuşmak istemediği konu: yabancı bir ülkede yalnızlık hissi ve nasıl aşılır.',
                'content_tr'  => '<h2>Konuşulması Gereken Bir Konu</h2><p>Sosyal medyada hep güzel anlar paylaşılır. Ama gerçekte çoğu uluslararası öğrenci ilk aylarında ciddi yalnızlık hisseder.</p><h3>Neden Bu Kadar Yoğun?</h3><ul><li>Aile ve arkadaş ağından kopuş</li><li>Dil bariyeri — derinlemesine sohbet kuramama</li><li>Alman sosyal kültürü — yeni arkadaşlık kurmak zaman alır</li><li>Akademik baskı</li></ul><h3>Başa Çıkma Yolları</h3><ul><li>Üniversite psikolojik danışmanlık hizmetleri (ücretsiz)</li><li>Erasmus/Internationals etkinlikleri</li><li>Spor kulüplerine katılmak</li><li>Volunteer işler — hem sosyal hem de Almanca pratik</li></ul>',
                'type'        => 'blog',
                'category'    => 'student-life',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['psikoloji', 'yalnızlık', 'öğrenci'],
                'read_time'   => 7,
                'published_at'=> $now->copy()->subDays(5),
            ],
            [
                'slug'        => 'almanya-ogrenci-gunlugu-video',
                'title_tr'    => 'Video: Almanya\'da Bir Öğrencinin Haftalık Rutini',
                'summary_tr'  => 'Ders, kütüphane, Mensa, spor, alışveriş — gerçek bir öğrenci haftası.',
                'content_tr'  => '<p>Bu videoda bir öğrencinin Almanya\'daki tipik haftasını takip ediyoruz. Ders programından hafta sonu aktivitelerine kadar her şey dahil.</p>',
                'type'        => 'video_feature',
                'category'    => 'student-life',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['vlog', 'rutin', 'öğrenci'],
                'video_url'   => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'read_time'   => 15,
                'published_at'=> $now->copy()->subDays(8),
            ],
            [
                'slug'        => 'almanya-ogrenci-butce-sunum',
                'title_tr'    => 'Sunum: Almanya\'da Öğrenci Bütçesi — Aylık €800\'a Yaşanır mı?',
                'summary_tr'  => 'Almanya\'nın 5 farklı şehrinde öğrenci yaşam maliyetlerini karşılaştıran sunum.',
                'content_tr'  => '<p>Bu sunumda Berlin, München, Hamburg, Stuttgart ve Köln\'deki ortalama öğrenci yaşam maliyetleri karşılaştırılıyor.</p>',
                'type'        => 'presentation',
                'category'    => 'student-life',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['bütçe', 'maliyet', 'öğrenci'],
                'video_url'   => 'https://docs.google.com/presentation/d/e/2PACX-placeholder-budget/embed',
                'read_time'   => 10,
                'published_at'=> $now->copy()->subDays(11),
            ],

            /* ── TIPS-TRICKS ── */
            [
                'slug'        => 'almanya-pratik-ipuclari-video',
                'title_tr'    => 'Video: Almanya\'da İlk 30 Gün — Yapılacaklar Listesi',
                'summary_tr'  => 'Almanya\'ya yeni gelenlerin ilk 1 ayda yapması gereken her şeyi anlatan video rehber.',
                'content_tr'  => '<p>Almanya\'ya yeni geldiniz. Ne yapmalısınız? Bu videoda ilk 30 gündeki zorunlu ve önemli adımları sıralıyoruz.</p>',
                'type'        => 'video_feature',
                'category'    => 'tips-tricks',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['ipucu', 'yeni-gelme', 'checklist'],
                'video_url'   => 'https://www.youtube.com/embed/dQw4w9WgXcQ',
                'read_time'   => 20,
                'published_at'=> $now->copy()->subDays(3),
            ],
            [
                'slug'        => 'almanya-pratik-podcast',
                'title_tr'    => 'Podcast: Almanya\'da Bürokratik Labirент — Nasıl Çıkılır?',
                'summary_tr'  => 'Anmeldung, Krankenversicherung, Finanzamt... Almanya bürokrasisini bilen uzmanla konuşuyoruz.',
                'content_tr'  => '<p>Bu bölümde Almanya bürokratik süreçlerinde uzmanlaşmış bir danışman ile tüm temel işlemleri konuşuyoruz.</p>',
                'type'        => 'podcast',
                'category'    => 'tips-tricks',
                'status'      => 'published',
                'target_audience' => 'all',
                'tags'        => ['bürokrasi', 'podcast', 'pratik'],
                'video_url'   => 'https://open.spotify.com/embed/episode/placeholder4',
                'read_time'   => 35,
                'published_at'=> $now->copy()->subDays(14),
            ],

        ];

        $adminId = \App\Models\User::first()?->id ?? 1;

        foreach ($items as $data) {
            $readMins = $data['read_time'] ?? 5;
            unset($data['read_time']);

            CmsContent::updateOrCreate(
                ['slug' => $data['slug']],
                array_merge($data, [
                    'created_by'                   => $adminId,
                    'metric_total_views'           => rand(20, 800),
                    'metric_avg_read_time_seconds' => $readMins * 60,
                ])
            );
        }

        $this->command->info('ContentHubSeeder2: ' . count($items) . ' içerik eklendi/güncellendi.');
    }
}
