<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Topluluk SSS Arsivi (Community FAQ Archive)
    |--------------------------------------------------------------------------
    |
    | Telegram topluluk forumlarindan anonim olarak derlenmis ve sik sorulan
    | sorularin yapisal arsivi. Her soru: tarih + konu kategorisi.
    | PII (isim, telefon, mention, mail) temizlenmistir.
    |
    | Bu sorular /sss/topluluk public endpoint icin kullanilir ve AI Labs
    | knowledge base seed kaynagidir.
    |
    | Toplam: 499 soru / 20 konu (5 doktor alt-kategorisi dahil)
    |
    */

    "topics" => [
        "vize" => [
            "title" => "Vize ve Sperrkonto",
            "description" => "Almanya ulusal vizesi, dil kursu vizesi, bloke hesap, IDATA randevu surecleri",
            "icon" => "shield-check",
            "questions" => [
                ["date" => "06.08.2018", "text" => "Bir de vize için başvuru nasıl yapılabilir? Dil kursu kaydıyla mı, yoksa üniversiteye başvuru mu yapmak gerekir?"],
                ["date" => "19.09.2020", "text" => "Mavikart basvurusu sirasinda ailesi icin basvurabilen var mi? Konsolosluk olur mümkün derken IDATA direnc gösteriyor.Yakkin zamanda Ankara dan basvuran var mi?"],
                ["date" => "19.09.2020", "text" => "Anne babasını yanına getirmek ya da istediği zaman istediği müddette ziyaret edebilecek şekilde bir vize/oturum kartı vs alınabiliniyor mu? Evet ise bu vize türünün / oturum kartının türü nedir?"],
                ["date" => "06.10.2020", "text" => "Su an Stellenangebote alanlar vize alabiliyor mu biliyor musunuz?"],
                ["date" => "06.10.2020", "text" => "Almanya’da goethe üzerinden bir Almanca kursuna kaydolursam vize alabilir miyim?"],
                ["date" => "22.10.2020", "text" => "Bu durum vize açısından yeni bir pencere açar mi sizce? Bu konuda bir haber okuyan veya yetkili birinden açıklamaya rastlayan var mi?"],
                ["date" => "08.12.2020", "text" => "Yakin zamanda vize basvurusunda bulunan var mi? Ortalama kac ay/hafta sonra randevu veriyorlar?"],
                ["date" => "11.10.2018", "text" => "Dil kursu vizesini tavsiye etmiyorsunuz fakat is arama vizesi icin appro istiyor konsolosluk, dolayisiyla B2 almak da yeterli olmuyor bu konuda ne oneriyorsunuz?"],
                ["date" => "15.02.2021", "text" => "Son dönemde dil kursu vizesiyle giden oldu mu ? 2 hafta sonra vize randevum var da belgelerle alakalı birkaç şey soracağım ?"],
                ["date" => "17.02.2021", "text" => "Fintiba dışında bloke hesap oluşturabileceğim uygulama var mı bildiğiniz ?"],
                ["date" => "24.03.2021", "text" => "Beglaubigung için konsolosluk sayfasından randevu almaya çalışıyorum birkaç gündür ama olmuyor. Randevu alabilen var mı acaba?"],
                ["date" => "13.05.2021", "text" => "Yaz stajı için vize başvurusunda bulunan ya da alabilen oldu mu?"],
                ["date" => "25.05.2021", "text" => "Sperr konto açtırıp dil kursuyla anlaşsak bile vize vermeyecekler mi?"],
                ["date" => "11.06.2021", "text" => "Yani illa oturum izni ya da vize olması şart gibi bir durum yok mu?"],
                ["date" => "18.06.2021", "text" => "Teşekkür ederim cevabınız için. Peki yaklaşık ne kadar zaman sonra vize için olumlu ya da olumsuz dönüş yapıyorlar biliyor musunuz?"],
                ["date" => "23.06.2021", "text" => "Arkadaşlar merhaba. Ulusal vize başvurusunda istenen belgeler arasında dil sertifikası göstermek zorunlu mu ?"],
                ["date" => "27.06.2021", "text" => "Herkese merhaba,son zamanlarda hospitaton için ulusal vize alabilen oldu mu?"],
                ["date" => "13.07.2021", "text" => "Iyi akşamlar , vize için istenen sigorta hakkında bilgisi olan var mı ??"],
                ["date" => "27.02.2019", "text" => "Fintiba basic ve plus arasinda nasil bir fiyat farki var hocam? Ve ulusal vize icin plus saglik sig kabul ediliyor mu?"],
                ["date" => "27.02.2019", "text" => "Bir soru daha sorayim hocam size bilginiz varsa. Biz 4 aylik dil kursu vizesine basvurucaz. Bloke hesaba 6 aylik yatirmam yeterli olur mu?"],
                ["date" => "02.08.2021", "text" => "Ankaradan 44 f vize çıkma süresi ortalama nedir ? Tecrübesi olan var mı?"],
                ["date" => "02.08.2021", "text" => "Vize için dil kursu kaydının en az 6 ay olması mı gerekiyor? Yoksa 3 ay sürecek bir dil kursuna vize verilebiliyor mu?"],
                ["date" => "06.08.2021", "text" => "Dil kursu vizesine başvururken ,çocuğumuz için de vize çıkarabilir miyiz ,herhangi bi sorun oluyor mu??"],
                ["date" => "19.08.2021", "text" => "Arkadaşlar hospitasyon yaptığımızda tüm konaklama, yemek, ulaşım, vize gibi giderlerin hepsini kendimiz mi karşılıyoruz?"],
                ["date" => "02.09.2021", "text" => "Bloke hesap olarak ne kadar paranın hesapta olmasını istiyorlar?"],
            ],
        ],
        "dil" => [
            "title" => "Almanca Dil Sertifikalari",
            "description" => "Goethe, Telc, TestDaF, DSH sinavlari ve B1/B2/C1 hazirlik surecleri",
            "icon" => "language",
            "questions" => [
                ["date" => "12.08.2018", "text" => "Herkese Selam .. Goethe nin online kursu nasıldır fikri olan varmı ?"],
                ["date" => "21.02.2020", "text" => "Ben nrw\"de doktorum. b2 tamamladım. ama münsterden abrovasyon çok zor siyorlar. ben de beşka eyaletten girmek istiyorum. nereyi tavsiyenedersiniz? hangi eyalet şu sıralar en uygun ?"],
                ["date" => "21.02.2020", "text" => "Aile hekimliği çekirdek TUKMOS gibi bir programı almanca ya çevirten kimse var mı acaba?"],
                ["date" => "09.03.2020", "text" => "Dolandırıcılık diyemesem de bir çeşit umut tacirliği. Arkadaşın dediği gibi B2 fsp ve appro konusunda yardım edemeyeceklerine göre, ne faydası olacak?"],
                ["date" => "19.03.2020", "text" => "Alman lisesi mezunuyum , abitur yaptim oradan almancam var. Abitur veya sprachdiplom B2 olmasi ne gibi faydalar sağlar acaba?"],
                ["date" => "29.03.2020", "text" => "Selamlar, dil kursuna gitmeden Almanca öğrenme şansım var mı? Aramızda öğrenen var mı?"],
                ["date" => "13.04.2020", "text" => "BW ve Bayern hep kabul etti şimdiye kadar, turkiyedeki almanca yeminli tercüman mı kabul edilmedi?"],
                ["date" => "15.04.2020", "text" => "Almanca kurslarin ne zaman baslayabilecegi ile ilgili bilgi paylasildi mi?"],
                ["date" => "23.04.2020", "text" => "Online herangi bir almanca kursuna katılıp memnun olan var mı? Goethe ya da almanyadaki kurslardan?"],
                ["date" => "24.04.2020", "text" => "Teoride evet ama onun yerine almanca öğrenip gerçekten istediğiniz branşta doktorluk yapabilecek seviyede olmak daha mantıklı değil mi?"],
                ["date" => "30.04.2020", "text" => "genelde B2 aldiktan sonra ilk yaomamiz gereken Appro bashvurusumu yoksa BE bashvurusu. Yoksa bunlar aynimi?"],
                ["date" => "01.05.2020", "text" => "O zaman almanca yi da öğrendikten sonra isviçre ye başvuru yapıp asistanlığın orada yapılabilme ihtimali var değil mi hocam ?"],
                ["date" => "05.05.2020", "text" => "Tavsiye edebileceğiniz bir online ders veren almanca öğretmeni var mı?"],
                ["date" => "12.05.2020", "text" => "Türkiyedeki Telc FSP ye girebilmek için öncesinde Almanyadaki geçerli üç eyaletten birinden is ayarlamis olmak gerekiyor mu?"],
                ["date" => "21.05.2020", "text" => "Goethe Almanca sınav tarihleri henüz belli değil. Sınav tarihleri belli olan ve dil sertifikası geçerli başka kurum var mı bildiğiniz ?"],
                ["date" => "28.05.2020", "text" => "ikinci sorum telc med c1 türkiyede almak mı mantıklı, almanyada almak mı?"],
                ["date" => "28.05.2020", "text" => "iki tipi var telc med b2-c1 ve telc med fsp. hangisine girmek lazım?"],
                ["date" => "31.05.2020", "text" => "Selamlar, DSH (Deutsche Sprachprüfung für den Hochschulzuganh) sınavını alırsak C1 ya da FSP'den muaf oluyor muyuz acaba bilen var mı?"],
                ["date" => "12.06.2020", "text" => "almanca online ders veren hoca arıyorum!! tanıdıgınız birisi varmı?"],
                ["date" => "22.06.2020", "text" => "Almanca çalışan bir doktor olduğumu bilen biri o zaman şuna bi bakar mısın dedi. Kalakaldım. Yardımınız olabilir mi?"],
                ["date" => "08.07.2020", "text" => "Herkese iyi akşamlar b2 seviyesi için online birebir ders veren tanıdığınız hoca veya kurs var mı ?"],
                ["date" => "17.07.2020", "text" => "Grupta Telc-fsp-medizin sınavına Türkiye’de giren var mı acaba?"],
                ["date" => "20.07.2020", "text" => "İyi günler goethe'nin online almanca kursu hakkında bilgisi olan veya önerebileceği online almanca kursu olan bana yazabilir mi?"],
                ["date" => "27.07.2020", "text" => "İyi günler arkadaşlar Ben goethe b1 sınavında tek hörende kaldım Büyükelçilik kabul eder mi acaba ?"],
                ["date" => "27.07.2020", "text" => "Selamlar herkese. Mit Erfolg zu Telc deutsch B2 pdf olan varsa paylaşabilir mi ?"],
            ],
        ],
        "randevu" => [
            "title" => "Konsolosluk + IDATA Randevu",
            "description" => "Vize randevu sureleri, IDATA evrak teslim, basvurulardaki gecikmeler",
            "icon" => "calendar",
            "questions" => [
                ["date" => "04.09.2020", "text" => "Evrakları geri verip 75 eu eusunu geri verilenler olmuş demi, idata yanlışlık yapmış deyip?"],
                ["date" => "19.09.2020", "text" => "Mavikart basvurusu sirasinda ailesi icin basvurabilen var mi? Konsolosluk olur mümkün derken IDATA direnc gösteriyor.Yakkin zamanda Ankara dan basvuran var mi?"],
                ["date" => "08.12.2020", "text" => "Yakin zamanda vize basvurusunda bulunan var mi? Ortalama kac ay/hafta sonra randevu veriyorlar?"],
                ["date" => "17.02.2021", "text" => "Dil kursu vizesi için başvurduktan sonra randevu tarihi verilmesi için ne kadar süre beklediniz?"],
                ["date" => "24.03.2021", "text" => "Beglaubigung için konsolosluk sayfasından randevu almaya çalışıyorum birkaç gündür ama olmuyor. Randevu alabilen var mı acaba?"],
                ["date" => "05.05.2021", "text" => "Yakın zamanda ankara konsolosluğuna dil vizesi için başvurup randevu tarihi alan varmı?"],
                ["date" => "01.06.2021", "text" => "Selamlar, yakın zamanda Ankara valiliğinden apostil yaptıran oldu mu? Randevu gerekiyır mu pandemi nedeniyle?"],
                ["date" => "22.06.2021", "text" => "Benim gibi Izmir Baskonsolosluguna bagli bir ilgen basvuracak olup ulusal randevu sisteminden randevu olusturamayan var mi?"],
                ["date" => "03.09.2021", "text" => "Teşekkür ederim hocam. Şimdi baktım randevu için. En yakın tarihler hep ekim başı. Ne yapabilirim bunun için?"],
                ["date" => "03.09.2021", "text" => "Tamamdır öyle yaparım.Teşekkür ederim.Ancak yine de randevu bulamazsam ne yapmalıyım?"],
                ["date" => "02.12.2021", "text" => "Yakın zamanda idatadan hospitation için randevu alan oldu mu acaba?"],
                ["date" => "08.04.2022", "text" => "Arkadaslar merhabalar, Blue card icin Idata’dan randevu almak ne kadar suruyor bi bilginiz var mi?"],
                ["date" => "11.05.2022", "text" => "Arkadaşlar bu aralar idatanin ulusal vize icin aylarca randevu vermedigi konusuluyor. Hizlandirmak icin bir önerisi olan var mıdır?"],
                ["date" => "13.05.2022", "text" => "İzmir idata ulusal için başvuran oldu mu yakın zamanda? Randevu süresini sorabilir miyim?"],
                ["date" => "23.05.2022", "text" => "Alman konsoloslugundan adli sicil kaydi cikartan var mi acaba? Randevu almadan cikartilabiliniyor mu?"],
                ["date" => "04.06.2022", "text" => "Ama yine pasaport nunaranizi vermis oluyorsunuz. Tekrarli randevu alinmaz diye dusunuyorum. Denemedim ama?"],
                ["date" => "18.07.2022", "text" => "Selamlar arkadaş, yakin zamanda mavi kart için Ankara idatadan randevu alan oldu mu acaba??? Başvurudan sonra randevu ne zamana veriliyor bilen var mıdır acaba???"],
                ["date" => "20.07.2022", "text" => "İdata da başvuru sırasında ek hizmet olarak fotokopi var. Ne anlama geliyor?"],
                ["date" => "25.07.2022", "text" => "Arkadaşlar nrw ve niedersachsenda güncel fsp termin süresi hakkında bilgisi olan var mı?"],
                ["date" => "10.08.2022", "text" => "26 haziranda başvurdum idata ‘ya daha randevum gelmedi ,acaba benzer durumları yaşayan var mı ,acaba başvurduğumuz şehrin ya da ikametimizin bir etkisi var mı?"],
                ["date" => "31.08.2022", "text" => "Mavi kart vizesi için şu an randevu tarihleri en son ne zaman başvuranlara verildi acaba bilgisi olan var mı?"],
                ["date" => "01.09.2022", "text" => "İyi akşamlar arkadaşlar, iDATA vize başvurusu için evrakları teslim etmek için çağırdığında hangi şehirler oluyor bunlar bileniniz var mı?"],
                ["date" => "01.09.2022", "text" => "Arkadaşlar ağustos ayının başında idataya başvurumu yaptım hala randevu ataması olmadı. Bu ara çok bekleyen oldu mu?"],
                ["date" => "05.09.2022", "text" => "hangi sehir hocam? ve tarihleriniz nedir? basvuru, randevu, vize gelmesi?"],
                ["date" => "05.09.2022", "text" => "İdata başvurusunda sağlık alanında eğitimimi tamamladım, Almanya'da ileriki iş hayatim için teşvik ve hazırlık için dil kursuna basvuruyorum- bu soruya evet mi hayır mı dediniz?"],
            ],
        ],
        "uni_assist" => [
            "title" => "Uni-Assist ve VPD",
            "description" => "On-degerlendirme, HZB notu, evrak yukleme, Mein Konto kullanimi",
            "icon" => "file-check",
            "questions" => [
                ["date" => "22.08.2022", "text" => "Uni-assist üzerinden başvurulduysa tekrardan okula başvurmaya gerek var mı?"],
                ["date" => "13.06.2023", "text" => "Bremen universitesine kayit yapmak istiyorum daha oncesinde bu surecten gecen olduysa tecrubelerinden yararlanmak isterim surec nasil ilerliyor ? Uni assist uzerinden mi kayit yapiyoruz ?"],
                ["date" => "09.07.2023", "text" => "Arkadaşlar online-only applicationlarda dosyaları upload ettikten sonra uni assist merkeze posta ile göndermeye gerek yok degil mi? Kesin bilgi bu?"],
                ["date" => "29.07.2023", "text" => "Herkes iyi umarım. Arkadaşlar sizde Uni assist çalışıyor mu?"],
                ["date" => "15.08.2023", "text" => "Arkadaşlar Bremen’e başvuru yapıyorum ama HzB puanımı kabul etmiyor site bilgisi olan var mı ?"],
                ["date" => "19.11.2022", "text" => "fatih bey benim vpd belgem geldi ancak bremen üniversitesi portalına kayıt olamadım nasil yapılacağını biliyor musunuz ?"],
                ["date" => "01.12.2022", "text" => "Süper. başvurumu yaptıktan sonra vpd belgesini aldığımda bi daha üniversiteye başvuru yaptığımda kaç hafta ya da ay içerisinde cevap gelir?"],
                ["date" => "06.12.2022", "text" => "Bilgisi olan varmi 2 yıl önce açılmış Uni Assist profilini yinede kullanmak oluyomu aktuelmi yoksa yenisinimi açmak lazim diğeri eski sayilir diye??"],
                ["date" => "08.12.2022", "text" => "Uni-assist başvuru süreçleri ile ilgili ayrıntılı bilgi veren youtube videosu var mı?"],
                ["date" => "24.12.2022", "text" => "Arkadaşlar uni assist ödemesini yaptıktan ne kadar süre sonra kabul gelir?"],
                ["date" => "27.12.2022", "text" => "Bremen üniversitesi uni assist'ten başvuruya ek olarak kendilerine direkt başvuru da istiyorlar mi?"],
                ["date" => "03.01.2023", "text" => "Arkadaşlar merhaba, apostilli belgeleri Almanya’da nasıl çoğaltabilirim? Ve uni-assist Almanya’da çoğaltılan apostili ve diğer belgeleri kabul eder mi?"],
                ["date" => "03.01.2023", "text" => "Tamamdır hocam sağolasın, apostilli bi şekilde çoğaltma yapsalar uni-assist bunu kabul eder mi bilginiz var mı?"],
                ["date" => "21.01.2023", "text" => "Arkadaşlar merhaba, bu çok değişkenlik gösteriyodur ama uni-assist üniversitelere master veya lisans başvurusunu gönderdikten sonra ortalama ne kadar süre içinde üniversitelerden cevap alırız?"],
                ["date" => "03.02.2023", "text" => "TransferGo dan uni assist icin ödeme yapacağım fakat anlamadım yardım edebilecek biri var mı?"],
                ["date" => "03.02.2023", "text" => "VPD belgesi üni den uniye değişir mi yoksa illa almak zorunda mıyız ?"],
                ["date" => "13.03.2023", "text" => "Yakın zamanda vpd alan var mı şu sıralar ne kadar sürede geliyor?"],
                ["date" => "31.03.2023", "text" => "uniassist toplu kabul ettiğine göre başvuru süresi bittikten sonra mı üniversiteler kabul veriyor ?"],
                ["date" => "02.05.2023", "text" => "Lisans mezunuyum, tekrardan lisans okuyacağim. Uni-assist portalina lise transkript yüklemek gerek mi?"],
                ["date" => "08.05.2023", "text" => "Tüm üniversitelere başvuru uni assist üzerinden mi alınıyor?"],
                ["date" => "22.05.2023", "text" => "Üniversite başvurusundan kaç gün sonra VPD belgesini uni-asisst gönderiyor ?"],
                ["date" => "30.08.2023", "text" => "Bremene moin portali üzerinden basvururken motivasyon mektupu istemiyor mu? Uni-asist tek vpd için mi istiyordu?"],
                ["date" => "29.05.2024", "text" => "Üni Bremen den aldığım VPD ile başka üniversitelere bu VPD yi sunabilir miyim yoksa her üniversite için ayri ayri Uni Assiten VPD mi almaliyim?"],
                ["date" => "23.12.2022", "text" => "Arkadaşlar vpd ile A/T 11 belgesi alınıyor mu? Bu konuda bilgisi olan var mıdır?"],
                ["date" => "06.01.2023", "text" => "Bremen uni şartlı kabul her bölüm için uni assist üzerinden mi alıyor?"],
            ],
        ],
        "master" => [
            "title" => "Yuksek Lisans ve Master",
            "description" => "Master programlari, dil sartlari, kabul ve burs imkanlari",
            "icon" => "graduation-cap",
            "questions" => [
                ["date" => "28.09.2023", "text" => "internette arama yaptigimda PhD / master vs olarak cikiyor. Tibbi Biyokimya ihtisas icin surec nasil isliyor ?"],
                ["date" => "25.08.2022", "text" => "Arkadaşlar selam, master kabulü aldım. Yeşil pasaportum var. Vize işlemlerini Almanya'nın içinden yapabilir miyim önden gitsem?"],
                ["date" => "22.09.2022", "text" => "arkadaslar almanyaya master egitimi icin gidiyorum 20 saatlik calisma iznim var di mi simdi benim ? ve ben onu liferando da kullanabilir miyim ?"],
                ["date" => "24.09.2022", "text" => "Arkadaslar master icin mainz universitesini dusunuyorum da, burslarla ilgili pek bilgi bulamadim internette. Yardimci olmak isteyen biri bana dm atabilir mi ?"],
                ["date" => "11.06.2023", "text" => "Herkese merhabalar. Okullarin yuksek lisans icin istedikleri dil seviyeleri farkli biliyorum ama eger goethe b2 dil sertifikasi alirsak sartli kabul olmadan direkt yuksek lisansa baslayabilir miyim?"],
                ["date" => "22.07.2023", "text" => "Master başvurularına 3. sınıfta mı başlamak gerekiyor 4. sınıf bittikten sonraki dönemde master'a başlamak için?"],
                ["date" => "26.08.2023", "text" => "Ücretsiz eğitim alabileceğim master bölümleri mümkün mü acaba yoksa söylenti mi?"],
                ["date" => "10.05.2024", "text" => "Arkadaşlar merhaba düşük gpa ile Almanya'da master veya bachelor kabulü alan var mı ?"],
                ["date" => "27.05.2024", "text" => "Arkadaşlar aramızda mimarlık alanında İngilizce master kabulü alan/okuyan var mı ?"],
                ["date" => "22.11.2022", "text" => "master öğrenci vize türlerinden 36f ile 40f’in farkı nedir ?"],
                ["date" => "17.12.2022", "text" => "Iyi aksamlar arkadaslar. Yuksek lisans sirasinda bir sirketle anlasip yüksek lisansi dondurarak calismaya baslayabilir miyiz?"],
                ["date" => "30.12.2022", "text" => "Teşekkür ederim. Master ya da üniversite başvurusu yaparsanız işler kolaylaşır gibime geliyor. Bu seçeneği düsündünüz mü?"],
                ["date" => "07.01.2023", "text" => "Master için direkt bölüme mi başvurmamız gerekiyor yoksa okulun hazırlık kursuna mı?"],
                ["date" => "19.01.2023", "text" => "b2 goethe ya da telc sertifikasiyla sartli kabul mu aliriz yoksa direkt kabul ederler mi master icin?"],
                ["date" => "20.01.2023", "text" => "Yazın da master için başvurular oluyor mu arkadaşlar yoksa bitti mi?"],
                ["date" => "21.01.2023", "text" => "Arkadaşlar merhaba, bu çok değişkenlik gösteriyodur ama uni-assist üniversitelere master veya lisans başvurusunu gönderdikten sonra ortalama ne kadar süre içinde üniversitelerden cevap alırız?"],
                ["date" => "25.01.2023", "text" => "Herkese iyi akşamlar, Master yapmak için şuanda 2023 Eylül ayında başlayacak olan dönemin kayıtları kapandı değil mi? En erken başvurular 2024 şubat dönemine ait olacak sanırım?"],
                ["date" => "01.02.2023", "text" => "Arkadaşlar 40f ile 41f arasında temel fark nedir ? Master için ingilizce tam kabul belgesi aldığımız da hangi vize türüne başvurmak gerekiyor ?"],
                ["date" => "12.02.2023", "text" => "Arkadaslar merhaba,almanyada yuksek lisans yapmak icin ne yapmaliyim. almancam yok.surec ile bilgisi olan var mi?"],
                ["date" => "28.02.2023", "text" => "Dil vizesi veya master için alınan vize ile ailemi götürebilir miyim?"],
                ["date" => "06.04.2023", "text" => "duisburg-essen Volkswirtschaftslehre Master bu dönem baslayacak olan var mi ?"],
                ["date" => "12.02.2023", "text" => "Arkadaslar merhaba,Almanyada yuksek lisans yapmak icin ne yapmaliyim ,almancam yok.surec ile ilgili bilgisi olan var mi?"],
                ["date" => "02.07.2023", "text" => "Selamlar, 3 tane NC-frei master bölümüne başvuru yaptım. Öğrenci profilim iyi ancak dil sertifikam yok. Bu üniversiteler kendi bünyesinde dil okulu sunuyorlar websitelerine göre. Sizce şansım nedir?"],
                ["date" => "30.07.2021", "text" => "İyi akşamlar, aranızda türkiye de PDR eğitimi almış olup Almanya da master yapan veya çalışan var mı? Hangi bölümde okuyor veya çalışıyorsunuz?"],
                ["date" => "11.12.2022", "text" => "herkese selam , master makine mühendisliği , şartsız , ön onay veren üniversite arıyorum, ayrıca uni asistten istemeyen, evrakları kargolatmayan, arıyorum hangileri vardır ?"],
            ],
        ],
        "studienkolleg" => [
            "title" => "Studienkolleg + FSP",
            "description" => "Hazirlik kursu, Feststellungspruefung ve M-Kurs / T-Kurs secimi",
            "icon" => "book-open",
            "questions" => [
                ["date" => "03.07.2022", "text" => "Arkadaslar merhaba. Cirriculum hazirlama surecindeyim. 1 sene hazirlik okudum. Hazirlik suresini cirriculuma eklemeli miyim ?"],
                ["date" => "05.09.2022", "text" => "İdata başvurusunda sağlık alanında eğitimimi tamamladım, Almanya'da ileriki iş hayatim için teşvik ve hazırlık için dil kursuna basvuruyorum- bu soruya evet mi hayır mı dediniz?"],
                ["date" => "28.09.2023", "text" => "Arkadaşlar herkese sürecinde başarılar ve hayırlar diliyorum. Fsp hazırlık için kitap önerebilecek olan var mıdır acaba?"],
                ["date" => "19.03.2024", "text" => "Arkadaşlar merhaba, tıp fakültesi ingilizce hazırlık sınıfını belgelerde belirtmemiz gerekiyor mu( örneğin curriculum, transkript, intibak raporu) yoksa 1. Sınıftan itibaren mi yazmalı?"],
                ["date" => "19.05.2024", "text" => "Arkadaşlar merhaba: Koblenz'de devlet hibesiyle verilen ücretsiz bir fsp hazırlık kursu olduğunu duydum. Aranızda bu kursa katılan var mı acaba?"],
                ["date" => "16.10.2024", "text" => "Arkadaşlar Koblenz ISL Sprachschule ya giden oldu mu? B2 ve Fsp hazırlık için önerir misiniz ?"],
                ["date" => "13.12.2024", "text" => "Studienzeutraum'a hazırlık okuduğum süreyi dahil edip öyle mi yazayım yoksa sadece fakülte yıllarını mı yazayım?"],
                ["date" => "22.01.2025", "text" => "Heildelberger padagogium dil kursuna giden var mi acaba? Fsp hazirlik kurslari veriyorlar mi?"],
                ["date" => "29.06.2023", "text" => "Ben lisans mezunuyum yeni mezun oldum. 2024 yilinda hazirlik kurslari Almanca kurslari icin basvurular ne zaman basliyor .Hicbir bilgim yok surec ile ilgili?"],
                ["date" => "29.06.2023", "text" => "Hmm anladim.Hazırlık icin konusuyorsunuz degil mi? Nisan ayinda hazirliga baslamak istiyorsam aralik gibi basvurmam mı lazım?"],
                ["date" => "29.06.2023", "text" => "Bir de orada hazirlik okumam icin tabi ki de universiteden sartli kabul almam lazim degil mi?"],
                ["date" => "12.07.2023", "text" => "Universitelerin almanca hazirlik okullari ucretsiz mi oluyor?"],
                ["date" => "08.08.2023", "text" => "Ben üniversite bitirdim, studienkolleg okumak istiyorum izin verirler mi?"],
                ["date" => "28.08.2023", "text" => "Dil hazirlik ogrencisi olarak gidip calisma izninizin olacagini nasil garanti goruyorsunuz ?"],
                ["date" => "26.01.2024", "text" => "Siegen Üniversitesi hazırlık kursu hakkında bilgisi olan var mı ? Nasıl iyi mi orda hazırlık okunur mu ?"],
                ["date" => "26.01.2024", "text" => "Hiç dil bilmeden kabul alabileceğimiz ya da Max 2 ile hazırlık kursuna şartlı kabul şeklinde kaç üniversite var ? En çok tercih edilenler neler ?"],
                ["date" => "24.10.2022", "text" => "Arkdaşlar istediğim bölüm hazırlık okuyacağım üniversitede yoksa yine de o üniversitede hazırlık alabilir miyiz?"],
                ["date" => "29.10.2022", "text" => "Orda da telc yada goethe giriyoruz orda hazırlık okumanın bi avantajı var mı ?"],
                ["date" => "19.11.2022", "text" => "Arkadaşlar merhaba Almanca dilinde yüksek yüksek lisans için Almanca hazırlık eğitimi veren okul başvurularında konsolosluk veya okulun kendisi Almanca dil sertifikası istiyor mu ?"],
                ["date" => "23.11.2022", "text" => "Şartlı kabul vermekle sadece hazırlık kursuna kabul vermenin arasında nasıl bir fark var peki?"],
                ["date" => "07.01.2023", "text" => "Master için direkt bölüme mi başvurmamız gerekiyor yoksa okulun hazırlık kursuna mı?"],
                ["date" => "29.01.2023", "text" => "Arkadaşlad Almanya da üniversite okumak için dil belgesi şart mı yoksa hazırlık sınıfı var mı ?"],
                ["date" => "04.04.2023", "text" => "Hangi üniversitelerin studienkolleg olmadan kabul ettiğini nereden öğrenebiliriz?"],
                ["date" => "04.05.2023", "text" => "Tûrkiyede açık lise okuduktan sonra 4 yıllık lisans eğitimi de bitirildiyse Studienkolleg gerekli mi peki bilgisi olan var mı?"],
                ["date" => "14.06.2023", "text" => "Arkadaşlar merhaba ,Wuppertal üniversitesinden kabul alan var mı ? Veya Wuppertal üniversitesinin Almanca hazırlık kursu hakkında bilgisi olan var mı ?"],
            ],
        ],
        "denklik" => [
            "title" => "Diploma Denkligi",
            "description" => "Tip ve diger meslekler icin Approbation, Anerkennung ve gutachten surecleri",
            "icon" => "certificate",
            "questions" => [
                ["date" => "02.03.2020", "text" => "Denklik almak için internlikte bizim 2 ay cerrahi almamız sorun olduğu Almanya'da pjlerin bunu 4 ay yaptığını yazmışsınız, benim bu yaptığım toplam 2 aylık stajlar bunu tamamlar mi?"],
                ["date" => "03.05.2020", "text" => "Almanyada alınan denklik İngilterede geçerli diye biliyorum peki UK deki diğer AB ülkelerinde geçerli mi biliyor musunuz?"],
                ["date" => "15.05.2020", "text" => "Olmaması lazım. Denklik ücretlerini neden Arbeitsagentur'dan talep etmediniz?"],
                ["date" => "06.07.2020", "text" => "Arkadaşlar. Grupta psikiyatri Uzmanı olupta denklik alan veya BE ile iş bulan kimse oldu mu? Yoksa boşuna mı uğraşıyorum?"],
                ["date" => "18.07.2020", "text" => "Nrw ye başvuran arkadaşlar var mı? Nrw de Denklik sürecinde zusage lazım mı?"],
                ["date" => "30.08.2020", "text" => "Ya arkadaslar bu sinav katilim belgesini Almanya'da denklik basvurusu icin verirken nasil vermek lazim?"],
                ["date" => "11.09.2020", "text" => "Sınavlar (dil-denklik vs) hepsi almanyada mı yapılıyor? Yakında bir sınav var mı? Sınır kısıtlaması dolayısı ile sınavlara giremeyenler var mı?"],
                ["date" => "06.10.2020", "text" => "Arkadaşlar Avusturya’da denklik ve çalışma konusunda bilgisi olan var mı ? Normalde C1 isteniyormuş ancak pandemi döneminde esneklik olduğunu duydum. Bilgisi olan var mı ?"],
                ["date" => "21.10.2020", "text" => "Genel cerrahide 4 ay asistanlık ile intörnlükteki cerrahi eksiği kapatıp KPye gerek kalmadan denklik alınabilir mi veya alan var mı?"],
                ["date" => "02.11.2020", "text" => "Herkese merhaba..Dokuz Eylül Tıp mezunu olup gutachten yoluyla (sınavsız) Denklik alan var mı acaba???"],
                ["date" => "03.11.2020", "text" => "Metin Bey uzman doktorlar icin denklik sınav yerine dosya hazirlasak ve Kendi bransimizda asistanliga başlarsak yine 1. Yıl asistani olarak mı başlıyoruz?"],
                ["date" => "29.10.2018", "text" => "Mrb hocam denklik denk sayılıp sayılmadığını nasıl nerden öğrenebiliriz.Gürcistan dan mezunum.dil sıkıktısı olmasa acaba direk çalışabiliyor muyum?"],
                ["date" => "18.12.2020", "text" => "İyi günler, EGE TIP mezunu olup yakın zamanda Gutachtenla denklik alan var mı acaba?"],
                ["date" => "20.12.2020", "text" => "İyi akşamlar herkese, Denklik sürecinde eksik sayılan stajlar için almanyada ya da türkiyede yaptığımız gönüllü stajları saydırmamız mümkün mü?"],
                ["date" => "25.12.2020", "text" => "B1 ile orda işe başlayabilir miyiz peki denklik almadan ve B2’ye devam ederken?"],
                ["date" => "27.02.2021", "text" => "Almanya ve ingilterede denklik ile ilgili yardimci olacak arkadas varmi ?"],
                ["date" => "01.03.2021", "text" => "circulum sadece klinik branşlarımı ilğilendiriyor. denklik için temel bilimler istenmiyor mu?"],
                ["date" => "06.03.2021", "text" => "Arkadaşlar merhaba , Almanyada hastanede denklik için çalışırken herhangi bir maaş /burs alabiliyor muyuz?"],
                ["date" => "11.05.2021", "text" => "Denklik şartları hep böyle mi olacak yoksa değişebilir mi? Bir kaç yıl sonra bir anda değişir mi acaba?"],
                ["date" => "29.06.2021", "text" => "Bu şartı sağlayamayınca denklik için sınava girilmesi yeterli olur mu?"],
                ["date" => "31.07.2021", "text" => "Herkese merhaba, fspsiz işe başlanabilen eyaletler hangisi ? Hangi eyaletlerde fsp sınavı görece kolay ? Hangi eyaletlerde 2 senelik tecrübeyle bilirkişi ile denklik almak daha kolay ?"],
                ["date" => "11.09.2021", "text" => "Arkadaslar merhaba, hic almancası olmayan birinin günde 1-2 saat çalışma ile denklik alabilecek kadar almanca öğrenmesi kac ay surer ortalama? Sizin ne kadar aldı ya da?"],
                ["date" => "20.09.2021", "text" => "Herkese merhaba! Almanyada denklik almak icin universite puan ortalamanin herhangi bir etkesi var mi acaba?"],
                ["date" => "05.12.2021", "text" => "ben internüm.almanya'da gutachten ile denklik alan varsa bir soru sormak istiyorum.gutachten ile denklik alan var mı?"],
                ["date" => "24.12.2021", "text" => "Almanya da denklik işin uğraşıp başarısız olan bir doktorla görüşebilir miyim?"],
            ],
        ],
        "doktor_approbation" => [
            "title" => "Doktor: Approbation Sureci",
            "description" => "Hekimler icin Almanya da resmi calisma izni — eyalet basvurularl, evraklar, sureler",
            "icon" => "stethoscope",
            "questions" => [
                ["date" => "01.08.2018", "text" => "Suanda Almanyanin hangi eyaletlerinde Approbation surecinde PKT sinavi gecerli?"],
                ["date" => "19.02.2020", "text" => "Aslında şöyle bişey de geliyo aklıma. Diyelim kafamızda eyaleti belirledik. Direk BE/APPRO başvurusunu aynı anda o eyalete yapsak mümkün mü? Yani hospitation şart mı gerçekten?"],
                ["date" => "03.03.2020", "text" => "Thüringende BE /appro için bütün ders plan ve programının (curriculum) çevirisi istendiği doğru mu gerçekten?"],
                ["date" => "09.03.2020", "text" => "Dolandırıcılık diyemesem de bir çeşit umut tacirliği. Arkadaşın dediği gibi B2 fsp ve appro konusunda yardım edemeyeceklerine göre, ne faydası olacak?"],
                ["date" => "30.04.2020", "text" => "genelde B2 aldiktan sonra ilk yaomamiz gereken Appro bashvurusumu yoksa BE bashvurusu. Yoksa bunlar aynimi?"],
                ["date" => "07.05.2020", "text" => "Arkadaşlar approbation başvurusu için şuan sadece BW, SH, niedersachsen ve Hamburg Almanya dışı çeviri kabul ediyor gibi bir cevap geldi; farklı tecrübeleri olanlar var mı?"],
                ["date" => "08.05.2020", "text" => "Bamfa appro basvuru ucretini de ödetebiliyor muyuz acaba? Nasil bir yol izlenmeli?"],
                ["date" => "14.05.2020", "text" => "Arkadaşlar Approbation başvurusu için Zusage illa Assistenzarzt olarak mı alinmasi gerekiyor. Mesela bir Praxiste praktikant olarak Zusage alsak da iş görür mü? Bu konuda tecrübesi olan var mı acaba?"],
                ["date" => "16.05.2020", "text" => "Arkadaşlar berlin approbation birimine evraklarımı göndermiştim böyle bir e mail aldım birimden çok anlamadım ne yapmam gerektiğini bana açıklayabilirmisiniz?"],
                ["date" => "28.05.2020", "text" => "Arkadaşlar, Gutachter 1 ay dahiliye eksik sadece dedi bir uzman hocamıza sınavsız Approbation alabilmesi için, fakat BE ile yapılması lazım diyorlar; tecrübesi olan var mı?"],
                ["date" => "09.06.2020", "text" => "İyi günler, aramızda Sachsen da appro alan ya da şu an orda hospitasyon vs yapan birileri var mı?"],
                ["date" => "29.06.2020", "text" => "Hessende appro ve iş bulma konusunda son durumu bilen var mı? Yığılma var mı orada ?"],
                ["date" => "07.08.2020", "text" => "Bu nerde çıkıyor, Approbation a başvururken sağlık raporu alırken mu?"],
                ["date" => "19.08.2020", "text" => "Yani dışarıdan gelen doktora böyle bir imkan tanınmıyor diye bir şey yok, Almanya mezunları gibi biz de istediğimiz takdirde appro sonrası doktor arbeit yapabiliyoruz doğru mu anladım hocam ?"],
                ["date" => "26.08.2020", "text" => "Beruf erlaubnis ile çalıştığımız yer ile appro belgelerini verdiğimiz yer farklı olabilir mi ?"],
                ["date" => "02.11.2020", "text" => "4 5 sene mesleki tecrübesi olan kişiler sınavsız Approbation alabiliyor diye duydum doğruluğu var mıdır bu bilginin?"],
                ["date" => "24.11.2020", "text" => "bir de approbation filan hall etdikden sonra başka hangi ülkelerde koşulsuz çalışa bilirim?"],
                ["date" => "25.11.2020", "text" => "Arkadaşlar zusage hospitasyon veya oturum olmadan şuan sadece Bayern e mi Appro ( ilk adım olarak FSP)başvuruluyor? BDW ? Berlin?"],
                ["date" => "11.10.2018", "text" => "Dil kursu vizesini tavsiye etmiyorsunuz fakat is arama vizesi icin appro istiyor konsolosluk, dolayisiyla B2 almak da yeterli olmuyor bu konuda ne oneriyorsunuz?"],
                ["date" => "27.10.2018", "text" => "Approbation basvurusu kabul olursa fsp ye girmek icin sure sınırı var mi? Eğer reddedilirse KP için süre sınırı var mi?"],
                ["date" => "27.10.2018", "text" => "Dil sertifikam var. İş görüşmesi ve anlaşması yapmadan direkt approbation için başvurabiliyormuyuz? Yoksa başvurmadan önce iş kabulü almış olmamız mı gerekiyor?"],
                ["date" => "11.01.2021", "text" => "Arkadaşlar merhaba thüringen eyaletinde approbation alan var mı kolay mı zor mu biliyor musunuz?"],
                ["date" => "22.01.2021", "text" => "Arkadaşlar bu grupta Hamburg’da approbation sürecini başlatan var mı?"],
                ["date" => "10.02.2021", "text" => "Uyarı cezası almış olmak appro yada beruferlaubnis için sıkıntı yapar mı? Daha önce böyle bişey tecrübe etmiş olan var mı ?"],
                ["date" => "18.02.2021", "text" => "Almanya’da B2 sertifika olmadan berufserlaubnis yada approbation başvurusu oluyor mu ?"],
            ],
        ],
        "doktor_fsp" => [
            "title" => "Doktor: FSP / Fachsprachpruefung",
            "description" => "Tibbi Almanca sinavi (Telc med, FSP) hazirlik, denemeler ve kurslar",
            "icon" => "mic",
            "questions" => [
                ["date" => "09.03.2020", "text" => "Dolandırıcılık diyemesem de bir çeşit umut tacirliği. Arkadaşın dediği gibi B2 fsp ve appro konusunda yardım edemeyeceklerine göre, ne faydası olacak?"],
                ["date" => "19.03.2020", "text" => "FSP tip dili ile alakali bir sinav, abitur ile ne alakasi var?"],
                ["date" => "21.03.2020", "text" => "Arkadaslar Merhaba , NRW bana böyle bir mesaj geldi.Sizce FSP teste cevrilmiş olabılır mı ?"],
                ["date" => "29.04.2020", "text" => "arkadaslar, FSP icin ders materiallerinden ne tavsiye ederdiniz? parali online kurslar falan yapiyorsunuz yoksa kendiniz hazirlaniyorsunuz?"],
                ["date" => "06.05.2020", "text" => "Turkiye de fsp sinavi yapiliyormus . Almanya da gecerliligi var mi bunun ?"],
                ["date" => "12.05.2020", "text" => "Türkiyedeki Telc FSP ye girebilmek için öncesinde Almanyadaki geçerli üç eyaletten birinden is ayarlamis olmak gerekiyor mu?"],
                ["date" => "15.05.2020", "text" => "Bu konuda bilginiz varsa paylasabilir misiniz hocam? Mesela fsp veya kp kursu icin nasil Bamfdan ya da Agentür für Arbeitdan destek alabiliriz?"],
                ["date" => "28.05.2020", "text" => "ikinci sorum telc med c1 türkiyede almak mı mantıklı, almanyada almak mı?"],
                ["date" => "28.05.2020", "text" => "iki tipi var telc med b2-c1 ve telc med fsp. hangisine girmek lazım?"],
                ["date" => "31.05.2020", "text" => "Selamlar, DSH (Deutsche Sprachprüfung für den Hochschulzuganh) sınavını alırsak C1 ya da FSP'den muaf oluyor muyuz acaba bilen var mı?"],
                ["date" => "17.07.2020", "text" => "Grupta Telc-fsp-medizin sınavına Türkiye’de giren var mı acaba?"],
                ["date" => "29.07.2020", "text" => "izmirde telc fsp veya fsp için kurs, eğitim var mı? intern doktorum b2 seviyesindeyim ve temmuz 2021de mezun olana kadar fsp yi halletmek istiyorum önerisi olan var mı?"],
                ["date" => "25.08.2020", "text" => "fsp ve approbacion alana kadar göz bölümünde çalıştınız değilmi? Peki bu süre asistanliginizdan sayılıyormu? Bu sürede maaş aldınız mı?"],
                ["date" => "10.09.2020", "text" => "Özür dilerim...FSP ya da bir başka doktorları yakından ilgilendiren herhangi bir kurs tanıtımı...reklam sayılarak...yasak olarak biliyordum ama... yanlış mı biliyorum acaba?"],
                ["date" => "17.09.2020", "text" => "Fsp sinavi icin calismaya nasil baslayabilirim arkadaslar? Bir oneriniz var mi ?"],
                ["date" => "27.09.2020", "text" => "forum sitesinde hessen yakında telc fsp kabul etmeyecek gibi bi haber gördüm bilgisi olan var mı ?"],
                ["date" => "01.10.2020", "text" => "Herkese merhaba. Avrupa kültür merkezin'deki Telc fsp kursuna katılıp tecrübesini aktarabilen var mı aramızda?"],
                ["date" => "07.10.2020", "text" => "Goethe b2 sertifikası ile telc arasında ne gibi farklılıklar var acaba? fsp alınca 2side her eyalette geçerli oluyor mu?"],
                ["date" => "03.11.2020", "text" => "Başka bir eyalette alınan FSP ile Niedersachsen'de veya herhangi bir eyalette çalışılabiliyor mu? Bilen, deneyen var mı hiç?"],
                ["date" => "10.11.2020", "text" => "Dil için yada FSP sınavı için tusmer' den yararlanan var mı acaba?"],
                ["date" => "18.11.2020", "text" => "İyi akşamlar. Hamburgda önerdiğiniz, sınava girdiğiniz Telc FSP merkezi adı paylaşabilir misiniz?"],
                ["date" => "20.11.2020", "text" => "Sanırım siz FSP yi geçememişsiniz. Motivasyonunuz kırılmış:( Kaç defa denediniz? Nerde girdiniz?"],
                ["date" => "25.11.2020", "text" => "Arkadaşlar zusage hospitasyon veya oturum olmadan şuan sadece Bayern e mi Appro ( ilk adım olarak FSP)başvuruluyor? BDW ? Berlin?"],
                ["date" => "06.12.2020", "text" => "Iyi günler arkadaşlar.FSP sınavı için hangi landlar öneriyorsunuz?"],
                ["date" => "06.12.2020", "text" => "Arkadaşlar 1 sorum daha olacaktı Türkiyede FSP sinavları Almanyada geçerli mi?"],
            ],
        ],
        "doktor_hospitation_be" => [
            "title" => "Doktor: Hospitation ve Berufserlaubnis",
            "description" => "Hastane gozlem stajlari, gecici calisma izni (BE) ve sponsorlu kabul yollari",
            "icon" => "hospital",
            "questions" => [
                ["date" => "26.07.2018", "text" => "-Hospitasyon süreci hakkında bilgisi olan var mı? -Herkes bu süreçten geçiyor mu? -İntörn gibi çalıştırılıyormuş, ama mesela intörn kan almıyordu bizde?"],
                ["date" => "19.02.2020", "text" => "Aslında şöyle bişey de geliyo aklıma. Diyelim kafamızda eyaleti belirledik. Direk BE/APPRO başvurusunu aynı anda o eyalete yapsak mümkün mü? Yani hospitation şart mı gerçekten?"],
                ["date" => "03.03.2020", "text" => "Thüringende BE /appro için bütün ders plan ve programının (curriculum) çevirisi istendiği doğru mu gerçekten?"],
                ["date" => "28.03.2020", "text" => "BE için başvuruda, istenen tüm evraklar tamamlanmadan inceleme sürecini başlatmıyorlar mı?"],
                ["date" => "30.04.2020", "text" => "genelde B2 aldiktan sonra ilk yaomamiz gereken Appro bashvurusumu yoksa BE bashvurusu. Yoksa bunlar aynimi?"],
                ["date" => "05.05.2020", "text" => "Arkadaşlar aranızda daha önce hospitasyon vizesi alan kimse varsa bana dönüş yapabilir mi ?"],
                ["date" => "28.05.2020", "text" => "Arkadaşlar, Gutachter 1 ay dahiliye eksik sadece dedi bir uzman hocamıza sınavsız Approbation alabilmesi için, fakat BE ile yapılması lazım diyorlar; tecrübesi olan var mı?"],
                ["date" => "09.06.2020", "text" => "İyi günler, aramızda Sachsen da appro alan ya da şu an orda hospitasyon vs yapan birileri var mı?"],
                ["date" => "06.07.2020", "text" => "Arkadaşlar. Grupta psikiyatri Uzmanı olupta denklik alan veya BE ile iş bulan kimse oldu mu? Yoksa boşuna mı uğraşıyorum?"],
                ["date" => "28.07.2020", "text" => "Arkadaslar iyi günler... nrw'de son zamanlarda BE alan oldu mu? Çıkmasi nekadar sürüyor?"],
                ["date" => "06.08.2020", "text" => "Bu arada Vertag Be siz yapmıyor mu hastaneler, resmi olarak çalışma izni olmadığı için?"],
                ["date" => "14.09.2020", "text" => "Berufserlaubnis belirli tarihler arasi verilmiyor mu? Mesela ise baslama tarihinden itibaren?"],
                ["date" => "16.10.2020", "text" => "Afedersiniz bir sorum var, internette aramama rağmen cevap bulamadım acaba BE sürecinde maaş alınıyor mu ?"],
                ["date" => "16.10.2020", "text" => "BE ile veriliyor diye biliyordum. Verilmiyorsa 2 senelik geçici çalışma süresinde Almanya’da nasıl geçineceğiz ki?"],
                ["date" => "25.11.2020", "text" => "Arkadaşlar zusage hospitasyon veya oturum olmadan şuan sadece Bayern e mi Appro ( ilk adım olarak FSP)başvuruluyor? BDW ? Berlin?"],
                ["date" => "03.12.2020", "text" => "Bundespolizei hospitasyon davetiyle giris veriyor mu genelde ya da giris verdigi birisi var mi aramizda?"],
                ["date" => "02.02.2021", "text" => "? Ben de öğrenmek istiyorum. Hospitation ile Famulatur aynı mı ?"],
                ["date" => "18.02.2021", "text" => "Almanya’da B2 sertifika olmadan berufserlaubnis yada approbation başvurusu oluyor mu ?"],
                ["date" => "03.04.2021", "text" => "Merhaha arkadaşlar.. aranızda son sene içinde Bremende Berufserlaubnis alıp çalışmaya başlayan var mı ?"],
                ["date" => "19.04.2021", "text" => "Herkese iyi günler, Berlin’de suan Fsp siz Zusage alırsak geçici Berufserlaubnis alabiliyor muyuz, bilgisi olan var mı acaba ?"],
                ["date" => "29.04.2021", "text" => "30F ile başvurunca sizden de hospitasyon sonrasi ise alinma olasılığınızın olduğu bir yazı istediler mi?"],
                ["date" => "24.05.2021", "text" => "Benim dil kursum yok. Dogrudan b2, fsp ve hospi Einladung u ile hospitasyon basvurusu. Einladungda isi alma ihtimalim oldugu yaziyor. Hospitationsvertrag vermediler. Sansim var mi sizce?"],
                ["date" => "28.05.2021", "text" => "BW de BE ile çalışan var mı? Maaşlar cidden düşük mü dedikleri kadar?"],
                ["date" => "01.06.2021", "text" => "Hospitasyon için belli bir dil şartı var mı,yoksa kliniğe göre değişiyor mu?"],
                ["date" => "25.06.2021", "text" => "Hospitasyon için gidildiğinde de ülkeye girerken aşı şartı var mı?"],
            ],
        ],
        "doktor_kp_gutachten" => [
            "title" => "Doktor: KP / Gutachten / Denklik",
            "description" => "Kenntnispruefung, gutachten dosyalari ve diplomanin denklik sureci",
            "icon" => "file-text",
            "questions" => [
                ["date" => "12.05.2020", "text" => "Kp tarihi verilmeden başvuruyu çekerseniz yeni eyalet gutachter kabul eder belki? Belki?"],
                ["date" => "15.05.2020", "text" => "Bu konuda bilginiz varsa paylasabilir misiniz hocam? Mesela fsp veya kp kursu icin nasil Bamfdan ya da Agentür für Arbeitdan destek alabiliriz?"],
                ["date" => "28.06.2020", "text" => "Bir arkadaşımın 4 ay eksik çıktı ve KP ye girmeye karar verdi ücretli mi incelediler raporu?"],
                ["date" => "12.07.2020", "text" => "Cemal bey faydalı bir video olmuş, yeni işiniz icin tebrikler!! :) , Niedersachsenda Kp'nin zorluk derecesiyle ilgili bilginiz var mı acaba??"],
                ["date" => "26.07.2020", "text" => "Cemal hocam bilgilendirme için teşekkürler.Sadece gutachten simülasyonu aklıma takıldı. Yeni mezun olacak bir hekim için ne avantajı oluyor?"],
                ["date" => "06.10.2020", "text" => "Herkese merhaba son zamanlarda Gutachten ile BW den denkliğini alan oldu mu?"],
                ["date" => "02.11.2020", "text" => "Herkese merhaba..Dokuz Eylül Tıp mezunu olup gutachten yoluyla (sınavsız) Denklik alan var mı acaba???"],
                ["date" => "25.11.2020", "text" => "Gutachten için hazırlanan belgeler mi 312 sayfa tuttu ? Kp terchinde de belge sayfaları bu rakamları buluyor mu ?"],
                ["date" => "26.11.2020", "text" => "Çok teşekkür ederim Dilek hanım, tabiki sizin mesleki kariyerinizi bilmiyorum. Ben yeni mezun olacağım için kp daha mantıklı olarak görüyorum. Sizin tecrübeleriniz nelerdir ?"],
                ["date" => "26.11.2020", "text" => "Cevabınız için teşekkür ederim. Gutachten yolu için dediniz değil mi ?"],
                ["date" => "27.10.2018", "text" => "Approbation basvurusu kabul olursa fsp ye girmek icin sure sınırı var mi? Eğer reddedilirse KP için süre sınırı var mi?"],
                ["date" => "06.03.2021", "text" => "Arkadaşlar sınavsız aprobasyon için bir eyalet seçip ordan dil belgesi olmadan gutachten süreci başlatılabilir mi?"],
                ["date" => "10.08.2021", "text" => "Iyi günler, Cerrahpasa mezunlarindan Almanyadan Gleichwertigkeit - Gutachten ile Approbation alan var mi? 4 cu sinif ve sonrasinda ders saatlerinde eksiklikler var mi?"],
                ["date" => "23.08.2021", "text" => "4 ay Almanya'da cerrahi PJ yapmak Gutachten sonucunu nasıl etkiler? Kesin olarak olumlu sonuçlanır diyebilir miyiz?"],
                ["date" => "11.09.2021", "text" => "Sağ olun hocam. Staj bırakarak okulu uzatıp Almanya’da Famulatur ayarlayarak onu Gutachten sürecinde kullanmak mümkün mü peki? Bir bilginiz var mı?"],
                ["date" => "12.10.2021", "text" => "Sachsen eyaletinde çalışan var mı?FSP ve KP sınavlarının zorluğu nasıl?Aue şehrinde bulunan oldu mu?Veya Chemnitz?"],
                ["date" => "01.11.2021", "text" => "Herkese merhabalar,Sachsen Anhalt ta Gutachten yolu ile Pozitif cevap alan varmı veya bildiyiniz varsa lütfen paylaşırsanız??"],
                ["date" => "23.11.2021", "text" => "Privat gutachten seçebileceğimiz bir eyalet var mı? Yoksa tüm gutachtenler Bonn’a mı gidiyor?"],
                ["date" => "05.12.2021", "text" => "ben internüm.almanya'da gutachten ile denklik alan varsa bir soru sormak istiyorum.gutachten ile denklik alan var mı?"],
                ["date" => "06.03.2022", "text" => "kendi içinizde çekiliyorsunuz beyefendi, Gutachten zaten yeterli görürse sınavsız Approbation alınıyor, sizin vaadettiğiniz nedir tam olarak?"],
                ["date" => "06.03.2022", "text" => "sorun zaten Gutachten yetersiz görürse Kenntnisprüfung yolu olmadan Approbation alacaksınız?"],
                ["date" => "19.03.2022", "text" => "Mərhəba, Gutachten mümkündü almnayada ve bunun için neler gerek ?"],
                ["date" => "19.03.2022", "text" => "Olumsuz Gutachten sonucuna itirazda hukuki destek alabileceğimiz bir avukat önerebilir misiniz arkadaşlar?"],
                ["date" => "25.03.2022", "text" => "İşyeri hekimliği kursuna gitmeden gutachten ile denklik mümkün değil mi?"],
                ["date" => "14.05.2022", "text" => "Arkadaşlar Bremen KP protokollerini bulabileceğim bir yer var mi?"],
            ],
        ],
        "doktor_fachgebiet" => [
            "title" => "Doktor: Branş / Fachgebiet",
            "description" => "Branş seçimi, asistanlık, stellenangebot, şehir/eyalet bazlı tıp iş imkanları",
            "icon" => "activity",
            "questions" => [
                ["date" => "21.02.2020", "text" => "Aile hekimliği çekirdek TUKMOS gibi bir programı almanca ya çevirten kimse var mı acaba?"],
                ["date" => "02.03.2020", "text" => "Denklik almak için internlikte bizim 2 ay cerrahi almamız sorun olduğu Almanya'da pjlerin bunu 4 ay yaptığını yazmışsınız, benim bu yaptığım toplam 2 aylık stajlar bunu tamamlar mi?"],
                ["date" => "30.03.2020", "text" => "Teşekkür ederim. Peki başka bir bölüm yapmak istesem Turkiyedeki aile hekimliği asistanlığım boyunca aldığım rotasyonlar sayılıyor mu? Mesela orada dermatoloji yapmak istesem faydası olur mu?"],
                ["date" => "20.05.2020", "text" => "Almanya’da Dr. Adnan isminde anestezi uzmanı bir doktor bey tanıyan var mı acaba, son yıllarda Tr’den gelen. Tanıyan varsa özelden mesajlaşabilir miyiz?"],
                ["date" => "21.05.2020", "text" => "Trden uzman olup ; türkiyedeki kurumundan aldigi asistan karnesi yada ilgili uzmanlik derneklerinin onayli uzmanlik egitim programlari gibi belgeleri kullanabilen var mi ?"],
                ["date" => "18.06.2020", "text" => "İyi akşamlar, almanyada çocuk ve ergen psikiyatrisinde asistan ya da uzman olarak çalışan var mı? Birkaç sorum olacaktı?"],
                ["date" => "06.07.2020", "text" => "Arkadaşlar. Grupta psikiyatri Uzmanı olupta denklik alan veya BE ile iş bulan kimse oldu mu? Yoksa boşuna mı uğraşıyorum?"],
                ["date" => "13.07.2020", "text" => "Arkadaşlar türkiyede 18 ay genel cerrahi tecrübem var. Approbationa başvuracağım, bu çalıştığım süreyi nasıl belgelemeliyim sizce? Elinde şablon olan var mı?"],
                ["date" => "28.09.2020", "text" => "Pj şartları nedir acaba? 4 ay dahiliye + 4 ay cerrahi + 4 ay elektif mi olması gerekiyor? Cerrahi genel cerrahi değil mi ayrıca?"],
                ["date" => "29.09.2020", "text" => "Örneğin PJ de 3 ay cerrahi bransim var, dönem 3ün yazında yaptığım 1 aylık cerrahi hospitasyonu saydırıp 4 aya tamamlayabilir miyim? Yoksa 4 ayın tamamı internlikte mi olmalı?"],
                ["date" => "21.10.2020", "text" => "Genel cerrahide 4 ay asistanlık ile intörnlükteki cerrahi eksiği kapatıp KPye gerek kalmadan denklik alınabilir mi veya alan var mı?"],
                ["date" => "06.11.2020", "text" => "Arkadaşlar merhaba Almanya’da radyoloji uzmanlarının durumu ile ilgili bilgisi olan var mı? Almancaya yeni başlayacaklar için online dil kursu önerileriniz var mu?"],
                ["date" => "05.12.2020", "text" => "Hakan Radyoloji uzmanı olarak iş bulmak sence diğer branşlara göre daha zor mu? Bilginiz var mı?"],
                ["date" => "01.03.2021", "text" => "Arkadaşlar örnek pediatri logbuch ihtiyacımız var Nrw için , yardımcı olabilen olur mu?"],
                ["date" => "09.07.2021", "text" => "Almanya'da \"Ben asistan doktor olmaktan memnunum, uzmanlığımı bitirmeden böyle devam edeceğim\" demek gibi bir şey oluyor mu? İlla bitirmek lazım mı asistanlığı?"],
                ["date" => "23.07.2021", "text" => "Diş hekimliğinde uzmanlık karnemde cerrahi rotasyonu sayfasını su an anabilim dalı başkanı olan hocaya mı yoksa ben rotasyondayken bölüm başkanı olan kişiye mi imzalatmam gerekir?"],
                ["date" => "06.08.2021", "text" => "Cerrahi stajları eksik çıkabiliyormuş fakat dahiliye stajları için de bu geçerli mi? Secmelilerde göğüs hastalıkları, göz, kbb, anestezi içinde göğüs seçmek daha mı iyi?"],
                ["date" => "06.08.2021", "text" => "Mezuniyet sonrası cerrahi hospitasyon yapsak sayılır mı yoksa mezuniyet öncesi olması şart mı gutachter sayılması için?"],
                ["date" => "23.08.2021", "text" => "4 ay Almanya'da cerrahi PJ yapmak Gutachten sonucunu nasıl etkiler? Kesin olarak olumlu sonuçlanır diyebilir miyiz?"],
                ["date" => "29.08.2021", "text" => "Cocuk ve ergen psikiyatri kitabı pdf olarak arıyorum da, yardımcı olabilecek arkadaşım var mıdır?"],
                ["date" => "07.09.2021", "text" => "Arkadaşlar merhabalar pediatri sba asistanlığının birinci yılındayım . Bende geçmek istiyorum fakat süreç hakkında pek bilgim yok yardımcı olabilir misiniz rica etsem ?"],
                ["date" => "17.10.2021", "text" => "Şimdi Hakan Bahadır hocamın canlı yayınında izliyorum, kadın doğumu cerrahi branştan saymadıkları doğru mu? İntörnlükte cerrahim eksik ama 2 yıl kadın doğum asistanlığı yaptım. Bunu saydıramaz mıyım?"],
                ["date" => "26.10.2021", "text" => "Almanyada psikosomatik alanında asistan veya uzman kişi var mı grupta?"],
                ["date" => "12.12.2021", "text" => "Anestezi uzmanıyım. Almanyaya gitsem orda anestezi uzmanı olarak çalışabilir miyim? Ayrıca Almanca öğrenmem ve sınavını geçmem şart mı? Ingilizcenin yeterli olduğu eyaleti var mı?"],
                ["date" => "14.12.2021", "text" => "currculum hazırlarken yabanci dil,türk dili,inkilap tarihi,bilgisayar gibi dersleri de belirtmemize gerek var mı?bir de 4 aylık cerrahi staja hangi branşlar dahil bilgisi olan var mı?"],
            ],
        ],
        "para" => [
            "title" => "Maliyet ve Para Transferi",
            "description" => "Bloke hesap miktari, sigorta ucreti, TR-DE para transferi ve harcama",
            "icon" => "wallet",
            "questions" => [
                ["date" => "13.04.2020", "text" => "Almanya’da intörnlük yaparken oradaki ücretlendirmeye göre mi para kazanacağız? Yolda TR’nin hibesiyle mi yapacağız intörnlüğü bilginiz var mı arkadaşlar?"],
                ["date" => "29.05.2020", "text" => "Bence temel soru extra para verince kanaat notu daha pozitif oluyor mu?"],
                ["date" => "01.03.2021", "text" => "Herhangi bir danismanlik sirketi ile baglantiniz var mi hocam? Veya bu isi maddi bir kar saglama amaci ile mi yapmak istiyorsunuz yoksa amaciniz tamamen insanlara yardim etmek mi?"],
                ["date" => "04.12.2021", "text" => "Selamlar ,Fintibaya para gönderirken swift te banka şube adı soruluyor ,ama fintibada şube olmadığı için bu kısmı dolduramıyorum.Bu sorunu yaşayan oldu mu ?"],
                ["date" => "24.03.2019", "text" => "Almancası iyi olmayan biri için süreç sonuna kadar kaç ay ve kaç tl ücret gerekli??"],
                ["date" => "29.01.2022", "text" => "bi şeyler yapmaya çalışan adama karışmayın bari adam sizden para mı istedi, kăr amacı mı gűttü?"],
                ["date" => "16.05.2022", "text" => "Cevabınız için çok teşekkür ederim. Acaba meslektaşlarımız sadece seçtiği eyalete gidebilmek için mi bir kaç bin Euro almanca çeviri ücreti ödüyor?"],
                ["date" => "08.06.2022", "text" => "Almanyada hangi bankadan hesap açmak Türkiye’den para transferi açısından daha avantajlı?"],
                ["date" => "31.08.2022", "text" => "Almanyada bloke hesaptan para çekmek için başka hesap açmak gerekiyor ya türkiyeden açabilir miyiz o hesabı?"],
                ["date" => "27.09.2022", "text" => "Almanyadan türkiyeye para göndermek için hangi uygulamayı önerirsiniz?"],
                ["date" => "12.10.2022", "text" => "Bu ücret gutachten için olmalı, BE için o kadar yüksek bir ücret yok 200 euro falan olması lazım. Siz gutachtene başvurmayacaksınız öyle mi? KP'yi mi seçeceksiniz? Eyalet neydi?"],
                ["date" => "03.11.2022", "text" => "Sayfa başı kaç euro talep ettiler Figen hanım? Ve kaç günde teslim edecekler?"],
                ["date" => "25.11.2022", "text" => "Arkadaşlar Türkiyeden Almanyaya para transferi için indirimli transfergo veya transferwise gibi uygulamalrdan indirim kodunuz var mı?"],
                ["date" => "25.03.2023", "text" => "Arkadaşlar selam Berufserlaubnis olmadan praktikum ya da hospitation ile para kazanabiliyor muyuz? Bu durumu Ausländerbehörde ile mı görüşmemiz lazım?"],
                ["date" => "26.08.2019", "text" => "Abrobasyon sürecinde hospitasyon yaparken para kazanabilme imkanı var mı?"],
                ["date" => "02.06.2023", "text" => "Iyi akşamlar. Dil kursu vizesi için istenen evraklarda yer alan saglik sigortası için, 30.000 euro teminatlı seyahat sağlık sigortaları yeterli oluyor mu?"],
                ["date" => "26.06.2023", "text" => "Bir de kişi başı aylık 1027 euro bloke hesaba aktaracağım. Eşim ve kendim için bı par. 4 ve 11 yaşında 2 çocuğum var, onlar içinde bloke heaba para aktarmam gerekirmi, miktarı bilen varmı?"],
                ["date" => "25.12.2023", "text" => "evi uzaktan tutmak zorunda kalirsak para gonderme konusunda direk ev sahibi yerine emlakci uzerinden ilerleyerek guvenilirlik saglayamaz miyiz?"],
                ["date" => "31.12.2023", "text" => "Arkadaşlar Goethe nin intensive dil kurslarına giden oldu mu? Yazın mezuniyetten sonra atamaya kadar gitmeyi düşünüyorum 3 haftalık kurs 1200 euro sizce değer mi?"],
                ["date" => "02.03.2024", "text" => "Vize görüşmesinde 75 Euro ücret yazıyor belgede, 75 Euro yeterli mi acaba ek başka bir ücret çıkıyor mu?"],
                ["date" => "28.03.2024", "text" => "Sayın hocalarım, danışmanlık hizmetlerine binlerce Euro ödemeye gerek var mıdır? Ya da önereceğiniz bir kurum var mı?"],
                ["date" => "30.09.2019", "text" => "Olası vize çıkmaması durumunda 4-5 ay daha Dil Eğitimi alıp yine başvuracağım. Bloke hesap açık kaldığı müddetçe sürekli 5 Euro kesecek mi?"],
                ["date" => "25.06.2024", "text" => "çalışan arkadaşlar dil okuluna gitmek için ücretsiz izine mi ayrılıyorsunuz yoksa para biriktirip istifa mı ediyorsunuz?"],
                ["date" => "05.11.2024", "text" => "Fahri konsolosluk evrak basına 29 euro istiyor.. konsolosluk ücreti nasıl bilen varmı acaba ?"],
                ["date" => "07.03.2025", "text" => "Arkadaşlar merhaba. Ben Postbank Berlin e bir Iban a para yatıracağım Euro olarak. Türkiye’den bunu en az komisyonla nasıl yollayabilirim?"],
            ],
        ],
        "sehir" => [
            "title" => "Sehir Secimi ve Yerel Surec",
            "description" => "Berlin, Hamburg, Frankfurt, Bayern, BW vb. eyalet/sehir bazli sorular",
            "icon" => "map-pin",
            "questions" => [
                ["date" => "07.05.2020", "text" => "Arkadaşlar approbation başvurusu için şuan sadece BW, SH, niedersachsen ve Hamburg Almanya dışı çeviri kabul ediyor gibi bir cevap geldi; farklı tecrübeleri olanlar var mı?"],
                ["date" => "12.05.2020", "text" => "Herkese merhaba , Hamburg’da asistanlık veya staj yapan birileri var mı acaba iletişime geçmek isterim?"],
                ["date" => "16.05.2020", "text" => "Arkadaşlar berlin approbation birimine evraklarımı göndermiştim böyle bir e mail aldım birimden çok anlamadım ne yapmam gerektiğini bana açıklayabilirmisiniz?"],
                ["date" => "09.08.2020", "text" => "Hamburg diğer eyaletlere göre iş bulma ve kabul açısından nasıl?"],
                ["date" => "25.11.2020", "text" => "Arkadaşlar zusage hospitasyon veya oturum olmadan şuan sadece Bayern e mi Appro ( ilk adım olarak FSP)başvuruluyor? BDW ? Berlin?"],
                ["date" => "22.01.2021", "text" => "Arkadaşlar bu grupta Hamburg’da approbation sürecini başlatan var mı?"],
                ["date" => "10.02.2021", "text" => "İyi akşamlar, Berlin’de şu an yüzyüze sınıf ortamında eğitim veren bir Almanca kursu var mı?"],
                ["date" => "19.04.2021", "text" => "Herkese iyi günler, Berlin’de suan Fsp siz Zusage alırsak geçici Berufserlaubnis alabiliyor muyuz, bilgisi olan var mı acaba ?"],
                ["date" => "19.07.2021", "text" => "Arkadaşlar Hamburg’da bildiğiniz uygun fiyatlı çevirmen var mı?"],
                ["date" => "11.12.2021", "text" => "Iyi günler. Aramızda Berlin'de Kinderarzt olarak görev yapan var mı acaba?"],
                ["date" => "23.01.2022", "text" => "Herkese iyi akşamlar dil kursu için frankfurt veya çevresinde olan varsa özelden yazabilir mi ?"],
                ["date" => "01.02.2022", "text" => "Arkadaslar alman konsoloslugunda ve ya berlin buyukelciliginde apostil islemleri oluyor mu? Yoksa sadece Turkiyede mi oluyor acaba ?"],
                ["date" => "05.02.2022", "text" => "Herkese merhaba frankfurt veya çevresinde dil kursu yapan var mı? Varsa özelden yazabilir mi?"],
                ["date" => "11.03.2022", "text" => "Berlin ya da Bayern’de konaklama yeri sağlayan ya da yurtla anlaşmalı önerebileceğiniz fsp kursu var mı ?"],
                ["date" => "11.04.2022", "text" => "Frankfurt civarında uygun bir dil kursu arıyorum.Bana acil kayıt belgesi lazım.Yardımcı olabilir misiniz?"],
                ["date" => "28.06.2022", "text" => "Bremen - Hamburg - Hannover ( Kuzey Almanya) için bir grup varmı ?"],
                ["date" => "23.08.2022", "text" => "Herkese merhaba, Freiburg'ta B2 ve FSP için kurs önerebilecek biri varsa sevinirim?"],
                ["date" => "13.09.2022", "text" => "Arkadaşlar merhaba , Stuttgart çevresi uygun çevirmen önerebilir misiniz ?"],
                ["date" => "20.10.2022", "text" => "Iyi akşamlar,Hamburg için grup varsa ekleyebilir misiniz beni ?"],
                ["date" => "04.11.2022", "text" => "Arkadaşlar Berlin de Gutachten süreci için belgeler Bohn a mi gönderiliyor?"],
                ["date" => "07.11.2022", "text" => "Arkadaşlar Merhaba Freiburg için 5-30 haziran tarihleri arasında kalacak bir yurt veya kiralık bir daire arıyorum. Bildiğiniz bir yer varsa öneride bulanabilir misiniz?"],
                ["date" => "08.11.2022", "text" => "Arkadaşlar merhaba. Berlin eyaleti denklik işlemleri için gerekli evrak listesini paylaşabilirmisiniz?"],
                ["date" => "22.01.2023", "text" => "Günaydın, Frankfurt am Main’de önerdiğiniz dil okulu var mı?"],
                ["date" => "15.07.2023", "text" => "Arkadaşlar 1 ay hospitation için Niedersachsen-Stade ye gideceğim. Hamburg-Stade arasında ailece kalabileceğimiz bir yer arıyorum. Yardımcı olabilecek olan var mı?"],
                ["date" => "09.08.2023", "text" => "Arkadaşlar Hamburg için bir grup var mıydı acaba ben bulamadım?"],
            ],
        ],
        "sigorta" => [
            "title" => "Saglik Sigortasi",
            "description" => "TK, AOK, Krankenversicherung, ozel/devlet sigorta secimleri",
            "icon" => "heart-pulse",
            "questions" => [
                ["date" => "30.04.2020", "text" => "Ama sigorta vs cok dezavantajli degil mi? Yüksek maas verilsede gider ona göre cok yüksek? Yani bide isvicre almancasi cok tuhaf bir aksanli yani direk olaraya tavsiye ederken sadece finansal mi?"],
                ["date" => "10.08.2020", "text" => "Herkese merhaba. Mavi kart calisma vizesi basvurusunda en az 15 gunluk seyahat saglik gerekiyormus. Alman konsoloslugu hangi sigorta firmalarini kabul ediyor?"],
                ["date" => "13.07.2021", "text" => "Iyi akşamlar , vize için istenen sigorta hakkında bilgisi olan var mı ??"],
                ["date" => "31.08.2021", "text" => "Yaşımdan ötürü at11'e başvuramıyorum. Zorunlu devlet sigortası da yaptırmaıyorum. İş/oturum izni almak için önerdiğiniz özel bir sigorta şirketi var mıdır?"],
                ["date" => "21.10.2021", "text" => "Tam olarak anlayamadım...ulusal vize için almanyadan mı bir sigorta yaptırmak gerekiyor. ?"],
                ["date" => "04.11.2021", "text" => "Arkadaşlar merhabalar, Almanya'da sigorta işlemlerini başlatırken Türkiyeden sigortalı olduğumuz süreyi gösteren bir belge istenildi mi kimseden ? E devletten SGK hizmet dökümü yeterli olur mu ?"],
                ["date" => "09.08.2022", "text" => "Diğer belgeleri Almanca mı verdiniz acaba? adli sicil kaydı, sigorta vs?"],
                ["date" => "17.01.2023", "text" => "Iyi akşamlar, 30 f vize için sigorta yaptırırken hospitasyon olduğuna dair ekstra bir ibareye gerek olur mu?"],
                ["date" => "01.08.2019", "text" => "Fintiba plus açtığımız taktirde extradan sigorta yaptırmaya gerek yok değil mi?"],
                ["date" => "29.02.2024", "text" => "4 aylık dil kursu için 6 aylık mı sigorta yapmalıyım bloke hesabım 6 ay olacak?"],
                ["date" => "25.04.2024", "text" => "Expatrio'dan sigorta yaptırdığımız halde ekstradan SGK A/T 11 istenmiyor, değil mi?"],
                ["date" => "27.04.2024", "text" => "Expatrio'dan sigorta yaptırdığımız halde ekstradan SGK A/T 11 isteniyor mu?"],
                ["date" => "23.09.2024", "text" => "İyi akşamlar, Türkiye ehliyeti üstüne araba alan oldu mu? Sigorta veya kayıt yaparken sorun oluyor mu?"],
                ["date" => "24.09.2024", "text" => "Herkese merhabalar , Almanya’da Anmeldungumuz olduğunda göz muayenesi olabiliyor muyuz? Hausarzt yönlendiriyor mu veya sigorta kapsamında oluyor mu bilen var mı acaba?"],
                ["date" => "10.06.2025", "text" => "Birçok şeyi kapsayan bir sigorta yaptırmak istesem ne yaptırmalıyım? Hospitasyon yaparken AOK'tan sigorta yaptırabiliyor muyum?"],
                ["date" => "02.01.2020", "text" => "Günaydın arkadaşlar. Dil kursu için Almanya ya gelecekler sigortasını Türkiye deki sigorta şirketlerinde yaptırsa Almanya da sorun yaşar mı bi hastalık durumunda?"],
                ["date" => "17.08.2022", "text" => "Sağlık sigortasını Türkiye de mi yaptırmak mantıklı yoksa Almanya da mı? Türkiye'de yaptırdığımız sigorta uzun süreli kalacaklar için sorun olur mu?"],
                ["date" => "05.06.2023", "text" => "fintiba'ya kayıt yaparken DAK sağlık sigortasını onaylamamı zorunlu tuttu. AOK sigortası yaptırmayı düşünüyordum ve şu an fintiba'nın DAK yaptığından da emin değilim. Benzer bir süreç yaşayan var mı?"],
                ["date" => "21.11.2023", "text" => "Almanya'da olan arkadaşlar, at11i onaylayıp sigorta kartı veren bir sigorta şirketi var mı?"],
                ["date" => "28.09.2022", "text" => "AT11 belgesi 25 yaşına kadar veriliyor, 25 yaşından sonra nereden yaptırabiliriz önerdiğiniz sigorta şirketi var mı ?"],
                ["date" => "01.10.2022", "text" => "Dr Walker , Expatio falan gereğinden fazla ücret çıkarıyor Allianz sigorta ile daha ucuz halledebiliyoruz ? Alllianz ile yaptıran arkadaşlar varöı?"],
                ["date" => "15.07.2024", "text" => "oturum uzatmak için Krankenversicherung isteniyor en uygun AOK mı yapıyor deneyimi olan yazabilir mi?"],
                ["date" => "08.10.2025", "text" => "İzninizle bişey sormak istiyorum, Çocuğum Almanya'da öğrenci ve sigorta olarak AT11 belgesi var, bu belge ile yarı zamanlı bir işte ekstra sigorta yapmadan çalışabilir mi?"],
                ["date" => "19.05.2023", "text" => "AT11 belgesi olan aok kayıt olan kronik rahatsızlığı olan arkadaşım Almanyada ilaç yazdırmaya gittiğinde 40 euro ödemiş ,parayı geri almak için Aok mı SGK ile mi iletişime geçmesi gerekiyor?"],
                ["date" => "03.08.2022", "text" => "Ama bana direk kabul verilmiş ve C1 sertifikasi ile sigorta belgesini gönder diyor. Benim dil sertifikam hiç yok. Ben şartlı kabul istiyorum başına böyle birşey gelen yokmu?"],
            ],
        ],
        "anmeldung" => [
            "title" => "Anmeldung ve Sehir Kaydi",
            "description" => "Burgeramt randevu, Wohnungsgeberbestatigung, SteuerID surecleri",
            "icon" => "clipboard-check",
            "questions" => [
                ["date" => "01.12.2021", "text" => "Iyi aksamlar arkadaslar.Hessende BE almak icin Zusage ve Anmeldung mutlakdirmi??"],
                ["date" => "20.01.2022", "text" => "Arkadaslar yeni geldim Berline . Ctesi . Burada anmeldung yapmak icin bi sure sinirlamasi varmi?"],
                ["date" => "13.04.2022", "text" => "Bayernden FSP randevusu almak için sadece B2 yeterli mi? Approbation başvurusu, anmeldung, zusage gibi seyler zorunlu mu?"],
                ["date" => "13.01.2023", "text" => "bw de fsp termini icin zusage veya orada anmeldung sarti var mi?"],
                ["date" => "18.01.2023", "text" => "İyi günler arkadaşlar, Schengenle hospitasyona gidip, sonrasında Anmeldung istenmeyen dil kursuna başvurup kabul alırsam, vizemi uzatabilir miyim? Lütfen bilen arkadaşlar yardımcı olabilir mi?"],
                ["date" => "31.07.2023", "text" => "selamlar sperrkonto ile 49euroluk bilet alınabiiyor mu? anmeldung için vize çıktıktan sonra almanyaya gitmeden herhangi bir yere başvuruluyor mu ya da randevu alınmalı mı?"],
                ["date" => "08.06.2024", "text" => "hospitasyon yapmadan, anmeldung ve iş teklifi olmadan başvurabileceğimiz eyalet var mı?"],
                ["date" => "09.06.2024", "text" => "zusage anmeldung ve hospi olmadan sadece iş başvurularına red ile appro ya başvuruluyor mu?"],
                ["date" => "16.02.2025", "text" => "Arkadaşlar 2 ay famulatur yapacağım yeşil pasaportla. Bir miktar ödeme yapacaklar. Vize anmeldung vs olmadan hesap açamam değil mi?"],
                ["date" => "09.11.2023", "text" => "anmeldung için dortmund yabancılar dairesine randevu almadan direkt gitmek oluyor mu ? bi bilginiz var mı ?"],
                ["date" => "30.11.2022", "text" => "2 haftadır almanyadayım Ev bulamadığım için Anmeldung yapamadım bir sorun olur mu ?"],
                ["date" => "30.12.2022", "text" => "Arkadaşlar merhaba, Berlin'de bir yerde kalıyorum ve dil kursum da Berlin'de ama Anmeldung'u Brandenburg'dan yaptırsam ileride bir sıkıntı olur mu?"],
                ["date" => "15.06.2023", "text" => "Selamlarr, almanyaya geldikten sonra henuz Anmeldung yapmadan expatrioda bloke hesabi aktive edebiliyor muyuz?"],
                ["date" => "16.07.2023", "text" => "Almanyada öğrenciyim,Şehir değişikliği yapıldığında belediyeye gidip yeni adrese kayıt anmeldung için kaç gün süre var ? Cezası var mı?"],
                ["date" => "28.03.2024", "text" => "Hat jemand Informationen zum Sprachniveau für die Anmeldung zum Dualen Studium?"],
                ["date" => "11.10.2021", "text" => "Arkadaşlar merhaba, Almanyaya geldim yenile, Anmeldung olayını çözmeye çalışıyorum. Ben yaklaşık 1 ay otelde kalacağım, bu sürede de kalıcı yer işini çözeceğim. Yalnız, Almanya'da 6 aydan fazla kalacağım için, geldikten sonra iki hafta içerisinde Anmeldung yaptırmak gerekiyormuş."],
                ["date" => "03.03.2022", "text" => "SH’de Anmeldung ve Telc-FSP sonucuyla Approbation başvurusu yapınca Gutachter’den olumlu cevap gelirse Approbation belgesini alabilmemiz için mutlaka iş bulmamız mı gerekiyor? İş bulmadan Approbation belgesini vermiyorlar mı?"],
                ["date" => "04.09.2023", "text" => "İyi günler herkese, kasım ayında başlayacak altı aylık erasmus kabulüm var ancak ulusal vize sırası gelmedi. Şu an yeşil pasaport ile Almanyadayım. Anmeldung yapıp buradan ulusal vizeye/oturuma başvurabiliyor muyuz?"],
                ["date" => "28.12.2023", "text" => "Vize uzatma için ikametgahımızın olduğu yerdeki yabancılar dairesine mi gitmeliyiz? Ben şimdi berlindeyim. Anmeldung Berlinde. Frankfurttaki dil kursuna kayıt olup vize uzatmak için anmeldungu Frankfurt tarafına alıp oranın yabancılar dairesine mi başvurmalıyım?"],
                ["date" => "20.02.2024", "text" => "Iyi gunler Expatriodan sperrkonto acmistim 7 aylik .almanyada sparkasse ya da commerzbankta banka hesabi acarken Ausländerbehörde'den gecici oturum belgesi istenen oldu mu acaba ? Rathaustan anmeldung ile banka hesabi actiramiyor muyuz ?"],
                ["date" => "17.07.2024", "text" => "Arkadaşlar merhaba, Ben ilk etapta ev bulamam airbnb tutarım diyodum ama bu sefer de Anmeldung sorun oluyormuş. Öyle olunca bloke hesap aktifleyemem banka hesabı açamam diye düşündüm. Böyle sıkıntı yaşayan oldu mu? Anmeldung yapamayan? N’aptınız böyle bi durumda?"],
                ["date" => "13.12.2024", "text" => "Meldebestätigung für die Anmeldung belgesi ile 'Beleg des dauerhaften Wohnsitzes' maddesini sağlamış oluyor muyum yoksa üçüncüyü mü işaretlemem gerekiyor? 3 haftalık hospitasyon belgem de var hangisi daha etkili olur sizce?"],
                ["date" => "27.03.2025", "text" => "Arkadaşlar merhaba bi sorum vardı. Ben dil kursu vizesiyle geldim 6 aylık b2 bitti. c1 kursı için başka eyaletten kursa gitsem, online katılıcam Anmeldung değiştirmeden , sıkıntı oluyor mu acaba. Bilgisi olan var mı. Kurs değişikliğini bildirmek gerekiyor mu?"],
                ["date" => "24.05.2025", "text" => "Arkadaşlar merhabalar, 30 mayısta greifswalde gideceğim Anmeldung yapmak istiyorum, süresi en fazla 15 gün içinde yapmak gerekiyormuş, ama şu an termin almaya çalıştığımda 18 haziranda en erken tarih veriyor. Nasıl bir yol izleyebilirim?"],
                ["date" => "20.07.2025", "text" => "Merhana ben FSPimi nrwde gectim 1ay once, ve burda BE icin zusage lazim, nrwde de Approlu doktor aradiklari icin, is bulmak cok zor, burda BE almadan baska bir bundeslandda anmelden olsam ve ya is bulsam evraklarimi ceke bilirmiyim?"],
            ],
        ],
        "yurt" => [
            "title" => "Konaklama ve Yurt",
            "description" => "WG, Wohnheim, kira sozlesmesi, kaution ve garantor sorulari",
            "icon" => "home",
            "questions" => [
                ["date" => "06.01.2022", "text" => "Herkese iyi aksamlar. Schengenle almanyada kira sozlesmesi yapabiliyor muyuz? Blaue Karte Ulusal vizem Martta baslayacak. Subatta gidip ev kontratini yapabilir miyim?"],
                ["date" => "29.05.2022", "text" => "Münih'te 07-06 dan 01-07 ye kadar kalacağım, tıp stajı ayarladım. WG arıyorum bu aralıkta benim gibi kiralık yer arayan yada kiralayan var mı ?"],
                ["date" => "30.06.2022", "text" => "Uc ay dil kursuna gittigimde Almanyada en ucuz konaklama sekli nasil olur?WG olarak yer bulsam vize de sorun olur mu?"],
                ["date" => "13.07.2022", "text" => "Almanyada da sahibinden gibi bir site var mı? Wg vs nasıl bulacağız orada? Ya da başka fikri olan?"],
                ["date" => "07.11.2022", "text" => "Arkadaşlar Merhaba Freiburg için 5-30 haziran tarihleri arasında kalacak bir yurt veya kiralık bir daire arıyorum. Bildiğiniz bir yer varsa öneride bulanabilir misiniz?"],
                ["date" => "15.05.2023", "text" => "ve üniversitem wdomsta olmazsa beni yurt dışı kabul etmiyo mu acaba?"],
                ["date" => "21.09.2023", "text" => "Herkese merhaba. Munich'de Famulatur'um icin kalacak yer ariyorum da, bildiginiz veya onerdiginiz bir yurt/host aile var mi?"],
                ["date" => "08.12.2023", "text" => "Arkadaşlar iyi akşamlar önerebileceğiniz kira hukuk avukatı var mı ?"],
                ["date" => "17.06.2025", "text" => "Neuruppinde kalacak yer arıyorum, bildiginiz hostel yurt vs de olur, yardimci olabilecek var midir ?"],
                ["date" => "02.07.2025", "text" => "Slm, Münih’te evinizde mi yaşıyorsunuz? İlk etapta odamı WG şeklinde mi kiralıyorsunuz?"],
                ["date" => "16.08.2022", "text" => "Bende yurt dışına eczacı olarak gitmek istiyorum bu konuda bilgisi olan yardımcı olabilir mi?"],
                ["date" => "25.08.2023", "text" => "Arkadaşlar üniversite için yurt bulmakta acele etmeli miyiz?"],
                ["date" => "27.01.2024", "text" => "Bu durumda Wohnungsgeberbestätigung belgesini yurt değil, bana odayı kiralayan öğrenci dolduracak değil mi?"],
                ["date" => "21.03.2024", "text" => "Şuan kalacak yer arıyorum, wg, pansiyon veya yurt. Yardımcı olabilir misiniz?"],
                ["date" => "30.11.2022", "text" => "Dortmund ve çevresinde ev veya WG arıyorum ? Ev akradaşı arayan var mı ?"],
                ["date" => "10.01.2023", "text" => "Almanyada okunacak en uygun dil okulu ve yurt sorunu olmayan bi şehir önerebilecek kimse var mı?"],
                ["date" => "17.01.2023", "text" => "Arkadaşlar Duisburg da WG arıyorum çevresinde boş oda olan birileri var mı ?"],
                ["date" => "30.01.2023", "text" => "Stw yurt başvurusu yapan var mı? Ortalama ne zaman sonuç gelir. Vizeden önce mi sonra mı başvurulmalı acaba?"],
                ["date" => "13.03.2023", "text" => "Bielefeld üniversitesi için konaklama/yurt hakkında bilgi verebilecek biri var mı ?"],
                ["date" => "11.04.2023", "text" => "ortaokulu bitirmek üzere olan kardeşim var yurt dışı liselerinden nasıl eğitimini devam ettirebilirim?"],
                ["date" => "13.08.2023", "text" => "arkadaşlar vizeye giderken yurt için bir sözleşme mi oluyor yoksa dekont mu?"],
                ["date" => "26.04.2024", "text" => "Arkadaşlar merhaba.Erasmus+ staj hareketliliği kapsamında Yurt dışında staj yapan var mı?"],
                ["date" => "11.01.2023", "text" => "Uni asist hangi bankalarla anlaşmalı yoksa yurt dışına açılan bütün kartlar geçerli mi ?"],
                ["date" => "15.04.2023", "text" => "Günaydın, bı sorum var. Almanya veya yurt dışı ülkelerine lise öğrencisi olarak gitmek için nasıl bı yol izleyebiliriz?"],
                ["date" => "17.06.2023", "text" => "Öğrenci olarak pasaportum var yurt dışına nasıl çıkabilirim yardımcı olabilecek var mı?"],
            ],
        ],
        "is" => [
            "title" => "Calisma ve Ogrenci Isi",
            "description" => "Werkstudent, Minijob, hospitation ve part-time iss imkanlari",
            "icon" => "briefcase",
            "questions" => [
                ["date" => "12.05.2020", "text" => "Türkiyedeki Telc FSP ye girebilmek için öncesinde Almanyadaki geçerli üç eyaletten birinden is ayarlamis olmak gerekiyor mu?"],
                ["date" => "11.10.2018", "text" => "Dil kursu vizesini tavsiye etmiyorsunuz fakat is arama vizesi icin appro istiyor konsolosluk, dolayisiyla B2 almak da yeterli olmuyor bu konuda ne oneriyorsunuz?"],
                ["date" => "04.08.2021", "text" => "nrw de praxisten bir is gorusmesi teklifi var . fsp siz sanirim baslayamiyorum . approbationda henuz yok sadece b2 sertifikasi var. oneriniz var mi yada bilgilendirme yapmaniz mumkun mu ?"],
                ["date" => "06.09.2021", "text" => "Arkadaslar merhaba, dil kursu vizesi evraklari arasinda is iliskisi beyani diye bir belge var. Bu konuda bilgisi olan var mi? Suan calistigim hastanenin bas hekimliginden mi talep etmeliyim belgeyi?"],
                ["date" => "08.09.2021", "text" => "hospitasyon surecinde normal maasla calisilabilen ve ingilizce curriculum kabul eden is bulma sureci nispeten zor olmayan eyalet hangisini onerirsiniz acaba?"],
                ["date" => "08.10.2023", "text" => "Appro basvurusu ve fsp randevusuyla is arama vizesine basvuruldugunda red alma ihtimali yuksek midir?"],
                ["date" => "05.07.2024", "text" => "berufserlaubnis ile approbationa ayni anda basvurdum, is sozlesmemi be basvurusu ile yolladım. bu durumu hizlandirir mi?"],
                ["date" => "23.07.2024", "text" => "Ve 3. Seçenek tam olarak ne anlama geliyor sadece nrwde is bulacağıma inanıyorum şeklinde bir şey mi? Kanıt istiyorlar mı bunun için?"],
                ["date" => "20.08.2024", "text" => "Türkiye'den alınan FSP ile Almanya'da is pozisyon bulmam mümkün mü ? Hangi eyaletlerde geçerli ? Ne gibi dezavantajlar beni bekliyor ?"],
                ["date" => "23.08.2024", "text" => "Arkadaslar iş iliskisi beyani konusunda tecrubesi olan var mi? Ben is bulmadim fsp’ye girip orada is gorusmeleri yapmak istiyorum. Benzer tecrubesi olan var mi?"],
                ["date" => "05.01.2026", "text" => "Yeni sertifikayı başvurduğu is yeri mi istemiş? Neresi istemiş?"],
                ["date" => "06.07.2023", "text" => "Hazırlıktayken aldığımız studienbescheinigung ile werkstudent yapabiliyor muyuz?"],
                ["date" => "30.07.2023", "text" => "daha önce sorulduysa kusura bakmayın kaçırdım. Göç yasasındaki dil vizesi ile part time çalışabilme durumu doğru mu?"],
                ["date" => "27.01.2023", "text" => "Sizce Almanya'da en uygun kiraların olduğu part time iş bulma olasılığınin yüksek olduğu yer neresi?"],
                ["date" => "26.03.2023", "text" => "Öğrenciler haftalık 20 saat çalışma hakkının yanı sıra minijob yapabiliyor mu?"],
                ["date" => "30.03.2023", "text" => "is bulmak icin de kolaylik saglanacak olan bu yasanin ne zaman yururluge girecegi kesin olarak biliniyor mu ?"],
                ["date" => "06.10.2023", "text" => "Üniversiteye şartlı kabul kazanmış kişilerin dil eğitimi alırken part time çalışma izni çıkacağı ile ilgili haberler vardı gerçekleşti mi?"],
                ["date" => "07.05.2022", "text" => "Ben Azerbaycandan yaziyom,bana Almaniyadan is vizesi gelirmi?A2 seviyesi olursam?"],
                ["date" => "22.02.2023", "text" => "Artik Almanca olmadan is arama vizesiyle almanyaya gidiliyor degil mi?"],
                ["date" => "05.07.2021", "text" => "Yani okul mu okuyacaksaniz, is bulup Ausbildung vs mi yapacaksiniz?"],
                ["date" => "18.10.2023", "text" => "her eyalet için mi? Minijob olarak mı yoksa haftalık 20 saat mi?"],
                ["date" => "18.10.2023", "text" => "şu anda bazı arkadaşlar çalışabiliyor yani minijob mu yapıyorlar acaba?"],
                ["date" => "01.09.2022", "text" => "Is bankasi euro hesabindan 10 bin euroyu fintiba bloke hesaba direkt swift yapmak mi daha mantikli sizce yoksa transferwise gibi aracilar mi kullanilir? Bir de swift ucretini bilen var mi?"],
                ["date" => "05.05.2020", "text" => "Şu konuyu çozemedim; is arama vizesi için appro. basvurusu isteniyor ve basvuru için tercumelerin Turkiye'de yapilmasi kabul edilmiyorsa orjinal belgeleri nasil tercume ettirecegiz ve uzaktan appro. Basvurusunu nasil yapacagiz??"],
                ["date" => "30.11.2018", "text" => "Almanyada halihazirda calisan arkadaslara sormak isterim. Dili gectik diyelim.. appro için evraklari da hazirladik basvurduk. Bu süre icerisinde is basvurusu yapabilecegimiz eyaletler hangileri. Eyaletlerden ikamet veya appro isteniyor diye duyuyorum. O zaman bu kısır döngü degil"],
            ],
        ],
        "ausbildung" => [
            "title" => "Ausbildung Programlari",
            "description" => "Meslek egitimi, Pflege, otelcilik vb. surecler",
            "icon" => "tools",
            "questions" => [
                ["date" => "31.12.2021", "text" => "Konuyla alakası yok diğer kusura bakmayın ama belki bilgisi olan biri vardır diye soruyorum hemşirelik için ausbildung düşünenlerin de bu grup gibi bir grubu var mı acaba? Ya da tanıdığı olan?"],
                ["date" => "08.03.2023", "text" => "Arkadaşlar selam , \" Nachweis über die Berechtigung zur Ausbildung des Heilberufs im Ausbildungs und/oder Herkunftsstaat \" bu belgeyi sağlık bakanlığından nasıl alabiliriz ?"],
                ["date" => "11.08.2023", "text" => "Arkadaşlar lebenslaufta intörnlük senesini berufliche erfahrung kısmına mı yazıyorsunuz yoksa ausbildung kısmına mı?"],
                ["date" => "28.01.2026", "text" => "Praktikum (staj) ile Ausbildung (mesleki eğitim) arasında çok büyük farklar var. Almanca seviyeniz ne durumda ve tam olarak hedefiniz nedir?"],
                ["date" => "10.03.2026", "text" => "“Das Gutachten stellte fest, dass Sie die festgestellten Defizite Ihrer Ausbildung durch Berufserfahrung ausgleichen konnten” demiş. Bu durumda bayernden başvurmak mantıklı mı ?"],
                ["date" => "15.05.2023", "text" => "İyi akşamlar ben Ausbildung üzerinden Almanya’ya gidecem ama daha sonra Üniversite okumak istiyorum.Burda Ausbildungu bırakma ya da üniye geçişte herangi bir sorun çıkabilir mi?"],
                ["date" => "31.12.2021", "text" => "Hallo, willkommen. 😊 Warum haben Sie anderthalb Jahre gewartet, um eine Ausbildung zu machen?"],
                ["date" => "07.05.2022", "text" => "Selamün aleyküm herkese Ausbildung icin B1 sertifikasi gerekiyordu degil mi ?"],
                ["date" => "22.01.2023", "text" => "Almanyada hemşirelik Ausbildung'dur. Bunun dışında derken ne demek istiyorsunuz?"],
                ["date" => "12.02.2023", "text" => "Brüt 1010 € olan Ausbildung maaşından kesintilerle ne kadar kalıyor biliyor musunuz?"],
                ["date" => "12.02.2023", "text" => "Ausbildung ile giderken hesapta para göstermek gerekmiyordu değil mi?"],
                ["date" => "22.05.2023", "text" => "ausbildung için geniş kapsamlı bilgiyi veya güzel anlatan youtube kanalını önerir misiniz ?"],
                ["date" => "05.07.2021", "text" => "Yani okul mu okuyacaksaniz, is bulup Ausbildung vs mi yapacaksiniz?"],
                ["date" => "17.09.2021", "text" => "Mrb Hiç bir meslek bilmiyorum sadece turkiyede bi üni kazanıp almanyada okumak istiyorum . Nasil ausbildung yapabilirim?"],
                ["date" => "22.02.2023", "text" => "Ama pflege studium ile ausbildungtaki mezun olunca ayni yetkilere mi sahip ondan emin degilim, neden ausbildung istemiyorsunuz?"],
                ["date" => "31.07.2023", "text" => "Arkadaşlar dualestudium ile Ausbildung arasındaki fark nedir acaba ?"],
                ["date" => "06.08.2023", "text" => "Üniversite vizesiyle gelen biri Ausbildung bulursa statü değiştirebilir mi ? Yoksa Ausländerbehorde ye mi bağlı ?"],
                ["date" => "05.01.2024", "text" => "Arkadaşlar ausbildung da çocuklar da gelebiliyor mu ? Süreci nerede detaylı görebilirim? Yapan var mı bu şekilde.?"],
                ["date" => "31.08.2024", "text" => "Kurs esnasında iş bulursak kalabilir miyim veyahut Ausbildung yapabilir miyim kurs sonrası onları tam öğrenebileceğim bir kaynak var mı peki bildiğiniz ?"],
                ["date" => "15.12.2021", "text" => "Dual studente ile duales Studium mu kastediyorsun Ausbildung mu?"],
                ["date" => "07.01.2022", "text" => "Ausbildung a ne zaman başvurmak gerekli ve ne zaman bewerbung um sonuç alır?"],
                ["date" => "03.02.2022", "text" => "Teeşkkürler, bir şey daha sormak istiyorum. Meslek lisesi diplomamla teknisyen denkliği alıp gelirsem. Yüksekokul diplomamı ausbildung a eşdeğer denklik alabilir miyim?"],
                ["date" => "01.09.2022", "text" => "Arkadaşlar paramedik mezunu olarak ausbildung ile giden var mı acaba ?"],
                ["date" => "18.09.2022", "text" => "Herkese merhaba. Studium vizesi ile gelip vizesini ausbildung vizesine çeviren var mı?"],
                ["date" => "14.11.2023", "text" => "İyi akşamlar gutachter sürecim için eksik belge olarak “Nachweis über Ableistung der praktischen Ausbildung “ istediler bu belge tam olarak nedir transkriptte yazandan hariç bir belge mi bilen varsa yardımcı olabilir mi?"],
            ],
        ],
        "burs" => [
            "title" => "Burs Imkanlari",
            "description" => "DAAD, Konrad Adenauer, Heinrich Boll vb. burs basvuru sureci",
            "icon" => "star",
            "questions" => [
                ["date" => "06.03.2021", "text" => "Arkadaşlar merhaba , Almanyada hastanede denklik için çalışırken herhangi bir maaş /burs alabiliyor muyuz?"],
                ["date" => "15.12.2022", "text" => "Almanyada üniversteden burs nasıl alınir ? Hangi belgeler gerklidir?"],
                ["date" => "25.01.2023", "text" => "Daad dan takipte kalıyorum o zaman, Başvuru tarihleri başlamadan önce yapmam gereken bir onay, sunmam gereken bir belge vs var mıdır acaba başvurular başlamadan halledeyim, zaman kaybetmeyeyim?"],
                ["date" => "06.03.2023", "text" => "Daad burslarına sadece TEV aracılığı ile mi başvuru yapılabiliyor? Daad sitesinde Türkiyeyi katılımcı listesinde bulamadım ben mi yanlış baktım?"],
                ["date" => "20.04.2023", "text" => "Arkadaşlar iyi günler, Almanya'da üniversiteden kabul alirkenki süreçte burs imkanı çok mu kısıtlı?"],
                ["date" => "20.12.2022", "text" => "Wer hilft mir bei der Bewerbung für ein Stipendium bei der Zulassung nach Deutschland?"],
                ["date" => "06.01.2024", "text" => "Arkadaşlar, Almanya Lisans DAAD Bursu neye göre veriliyor bilen var mı? Başarıya göre mi? yoksa kişinin durumuna göre mi?"],
                ["date" => "12.01.2024", "text" => "Arkadaşlar almanyada lisans okumak için hiç burs alan tanıdığınız yok mu?"],
                ["date" => "16.08.2022", "text" => "Bu burs hakkinda biraz daha bilgi verebilir misiniz? Ben de gormustum bunu fakat yabanci ogrenciler alamiyor diye biliyordum. Basvuru sureclerini adim adim gosterdiginiz bir video olursa eminim cok yardimci olacaktir, site biraz karisik cunku. Tam olarak ne zaman basvurmak gereki"],
                ["date" => "02.10.2023", "text" => "Is sagligi ve guvenliginden universite basvurusu yapmak istiyorum ama almanyada programimla ilgili daad ve baska sitelerede baktim ama is sagligi Ile ilgili fazla bir universite bulamadim. Su anda denk programlari ariyorum ama bununla ilgili bir sonuc alamadim nerden bakabilirim "],
                ["date" => "14.10.2022", "text" => "Oradaki burs ve çalışma imkanlarıyla ilgili bilginiz var mı? Ben bireysel doktoraya başvurmak istiyorum ama yapılandırılmışlara ödenek veriliyor. Ayrıca bireysel doktora yaparken burs alma şansım var mıdır?"],
                ["date" => "15.02.2023", "text" => "Lisansım iç mimarlık üzerine yaptım. Yüksek lisans için %100 ingilizce kendi alanımda yüksek yapmak istiyorum ama iç mimarlık bölümü seçeneği çıkmıyor. Bazı spesifik okul aramaları yaptığımda iç mim. Bölümü yükseklisans ulaştım ama kendi sitelerinden başvuru çıkıyor.Daad sitede a"],
                ["date" => "15.01.2024", "text" => "çok teşekkür ederim. bu üniversitelere şartlı kabul başvurusu nasıl yapacağım hakkında bilginiz de var mı acaba ? uni assist üzerinden baktım fakat şartlı kabule dair bir şey bulamadım ve daad den de başvurular yapılmıyormuş. mail yoluyla iletişime mi geçmeliyim ?"],
                ["date" => "10.09.2021", "text" => "TTB tıp öğrencilerine burs veriyor ona baktın mı?"],
                ["date" => "17.12.2021", "text" => "Arkadaslar merhaba, bu yil DAAD bursuna basvuran oldu mu?"],
                ["date" => "05.01.2023", "text" => "Almanya’da staj için burs bulabileceğimiz bir yer var mı?"],
                ["date" => "14.10.2022", "text" => "DAAD üzerinden araştırdınız mı?"],
                ["date" => "09.09.2023", "text" => "dil kursu öğrencilerine burs veriyorlar mı ki?"],
                ["date" => "25.01.2024", "text" => "Hocam hazırlık da burs alma durumu var mı?"],
                ["date" => "14.10.2022", "text" => "Peki burs başvuruları kabulden sonra mı oluyor?"],
                ["date" => "11.03.2023", "text" => "Merhaba, kabul aldığım üniversitenin kayıt formunu dolduruyorum. Krankenversicherung kısmıni doldurmam gerek. EHIC/DAAD veya Deutsche gesetzliche Krankenversicherung seçeneği var. Burada Allianz sağlık sigortası yapıp gidecegim. Hangi seçenegi secmeliyim ?"],
                ["date" => "29.03.2023", "text" => "Merhaba almanyada yüksek lisans programı arayacağımız daad başka sisteler var mı?"],
                ["date" => "14.01.2024", "text" => "Merhaba, lisans için daad bursu alma olan var mı? Veya almış bi yakını?"],
                ["date" => "02.07.2023", "text" => "Selam arkadaslar almanyada burs imkanlarini nereden ogrenebiliriz?"],
            ],
        ],
    ],
];
