<?php

return [
    'version' => 'v1',
    'document_templates' => [
        [
            'document_code' => 'DOC-DIPL',
            'category_code' => 'DOC-DIPL',
            'name' => 'Diploma + Yeminli Tercume',
            'keywords' => ['diploma', 'mezuniyet', 'graduation'],
            'default_required' => true,
            'accepted' => 'pdf,jpg,png',
            'max_mb' => 10,
        ],
        [
            'document_code' => 'DOC-TRNS',
            'category_code' => 'DOC-TRNS',
            'name' => 'Transkript + Yeminli Tercume',
            'keywords' => ['transkript', 'transcript', 'not dokumu'],
            'default_required' => true,
            'accepted' => 'pdf,jpg,png',
            'max_mb' => 10,
        ],
        [
            'document_code' => 'DOC-UNWN',
            'category_code' => 'DOC-UNWN',
            'name' => 'Kabul / Kazandi Belgesi',
            'keywords' => ['kabul', 'acceptance', 'kazandi', 'admission'],
            'default_required' => true,
            'accepted' => 'pdf,jpg,png',
            'max_mb' => 10,
        ],
        [
            'document_code' => 'DOC-YKSP',
            'category_code' => 'DOC-YKSP',
            'name' => 'YKS / Yerlestirme Belgesi',
            'keywords' => ['yks', 'yerlestirme', 'osym'],
            'default_required' => true,
            'accepted' => 'pdf,jpg,png',
            'max_mb' => 10,
        ],
        [
            'document_code' => 'DOC-IDCR',
            'category_code' => 'DOC-IDCR',
            'name' => 'Kimlik Karti',
            'keywords' => ['kimlik', 'id card', 'tc kimlik'],
            'default_required' => true,
            'accepted' => 'jpg,png,pdf',
            'max_mb' => 5,
        ],
        [
            'document_code' => 'DOC-PASS',
            'category_code' => 'DOC-PASS',
            'name' => 'Pasaport',
            'keywords' => ['pasaport', 'passport'],
            'default_required' => true,
            'accepted' => 'jpg,png,pdf',
            'max_mb' => 10,
        ],
        [
            'document_code' => 'DOC-CV__',
            'category_code' => 'DOC-CV__',
            'name' => 'CV',
            'keywords' => ['cv', 'ozgecmis', 'resume'],
            'default_required' => false,
            'accepted' => 'pdf,doc,docx',
            'max_mb' => 10,
        ],
        [
            'document_code' => 'DOC-MOTV',
            'category_code' => 'DOC-MOTV',
            'name' => 'Motivasyon Mektubu',
            'keywords' => ['motivasyon', 'niyet', 'motivation', 'letter'],
            'default_required' => false,
            'accepted' => 'pdf,doc,docx',
            'max_mb' => 10,
        ],
    ],
    'field_catalog' => [
        'student_registration' => [
            'application_type',
            'educationInfo.highSchool.type',
            'educationInfo.university.name',
            'identity.passportNo',
            'contact.phone',
            'contact.email',
            'lead_source',
            'campaign_code',
            'branch',
            'dealer_code',
        ],
        'student_assignment' => [
            'student_id',
            'senior_email',
            'branch',
            'risk_level',
            'payment_status',
            'dealer_id',
            'is_archived',
        ],
        'guest_application' => [
            'first_name',
            'last_name',
            'email',
            'phone',
            'application_type',
            'lead_source',
            'campaign_code',
            'dealer_code',
            'target_city',
            'target_term',
        ],
        'knowledge_base' => [
            'category',
            'title_tr',
            'body_tr',
            'tags',
            'target_roles',
            'is_published',
            'faq',
            'checklist',
            'vize',
            'universite',
        ],
    ],
    'id_prefix_by_entity' => [
        'student' => [
            'default' => 'STD',
            'from_student_type' => true,
        ],
        'dealer' => [
            'referrer' => 'REF',
            'operational' => 'OPE',
            'default' => 'DLR',
        ],
        'process' => [
            'default' => 'PROC',
        ],
        'document' => [
            'default' => 'DOC',
        ],
    ],
];
