<?php

return [
    'sections' => [
        [
            'key' => 'personal',
            'title' => 'Kişisel Bilgiler',
            'fields' => [
                ['key' => 'first_name', 'label' => 'İsim', 'type' => 'text', 'required' => true, 'max' => 80],
                ['key' => 'last_name', 'label' => 'Soyisim', 'type' => 'text', 'required' => true, 'max' => 80],
                ['key' => 'gender', 'label' => 'Cinsiyetiniz', 'type' => 'select', 'required' => true, 'options' => ['kadin' => 'Kadın', 'erkek' => 'Erkek', 'belirtmek_istemiyorum' => 'Belirtmek istemiyorum']],
                ['key' => 'marital_status', 'label' => 'Medeni Hali', 'type' => 'select', 'required' => true, 'options' => ['bekar' => 'Bekar', 'evli' => 'Evli', 'diger' => 'Diğer']],
                ['key' => 'email', 'label' => 'E-Mail', 'type' => 'email', 'required' => true, 'max' => 120],
                ['key' => 'phone', 'label' => 'Telefon', 'type' => 'phone', 'required' => true, 'max' => 40],
                ['key' => 'reference_text', 'label' => 'Referans', 'type' => 'text', 'required' => false, 'max' => 180],
                ['key' => 'application_city', 'label' => 'Başvuru şehri', 'type' => 'text', 'required' => true, 'max' => 100],
                ['key' => 'application_country', 'label' => 'Başvuru ülkesi', 'type' => 'text', 'required' => true, 'max' => 120],
                ['key' => 'birth_date', 'label' => 'Doğum Tarihiniz', 'type' => 'date', 'required' => true],
                ['key' => 'birth_place', 'label' => 'Doğum yeriniz', 'type' => 'text', 'required' => true, 'max' => 120],
            ],
        ],
        [
            'key' => 'address',
            'title' => 'Adres Bilgileri',
            'fields' => [
                ['key' => 'address_full', 'label' => 'Açık Adresiniz', 'type' => 'text', 'required' => true, 'max' => 255],
                ['key' => 'postal_code', 'label' => 'Posta kodu', 'type' => 'text', 'required' => true, 'max' => 32],
                ['key' => 'district', 'label' => 'İlçe', 'type' => 'text', 'required' => true, 'max' => 120],
                ['key' => 'city', 'label' => 'İl', 'type' => 'text', 'required' => true, 'max' => 120],
            ],
        ],
        [
            'key' => 'education',
            'title' => 'Eğitim Bilgileri',
            'fields' => [
                ['key' => 'education_level', 'label' => 'Eğitim seviyeniz', 'type' => 'select', 'required' => true, 'options' => ['lise' => 'Lise', 'on_lisans' => 'Ön Lisans', 'lisans' => 'Lisans', 'master' => 'Master']],
                ['key' => 'primary_start_date', 'label' => 'İlkokul başlama tarihi', 'type' => 'date', 'required' => true],
                ['key' => 'primary_end_date', 'label' => 'İlkokul bitirme tarihi', 'type' => 'date', 'required' => true],
                ['key' => 'primary_gpa', 'label' => 'İlkokul mezuniyet ortalaması', 'type' => 'text', 'required' => false, 'max' => 32],
                ['key' => 'middle_start_date', 'label' => 'Ortaokul başlama tarihi', 'type' => 'date', 'required' => true],
                ['key' => 'middle_end_date', 'label' => 'Ortaokul bitirme tarihi', 'type' => 'date', 'required' => true],
                ['key' => 'middle_gpa', 'label' => 'Ortaokul mezuniyet ortalaması', 'type' => 'text', 'required' => false, 'max' => 32],
                ['key' => 'middle_school_name', 'label' => 'Mezun olduğunuz ortaokul', 'type' => 'text', 'required' => true, 'max' => 180],
                ['key' => 'high_start_date', 'label' => 'Lise başlama tarihi', 'type' => 'date', 'required' => true],
                ['key' => 'high_end_date', 'label' => 'Lise mezuniyet tarihi', 'type' => 'date', 'required' => true],
                ['key' => 'high_school_name', 'label' => 'Mezun olduğunuz lise', 'type' => 'text', 'required' => true, 'max' => 180],
                ['key' => 'high_gpa', 'label' => 'Lise mezuniyet ortalamanız', 'type' => 'text', 'required' => true, 'max' => 32],
                ['key' => 'university_name', 'label' => 'Üniversite adı (öğrenciyseniz)', 'type' => 'text', 'required' => false, 'max' => 180],
                ['key' => 'university_department', 'label' => 'Üniversite bölüm adı (öğrenciyseniz)', 'type' => 'text', 'required' => false, 'max' => 180],
            ],
        ],
        [
            'key' => 'language',
            'title' => 'Dil Bilgileri',
            'fields' => [
                ['key' => 'has_german_course', 'label' => 'Almanca kursuna kayıtlı mısınız?', 'type' => 'select', 'required' => true, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
                ['key' => 'german_course_name', 'label' => 'Almanca kursu adı', 'type' => 'text', 'required' => false, 'max' => 180],
                ['key' => 'german_level', 'label' => 'Almanca seviyeniz', 'type' => 'select', 'required' => true, 'options' => ['A1' => 'A1', 'A2' => 'A2', 'B1' => 'B1', 'B2' => 'B2', 'C1' => 'C1', 'C2' => 'C2']],
                ['key' => 'has_english_course', 'label' => 'İngilizce kursuna gidiyor musunuz?', 'type' => 'select', 'required' => true, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
                ['key' => 'english_level', 'label' => 'İngilizce dil seviyeniz', 'type' => 'select', 'required' => true, 'options' => ['A1' => 'A1', 'A2' => 'A2', 'B1' => 'B1', 'B2' => 'B2', 'C1' => 'C1', 'C2' => 'C2']],
                ['key' => 'other_language_level', 'label' => 'Diğer diller dil seviyesi', 'type' => 'select', 'required' => false, 'options' => ['yok' => 'Yok', 'A1' => 'A1', 'A2' => 'A2', 'B1' => 'B1', 'B2' => 'B2', 'C1' => 'C1', 'C2' => 'C2']],
            ],
        ],
        [
            'key' => 'target_finance',
            'title' => 'Hedef ve Finans',
            'fields' => [
                ['key' => 'target_program', 'label' => 'Hedef bölüm/program', 'type' => 'text', 'required' => true, 'max' => 180],
                ['key' => 'target_term', 'label' => 'Üniversite başlangıç tarihi hedefi', 'type' => 'date', 'required' => true],
                ['key' => 'finance_method', 'label' => 'Üniversite başvurusu finans yöntemi', 'type' => 'select', 'required' => true, 'options' => ['blokeli_hesap' => 'Blokeli Hesap', 'sponsor' => 'Sponsor', 'aile_destegi' => 'Aile Desteği', 'diger' => 'Diğer']],
                ['key' => 'financial_budget_eur', 'label' => 'Tahmini aylık bütçe (EUR)', 'type' => 'money', 'required' => false, 'max' => 32],
                ['key' => 'blocked_account_knowledge', 'label' => 'Bloke hesap gerekliliğini biliyor musunuz?', 'type' => 'select', 'required' => true, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
            ],
        ],
        [
            'key' => 'passport_travel',
            'title' => 'Pasaport ve Seyahat',
            'fields' => [
                ['key' => 'has_passport', 'label' => 'Pasaportunuz var mı?', 'type' => 'select', 'required' => true, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
                ['key' => 'passport_number', 'label' => 'Pasaport seri numarası', 'type' => 'text', 'required' => true, 'max' => 64],
                ['key' => 'visa_history', 'label' => 'Daha önce vize başvurusu yaptınız mı?', 'type' => 'select', 'required' => true, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
                ['key' => 'abroad_experience', 'label' => 'Yurt dışı eğitim/iş deneyimi oldu mu?', 'type' => 'select', 'required' => true, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
                ['key' => 'health_condition', 'label' => 'Özel sağlık durumu gereksinimi var mı?', 'type' => 'select', 'required' => true, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
                ['key' => 'other_country_plan', 'label' => 'Başka ülkede üniversite düşündünüz mü?', 'type' => 'select', 'required' => false, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
                ['key' => 'lived_in_germany', 'label' => 'Daha önce Almanya’da yaşadınız mı?', 'type' => 'select', 'required' => true, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
                ['key' => 'germany_stay_dates', 'label' => 'Almanya’da kaldığınız tarih aralıkları', 'type' => 'text', 'required' => false, 'max' => 180],
                ['key' => 'germany_last_three_addresses', 'label' => 'Almanya son 3 ikamet (tarih/yer)', 'type' => 'textarea', 'required' => false, 'max' => 3000],
                ['key' => 'germany_references', 'label' => 'Almanya referanslarınız', 'type' => 'textarea', 'required' => false, 'max' => 3000],
            ],
        ],
        [
            'key' => 'family',
            'title' => 'Aile Bilgileri',
            'fields' => [
                ['key' => 'father_full_name', 'label' => 'Babanızın Adı Soyadı', 'type' => 'text', 'required' => true, 'max' => 180],
                ['key' => 'father_birth_date', 'label' => 'Babanızın doğum tarihi', 'type' => 'date', 'required' => true],
                ['key' => 'father_job', 'label' => 'Babanızın mesleği', 'type' => 'text', 'required' => true, 'max' => 120],
                ['key' => 'father_birth_place', 'label' => 'Babanızın doğum yeri', 'type' => 'text', 'required' => true, 'max' => 120],
                ['key' => 'father_address', 'label' => 'Babanızın açık adresi', 'type' => 'text', 'required' => true, 'max' => 255],
                ['key' => 'mother_full_name', 'label' => 'Annenizin adı soyadı', 'type' => 'text', 'required' => true, 'max' => 180],
                ['key' => 'mother_birth_date', 'label' => 'Annenizin doğum tarihi', 'type' => 'date', 'required' => true],
                ['key' => 'mother_birth_place', 'label' => 'Annenizin doğum yeri', 'type' => 'text', 'required' => true, 'max' => 120],
                ['key' => 'mother_job', 'label' => 'Annenizin mesleği', 'type' => 'text', 'required' => true, 'max' => 120],
                ['key' => 'mother_address', 'label' => 'Annenizin açık adresi', 'type' => 'text', 'required' => true, 'max' => 255],
            ],
        ],
        [
            'key' => 'social',
            'title' => 'Sosyal ve Referans Bilgileri',
            'fields' => [
                ['key' => 'social_projects', 'label' => 'Bilimsel/sosyal projelerde yer aldınız mı?', 'type' => 'text', 'required' => false, 'max' => 255],
                ['key' => 'teacher_reference_exists', 'label' => 'Öğretmen referansı var mı?', 'type' => 'select', 'required' => false, 'options' => ['evet' => 'Evet', 'hayir' => 'Hayır']],
                ['key' => 'teacher_reference_contact', 'label' => 'Referans isim soyisim ve iletişim', 'type' => 'text', 'required' => false, 'max' => 255],
                ['key' => 'notes', 'label' => 'Eklemek istediğiniz açıklama', 'type' => 'textarea', 'required' => false, 'max' => 5000],
                ['key' => 'motivation_text', 'label' => 'Motivasyon metni', 'type' => 'textarea', 'required' => true, 'max' => 5000, 'min' => 20],
            ],
        ],
    ],
    'document_upload_notes' => [
        'Almanca dil seviyenizin belgesi (sertifika) -> Belgeler ekranından yükleyin.',
        'İngilizce dil seviyenizin belgesi (sertifika) -> Belgeler ekranından yükleyin.',
        'Lise Diploma, Transkript, YKS, Pasaport, Kimlik, CV, Motivasyon mektubu -> Ön Kayıt Belgeleri ekranından yükleyin.',
        'Sosyal proje belgeleri -> Belgeler ekranından kategori seçerek yükleyin.',
    ],
];
