<?php
/**
 * MentorDE İkon Karşılık Tablosu
 * Premium (Emoji) ↔ Minimalist (Unicode Geometrik)
 *
 * Kullanım:
 *   @php $i = config('mentorde-icons.'.session('mentorde_design','premium')); @endphp
 *   <span class="nav-icon">{{ $i['home'] }}</span>
 *
 * Alternatif: public/js/ içindeki __ICON_MAP JS objesi otomatik swap yapar.
 */

return [

    'premium' => [
        // Nav
        'home'        => '🏠',
        'form'        => '📋',
        'calendar'    => '📅',
        'docs'        => '📂',
        'process'     => '🔄',
        'services'    => '🎓',
        'contract'    => '📜',
        'instdocs'    => '🏛️',
        'shipment'    => '📦',
        'checklist'   => '✅',
        'vault'       => '🔐',
        'messages'    => '💬',
        'ticket'      => '🎫',
        'docbuilder'  => '📝',
        'materials'   => '📚',
        'payments'    => '💳',
        'bell'        => '🔔',
        'profile'     => '👤',
        'settings'    => '⚙️',
        'logout'      => '🚪',
        'feedback'    => '💡',
        'money'       => '💰',
        'ai'          => '🤖',
        'link'        => '🔗',
        'chart'       => '📊',
        'trend'       => '📈',
        'inbox'       => '📬',
        'dealer'      => '🏪',
        'team'        => '👥',
        'advisor'     => '👨‍💼',
        'students'    => '👨‍🎓',
        'pipeline'    => '🗂',
        'unimap'      => '🗺️',
        'theme'       => '🎨',
        'add'         => '➕',
        'upload'      => '📎',
        'support'     => '🎫',
        'lock'        => '🔒',
        'globe'       => '🌍',
        'trophy'      => '🏆',
        'star'        => '⭐',
        'bolt'        => '⚡',
        'warning'     => '⚠',
        'check'       => '✅',
        'cross'       => '❌',
        'wait'        => '⏳',
        // KPI
        'kpi_docs'    => '📄',
        'kpi_date'    => '📅',
        'kpi_money'   => '💰',
        'kpi_msg'     => '💬',
        'kpi_student' => '🎓',
    ],

    'minimalist' => [
        // Nav
        'home'        => '⌂',
        'form'        => '□',
        'calendar'    => '◻',
        'docs'        => '▤',
        'process'     => '◫',
        'services'    => '▦',
        'contract'    => '▥',
        'instdocs'    => '◇',
        'shipment'    => '▣',
        'checklist'   => '☐',
        'vault'       => '◉',
        'messages'    => '◱',
        'ticket'      => '◲',
        'docbuilder'  => '□',
        'materials'   => '≡',
        'payments'    => '▭',
        'bell'        => '△',
        'profile'     => '○',
        'settings'    => '◉',
        'logout'      => '→',
        'feedback'    => '□',
        'money'       => '◎',
        'ai'          => '◈',
        'link'        => '⊞',
        'chart'       => '▥',
        'trend'       => '△',
        'inbox'       => '◱',
        'dealer'      => '◔',
        'team'        => '◔',
        'advisor'     => '○',
        'students'    => '◫',
        'pipeline'    => '▦',
        'unimap'      => '▦',
        'theme'       => '◐',
        'add'         => '+',
        'upload'      => '↑',
        'support'     => '?',
        'lock'        => '◉',
        'globe'       => '◯',
        'trophy'      => '☆',
        'star'        => '☆',
        'bolt'        => '◆',
        'warning'     => '!',
        'check'       => '●',
        'cross'       => '○',
        'wait'        => '◷',
        // KPI
        'kpi_docs'    => '□',
        'kpi_date'    => '◻',
        'kpi_money'   => '◎',
        'kpi_msg'     => '◱',
        'kpi_student' => '◫',
    ],

];
