<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Hizmet Paketleri
    |--------------------------------------------------------------------------
    | Her paket, kucuk hizmet kategorilerinin birlesmesinden olusur.
    | Basic  = Universite + Vize + Finans
    | Plus   = Basic + Konaklama
    | Premium = Plus + Yurtdisi Hizmetleri
    */

    'packages' => [
        [
            'code'             => 'pkg_basic',
            'title'            => 'Basic Paket',
            'price'            => '1.490 EUR',
            'price_amount'     => 1490,
            'currency'         => 'EUR',
            'includes'         => 'Universite + Vize + Finansal Islemler',
            'is_active'        => true,
            'sort_order'       => 1,
            'features'         => [
                'Universite & Bolum Secimi',
                'Uni-Assist & Resmi Basvurular',
                'Basvuru Takibi & Kabul Sureci',
                'Konsolosluk Vize Randevusu',
                'Vize Basvuru Dosyasi Hazirlama',
                'Vize Niyet Mektubu Hazirlama',
                'Vize Mulakat Oryantasyonu',
                'Bloke Hesap (Sperrkonto) Acma',
                'Saglik Sigortasi Sureci',
            ],
            'included_categories' => ['uni', 'visa', 'finance'],
            'included_extras'  => [
                'uni_dept_selection',
                'uni_assist_apply',
                'uni_application_tracking',
                'visa_consulate_appointment',
                'visa_file_preparation',
                'visa_intent_letter',
                'visa_interview_orient',
                'finance_blocked_account',
                'finance_health_insurance',
            ],
            'max_universities' => 3,
            'includes_visa'    => true,
            'includes_housing' => false,
            'support_level'    => 'email',
            'validity_months'  => 12,
        ],
        [
            'code'             => 'pkg_plus',
            'title'            => 'Plus Paket',
            'price'            => '2.490 EUR',
            'price_amount'     => 2490,
            'currency'         => 'EUR',
            'includes'         => 'Basic + Konaklama',
            'is_active'        => true,
            'sort_order'       => 2,
            'features'         => [
                'Basic Paket iceriginin tamami',
                'Konaklama Ayarlanmasi',
                'Devlet Yurdu Basvurulari',
                'Konaklama Bilgilendirme',
                'Universite danismanligi (max 5 basvuru)',
                'Haftalik durum raporu',
            ],
            'included_categories' => ['uni', 'visa', 'finance', 'accommodation'],
            'included_extras'  => [
                'uni_dept_selection',
                'uni_assist_apply',
                'uni_application_tracking',
                'visa_consulate_appointment',
                'visa_file_preparation',
                'visa_intent_letter',
                'visa_interview_orient',
                'finance_blocked_account',
                'finance_health_insurance',
                'accom_arrangement',
                'accom_dorm_apply',
                'accom_info',
            ],
            'max_universities' => 5,
            'includes_visa'    => true,
            'includes_housing' => true,
            'support_level'    => 'phone',
            'validity_months'  => 12,
        ],
        [
            'code'             => 'pkg_premium',
            'title'            => 'Premium Paket',
            'price'            => '3.990 EUR',
            'price_amount'     => 3990,
            'currency'         => 'EUR',
            'includes'         => 'Plus + Yurtdisi Hizmetleri + VIP Danisman',
            'is_active'        => true,
            'sort_order'       => 3,
            'features'         => [
                'Plus Paket iceriginin tamami',
                'VIP danisman atamasi',
                'Bire bir mentorluk (aylik 2 seans)',
                'Havalimani Karsilama & Yerlestirme',
                'Banka Hesabi Acilmasi',
                'Ikamet Kaydi (Anmeldung)',
                'Yabancilar Dairesi Vize Basvurusu',
                'AT/11 Saglik Sigortasi Aktivasyonu',
                'Almanya\'da Yasam Semineri',
                'Deutschlandticket & Telefon Hatti',
                'Oncelikli destek hatti',
            ],
            'included_categories' => ['uni', 'visa', 'finance', 'accommodation', 'abroad'],
            'included_extras'  => [
                'uni_dept_selection',
                'uni_assist_apply',
                'uni_application_tracking',
                'visa_consulate_appointment',
                'visa_file_preparation',
                'visa_intent_letter',
                'visa_interview_orient',
                'finance_blocked_account',
                'finance_health_insurance',
                'accom_arrangement',
                'accom_dorm_apply',
                'accom_info',
                'abroad_deutschlandticket',
                'abroad_phone_line',
                'abroad_airport_pickup',
                'abroad_bank_account',
                'abroad_residence_reg',
                'abroad_foreigners_office',
                'abroad_health_activate',
                'abroad_life_seminar',
            ],
            'max_universities' => 10,
            'includes_visa'    => true,
            'includes_housing' => true,
            'support_level'    => 'vip',
            'validity_months'  => 18,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Hizmet Kategorileri
    |--------------------------------------------------------------------------
    */

    'service_categories' => [
        [
            'key'   => 'uni',
            'title' => 'Universite Basvurusu',
            'icon'  => '🎓',
            'color' => '#4b8cf7',
            'included_in' => ['pkg_basic', 'pkg_plus', 'pkg_premium'],
        ],
        [
            'key'   => 'visa',
            'title' => 'Vize Basvurusu',
            'icon'  => '🛂',
            'color' => '#7c3aed',
            'included_in' => ['pkg_basic', 'pkg_plus', 'pkg_premium'],
        ],
        [
            'key'   => 'finance',
            'title' => 'Finansal Islemler',
            'icon'  => '💰',
            'color' => '#059669',
            'included_in' => ['pkg_basic', 'pkg_plus', 'pkg_premium'],
        ],
        [
            'key'   => 'accommodation',
            'title' => 'Konaklama',
            'icon'  => '🏠',
            'color' => '#d97706',
            'included_in' => ['pkg_plus', 'pkg_premium'],
        ],
        [
            'key'   => 'abroad',
            'title' => 'Yurtdisi Hizmetleri',
            'icon'  => '✈️',
            'color' => '#0891b2',
            'included_in' => ['pkg_premium'],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Ek Hizmetler
    |--------------------------------------------------------------------------
    */

    'extra_services' => [

        // -- Universite Basvurusu --
        [
            'code'         => 'uni_dept_selection',
            'category'     => 'uni',
            'title'        => 'Universite & Bolum Secimi',
            'price'        => '490 EUR',
            'price_amount' => 490,
            'currency'     => 'EUR',
            'description'  => 'Profilinize uygun universite ve bolum analizi, oneri listesi',
            'is_active'    => true,
            'sort_order'   => 10,
        ],
        [
            'code'         => 'uni_assist_apply',
            'category'     => 'uni',
            'title'        => 'Uni-Assist & Resmi Basvurular',
            'price'        => '390 EUR',
            'price_amount' => 390,
            'currency'     => 'EUR',
            'description'  => 'Uni-Assist portali ve universitelere direkt online basvuru',
            'is_active'    => true,
            'sort_order'   => 11,
        ],
        [
            'code'         => 'uni_application_tracking',
            'category'     => 'uni',
            'title'        => 'Basvuru Takibi & Kabul Sureci',
            'price'        => '290 EUR',
            'price_amount' => 290,
            'currency'     => 'EUR',
            'description'  => 'Basvuru durumu takibi, kabul mektubu ve sonraki adimlar',
            'is_active'    => true,
            'sort_order'   => 12,
        ],

        // -- Vize Basvurusu --
        [
            'code'         => 'visa_consulate_appointment',
            'category'     => 'visa',
            'title'        => 'Konsolosluk Vize Randevusu',
            'price'        => '190 EUR',
            'price_amount' => 190,
            'currency'     => 'EUR',
            'description'  => 'Alman konsoloslugundan ogrenci vizesi randevusu alinmasi',
            'is_active'    => true,
            'sort_order'   => 20,
        ],
        [
            'code'         => 'visa_file_preparation',
            'category'     => 'visa',
            'title'        => 'Vize Basvuru Dosyasi Hazirlama',
            'price'        => '240 EUR',
            'price_amount' => 240,
            'currency'     => 'EUR',
            'description'  => 'Tum vize evraklarinin eksiksiz hazirlanmasi ve kontrolu',
            'is_active'    => true,
            'sort_order'   => 21,
        ],
        [
            'code'         => 'visa_intent_letter',
            'category'     => 'visa',
            'title'        => 'Vize Niyet Mektubu Hazirlama',
            'price'        => '120 EUR',
            'price_amount' => 120,
            'currency'     => 'EUR',
            'description'  => 'Kisisellesirilmis motivasyon/niyet mektubu hazirlama',
            'is_active'    => true,
            'sort_order'   => 22,
        ],
        [
            'code'         => 'visa_interview_orient',
            'category'     => 'visa',
            'title'        => 'Vize Mulakat Oryantasyonu',
            'price'        => '120 EUR',
            'price_amount' => 120,
            'currency'     => 'EUR',
            'description'  => 'Konsolosluk mulakatina hazirlik ve sik sorulan sorular',
            'is_active'    => true,
            'sort_order'   => 23,
        ],

        // -- Finansal Islemler --
        [
            'code'         => 'finance_blocked_account',
            'category'     => 'finance',
            'title'        => 'Bloke Hesap (Sperrkonto) Acma',
            'price'        => '190 EUR',
            'price_amount' => 190,
            'currency'     => 'EUR',
            'description'  => 'Vize icin zorunlu bloke hesap acilis sureci destegi',
            'is_active'    => true,
            'sort_order'   => 30,
        ],
        [
            'code'         => 'finance_health_insurance',
            'category'     => 'finance',
            'title'        => 'Saglik Sigortasi Sureci',
            'price'        => '160 EUR',
            'price_amount' => 160,
            'currency'     => 'EUR',
            'description'  => 'Ogrenci saglik sigortasi secimi ve basvuru destegi',
            'is_active'    => true,
            'sort_order'   => 31,
        ],

        // -- Konaklama --
        [
            'code'         => 'accom_arrangement',
            'category'     => 'accommodation',
            'title'        => 'Konaklama Ayarlanmasi',
            'price'        => '290 EUR',
            'price_amount' => 290,
            'currency'     => 'EUR',
            'description'  => 'Daire/oda arama, ilan takibi ve iletisim koordinasyonu',
            'is_active'    => true,
            'sort_order'   => 40,
        ],
        [
            'code'         => 'accom_dorm_apply',
            'category'     => 'accommodation',
            'title'        => 'Devlet Yurdu Basvurulari',
            'price'        => '140 EUR',
            'price_amount' => 140,
            'currency'     => 'EUR',
            'description'  => 'Studierendenwerk yurt basvurularinin yapilmasi',
            'is_active'    => true,
            'sort_order'   => 41,
        ],
        [
            'code'         => 'accom_info',
            'category'     => 'accommodation',
            'title'        => 'Konaklama Bilgilendirme',
            'price'        => '90 EUR',
            'price_amount' => 90,
            'currency'     => 'EUR',
            'description'  => 'Konaklama yontemi, surec ve bolge hakkinda detayli rehberlik',
            'is_active'    => true,
            'sort_order'   => 42,
        ],

        // -- Yurtdisi Hizmetleri --
        [
            'code'         => 'abroad_deutschlandticket',
            'category'     => 'abroad',
            'title'        => 'Deutschlandticket Satin Alma',
            'price'        => '49 EUR',
            'price_amount' => 49,
            'currency'     => 'EUR',
            'description'  => 'Almanya geneli toplu tasima karti aktivasyonu',
            'is_active'    => true,
            'sort_order'   => 50,
        ],
        [
            'code'         => 'abroad_phone_line',
            'category'     => 'abroad',
            'title'        => 'Yurt Disi Telefon Hatti',
            'price'        => '79 EUR',
            'price_amount' => 79,
            'currency'     => 'EUR',
            'description'  => 'Alman SIM karti temin ve aktivasyon destegi',
            'is_active'    => true,
            'sort_order'   => 51,
        ],
        [
            'code'         => 'abroad_airport_pickup',
            'category'     => 'abroad',
            'title'        => 'Havalimani Karsilama & Yerlestirme',
            'price'        => '149 EUR',
            'price_amount' => 149,
            'currency'     => 'EUR',
            'description'  => 'Varis havalimaninda karsilama ve ikamet yerine ulasim',
            'is_active'    => true,
            'sort_order'   => 52,
        ],
        [
            'code'         => 'abroad_bank_account',
            'category'     => 'abroad',
            'title'        => 'Banka Hesabi Acilmasi',
            'price'        => '99 EUR',
            'price_amount' => 99,
            'currency'     => 'EUR',
            'description'  => 'Almanya\'da ogrenci banka hesabi acma sureci',
            'is_active'    => true,
            'sort_order'   => 53,
        ],
        [
            'code'         => 'abroad_residence_reg',
            'category'     => 'abroad',
            'title'        => 'Ikamet Kaydi (Anmeldung)',
            'price'        => '99 EUR',
            'price_amount' => 99,
            'currency'     => 'EUR',
            'description'  => 'Belediyeye adres kayit (Anmeldung) surecinde destek',
            'is_active'    => true,
            'sort_order'   => 54,
        ],
        [
            'code'         => 'abroad_foreigners_office',
            'category'     => 'abroad',
            'title'        => 'Yabancilar Dairesi Vize Basvurusu',
            'price'        => '199 EUR',
            'price_amount' => 199,
            'currency'     => 'EUR',
            'description'  => 'Auslanderbehorde\'de oturma izni basvurusu destegi',
            'is_active'    => true,
            'sort_order'   => 55,
        ],
        [
            'code'         => 'abroad_health_activate',
            'category'     => 'abroad',
            'title'        => 'AT/11 Saglik Sigortasi Aktivasyonu',
            'price'        => '149 EUR',
            'price_amount' => 149,
            'currency'     => 'EUR',
            'description'  => 'Almanya\'da AT/11 formunu aktive etme ve universiteye teslim',
            'is_active'    => true,
            'sort_order'   => 56,
        ],
        [
            'code'         => 'abroad_life_seminar',
            'category'     => 'abroad',
            'title'        => 'Almanya\'da Yasam Semineri',
            'price'        => '149 EUR',
            'price_amount' => 149,
            'currency'     => 'EUR',
            'description'  => 'Almanya\'da gunluk yasam, kultur ve ogrenci haklari semineri',
            'is_active'    => true,
            'sort_order'   => 57,
        ],

        // -- Eski kodlar (geriye donuk uyum) --
        [
            'code'         => 'vip_meeting',
            'category'     => 'other',
            'title'        => 'VIP Danismanlik Toplantisi',
            'price'        => '250 EUR',
            'price_amount' => 250,
            'currency'     => 'EUR',
            'description'  => '60 dakika birebir danismanlik gorusmesi',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
        [
            'code'         => 'blocked_account_support',
            'category'     => 'other',
            'title'        => 'Bloke Hesap Destegi',
            'price'        => '150 EUR',
            'price_amount' => 150,
            'currency'     => 'EUR',
            'description'  => 'Sperrkonto acilis rehberligi',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
        [
            'code'         => 'visa_file_review',
            'category'     => 'other',
            'title'        => 'Vize Dosya On Inceleme',
            'price'        => '200 EUR',
            'price_amount' => 200,
            'currency'     => 'EUR',
            'description'  => 'Vize basvuru dosyasinin eksiksizlik kontrolu',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
        [
            'code'         => 'airport_pickup',
            'category'     => 'other',
            'title'        => 'Havaalani Karsilama',
            'price'        => '100 EUR',
            'price_amount' => 100,
            'currency'     => 'EUR',
            'description'  => 'Havaalani karsilama hizmeti',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
        [
            'code'         => 'accommodation_support',
            'category'     => 'other',
            'title'        => 'Konaklama Destegi',
            'price'        => '300 EUR',
            'price_amount' => 300,
            'currency'     => 'EUR',
            'description'  => 'Yurt/daire arama ve basvuru destegi',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
    ],

];
