<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Hizmet Paketleri
    |--------------------------------------------------------------------------
    */

    'packages' => [
        [
            'code'             => 'pkg_basic',
            'title'            => 'Basic Paket',
            'price'            => '1.490 EUR',
            'price_amount'     => 1490,
            'currency'         => 'EUR',
            'includes'         => 'Başvuru + evrak kontrol + onboarding',
            'is_active'        => true,
            'sort_order'       => 1,
            'features'         => [
                'Başvuru dosyası hazırlama',
                'Evrak kontrol ve düzeltme',
                'Onboarding süreci rehberliği',
            ],
            'max_universities' => 3,
            'includes_visa'    => false,
            'includes_housing' => false,
            'support_level'    => 'email',
            'validity_months'  => 12,
        ],
        [
            'code'             => 'pkg_plus',
            'title'            => 'Plus Paket',
            'price'            => '2.490 EUR',
            'price_amount'     => 2490,
            'currency'         => 'EUR',
            'includes'         => 'Basic + süreç takibi + üniversite danışmanlığı',
            'is_active'        => true,
            'sort_order'       => 2,
            'features'         => [
                'Basic Paket içeriğinin tamamı',
                'Üniversite süreç takibi',
                'Üniversite danışmanlığı (max 5 başvuru)',
                'Haftalık durum raporu',
            ],
            'max_universities' => 5,
            'includes_visa'    => false,
            'includes_housing' => false,
            'support_level'    => 'phone',
            'validity_months'  => 12,
        ],
        [
            'code'             => 'pkg_premium',
            'title'            => 'Premium Paket',
            'price'            => '3.990 EUR',
            'price_amount'     => 3990,
            'currency'         => 'EUR',
            'includes'         => 'Plus + VIP danışman + bire bir mentorluk',
            'is_active'        => true,
            'sort_order'       => 3,
            'features'         => [
                'Plus Paket içeriğinin tamamı',
                'VIP danışman ataması',
                'Bire bir mentorluk (aylık 2 seans)',
                'Vize dosya ön inceleme',
                'Konaklama danışmanlığı',
                'Öncelikli destek hattı',
            ],
            'max_universities' => 10,
            'includes_visa'    => true,
            'includes_housing' => true,
            'support_level'    => 'vip',
            'validity_months'  => 18,
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Hizmet Kategorileri
    |--------------------------------------------------------------------------
    | Ek hizmetlerin gösterileceği bölümler ve metadata.
    */

    'service_categories' => [
        [
            'key'   => 'uni',
            'title' => 'Üniversite Başvurusu',
            'icon'  => '🎓',
            'color' => '#4b8cf7',
        ],
        [
            'key'   => 'visa',
            'title' => 'Vize Başvurusu',
            'icon'  => '🛂',
            'color' => '#7c3aed',
        ],
        [
            'key'   => 'finance',
            'title' => 'Finansal İşlemler',
            'icon'  => '💰',
            'color' => '#059669',
        ],
        [
            'key'   => 'accommodation',
            'title' => 'Konaklama',
            'icon'  => '🏠',
            'color' => '#d97706',
        ],
        [
            'key'   => 'abroad',
            'title' => 'Yurtdışı Hizmetleri',
            'icon'  => '✈️',
            'color' => '#0891b2',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Ek Hizmetler
    |--------------------------------------------------------------------------
    */

    'extra_services' => [

        // ── Üniversite Başvurusu ─────────────────────────────────────────────
        [
            'code'         => 'uni_dept_selection',
            'category'     => 'uni',
            'title'        => 'Üniversite & Bölüm Seçimi',
            'price'        => '490 EUR',
            'price_amount' => 490,
            'currency'     => 'EUR',
            'description'  => 'Profilinize uygun üniversite ve bölüm analizi, öneri listesi',
            'is_active'    => true,
            'sort_order'   => 10,
        ],
        [
            'code'         => 'uni_assist_apply',
            'category'     => 'uni',
            'title'        => 'Uni-Assist & Resmi Başvurular',
            'price'        => '390 EUR',
            'price_amount' => 390,
            'currency'     => 'EUR',
            'description'  => 'Uni-Assist portalı ve üniversitelere direkt online başvuru',
            'is_active'    => true,
            'sort_order'   => 11,
        ],
        [
            'code'         => 'uni_application_tracking',
            'category'     => 'uni',
            'title'        => 'Başvuru Takibi & Kabul Süreci',
            'price'        => '290 EUR',
            'price_amount' => 290,
            'currency'     => 'EUR',
            'description'  => 'Başvuru durumu takibi, kabul mektubu ve sonraki adımlar',
            'is_active'    => true,
            'sort_order'   => 12,
        ],

        // ── Vize Başvurusu ───────────────────────────────────────────────────
        [
            'code'         => 'visa_consulate_appointment',
            'category'     => 'visa',
            'title'        => 'Konsolosluk Vize Randevusu',
            'price'        => '190 EUR',
            'price_amount' => 190,
            'currency'     => 'EUR',
            'description'  => 'Alman konsolosluğundan öğrenci vizesi randevusu alınması',
            'is_active'    => true,
            'sort_order'   => 20,
        ],
        [
            'code'         => 'visa_file_preparation',
            'category'     => 'visa',
            'title'        => 'Vize Başvuru Dosyası Hazırlama',
            'price'        => '240 EUR',
            'price_amount' => 240,
            'currency'     => 'EUR',
            'description'  => 'Tüm vize evraklarının eksiksiz hazırlanması ve kontrolü',
            'is_active'    => true,
            'sort_order'   => 21,
        ],
        [
            'code'         => 'visa_intent_letter',
            'category'     => 'visa',
            'title'        => 'Vize Niyet Mektubu Hazırlama',
            'price'        => '120 EUR',
            'price_amount' => 120,
            'currency'     => 'EUR',
            'description'  => 'Kişiselleştirilmiş motivasyon/niyet mektubu hazırlama',
            'is_active'    => true,
            'sort_order'   => 22,
        ],
        [
            'code'         => 'visa_interview_orient',
            'category'     => 'visa',
            'title'        => 'Vize Mülakat Oryantasyonu',
            'price'        => '120 EUR',
            'price_amount' => 120,
            'currency'     => 'EUR',
            'description'  => 'Konsolosluk mülakatına hazırlık ve sık sorulan sorular',
            'is_active'    => true,
            'sort_order'   => 23,
        ],

        // ── Finansal İşlemler ────────────────────────────────────────────────
        [
            'code'         => 'finance_blocked_account',
            'category'     => 'finance',
            'title'        => 'Bloke Hesap (Sperrkonto) Açma',
            'price'        => '190 EUR',
            'price_amount' => 190,
            'currency'     => 'EUR',
            'description'  => 'Vize için zorunlu bloke hesap açılış süreci desteği',
            'is_active'    => true,
            'sort_order'   => 30,
        ],
        [
            'code'         => 'finance_health_insurance',
            'category'     => 'finance',
            'title'        => 'Sağlık Sigortası Süreci',
            'price'        => '160 EUR',
            'price_amount' => 160,
            'currency'     => 'EUR',
            'description'  => 'Öğrenci sağlık sigortası seçimi ve başvuru desteği',
            'is_active'    => true,
            'sort_order'   => 31,
        ],

        // ── Konaklama ────────────────────────────────────────────────────────
        [
            'code'         => 'accom_arrangement',
            'category'     => 'accommodation',
            'title'        => 'Konaklama Ayarlanması',
            'price'        => '290 EUR',
            'price_amount' => 290,
            'currency'     => 'EUR',
            'description'  => 'Daire/oda arama, ilan takibi ve iletişim koordinasyonu',
            'is_active'    => true,
            'sort_order'   => 40,
        ],
        [
            'code'         => 'accom_dorm_apply',
            'category'     => 'accommodation',
            'title'        => 'Devlet Yurdu Başvuruları',
            'price'        => '140 EUR',
            'price_amount' => 140,
            'currency'     => 'EUR',
            'description'  => 'Studierendenwerk yurt başvurularının yapılması',
            'is_active'    => true,
            'sort_order'   => 41,
        ],
        [
            'code'         => 'accom_info',
            'category'     => 'accommodation',
            'title'        => 'Konaklama Bilgilendirme',
            'price'        => '90 EUR',
            'price_amount' => 90,
            'currency'     => 'EUR',
            'description'  => 'Konaklama yöntemi, süreç ve bölge hakkında detaylı rehberlik',
            'is_active'    => true,
            'sort_order'   => 42,
        ],

        // ── Yurtdışı Hizmetleri ──────────────────────────────────────────────
        [
            'code'         => 'abroad_deutschlandticket',
            'category'     => 'abroad',
            'title'        => 'Deutschlandticket Satın Alma',
            'price'        => '49 EUR',
            'price_amount' => 49,
            'currency'     => 'EUR',
            'description'  => 'Almanya geneli toplu taşıma kartı aktivasyonu',
            'is_active'    => true,
            'sort_order'   => 50,
        ],
        [
            'code'         => 'abroad_phone_line',
            'category'     => 'abroad',
            'title'        => 'Yurt Dışı Telefon Hattı',
            'price'        => '79 EUR',
            'price_amount' => 79,
            'currency'     => 'EUR',
            'description'  => 'Alman SIM kartı temin ve aktivasyon desteği',
            'is_active'    => true,
            'sort_order'   => 51,
        ],
        [
            'code'         => 'abroad_airport_pickup',
            'category'     => 'abroad',
            'title'        => 'Havalimanı Karşılama & Yerleştirme',
            'price'        => '149 EUR',
            'price_amount' => 149,
            'currency'     => 'EUR',
            'description'  => 'Varış havalimanında karşılama ve ikamet yerine ulaşım',
            'is_active'    => true,
            'sort_order'   => 52,
        ],
        [
            'code'         => 'abroad_bank_account',
            'category'     => 'abroad',
            'title'        => 'Banka Hesabı Açılması',
            'price'        => '99 EUR',
            'price_amount' => 99,
            'currency'     => 'EUR',
            'description'  => 'Almanya\'da öğrenci banka hesabı açma süreci',
            'is_active'    => true,
            'sort_order'   => 53,
        ],
        [
            'code'         => 'abroad_residence_reg',
            'category'     => 'abroad',
            'title'        => 'İkamet Kaydı (Anmeldung)',
            'price'        => '99 EUR',
            'price_amount' => 99,
            'currency'     => 'EUR',
            'description'  => 'Belediyeye adres kayıt (Anmeldung) sürecinde destek',
            'is_active'    => true,
            'sort_order'   => 54,
        ],
        [
            'code'         => 'abroad_foreigners_office',
            'category'     => 'abroad',
            'title'        => 'Yabancılar Dairesi Vize Başvurusu',
            'price'        => '199 EUR',
            'price_amount' => 199,
            'currency'     => 'EUR',
            'description'  => 'Ausländerbehörde\'de oturma izni başvurusu desteği',
            'is_active'    => true,
            'sort_order'   => 55,
        ],
        [
            'code'         => 'abroad_health_activate',
            'category'     => 'abroad',
            'title'        => 'AT/11 Sağlık Sigortası Aktivasyonu',
            'price'        => '149 EUR',
            'price_amount' => 149,
            'currency'     => 'EUR',
            'description'  => 'Almanya\'da AT/11 formunu aktive etme ve üniversiteye teslim',
            'is_active'    => true,
            'sort_order'   => 56,
        ],
        [
            'code'         => 'abroad_life_seminar',
            'category'     => 'abroad',
            'title'        => 'Almanya\'da Yaşam Semineri',
            'price'        => '149 EUR',
            'price_amount' => 149,
            'currency'     => 'EUR',
            'description'  => 'Almanya\'da günlük yaşam, kültür ve öğrenci hakları semineri',
            'is_active'    => true,
            'sort_order'   => 57,
        ],

        // ── Eski kodlar (geriye dönük uyum) ─────────────────────────────────
        [
            'code'         => 'vip_meeting',
            'category'     => 'other',
            'title'        => 'VIP Danışmanlık Toplantısı',
            'price'        => '250 EUR',
            'price_amount' => 250,
            'currency'     => 'EUR',
            'description'  => '60 dakika birebir danışmanlık görüşmesi',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
        [
            'code'         => 'blocked_account_support',
            'category'     => 'other',
            'title'        => 'Bloke Hesap Desteği',
            'price'        => '150 EUR',
            'price_amount' => 150,
            'currency'     => 'EUR',
            'description'  => 'Sperrkonto açılış rehberliği',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
        [
            'code'         => 'visa_file_review',
            'category'     => 'other',
            'title'        => 'Vize Dosya Ön İnceleme',
            'price'        => '200 EUR',
            'price_amount' => 200,
            'currency'     => 'EUR',
            'description'  => 'Vize başvuru dosyasının eksiksizlik kontrolü',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
        [
            'code'         => 'airport_pickup',
            'category'     => 'other',
            'title'        => 'Havaalanı Karşılama',
            'price'        => '100 EUR',
            'price_amount' => 100,
            'currency'     => 'EUR',
            'description'  => 'Havaalanı karşılama hizmeti',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
        [
            'code'         => 'accommodation_support',
            'category'     => 'other',
            'title'        => 'Konaklama Desteği',
            'price'        => '300 EUR',
            'price_amount' => 300,
            'currency'     => 'EUR',
            'description'  => 'Yurt/daire arama ve başvuru desteği',
            'is_active'    => false,
            'sort_order'   => 99,
        ],
    ],

];
